// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAttendanceSession = `-- name: CreateAttendanceSession :one
INSERT INTO attendance_sessions (class_id, taken_by, date)
VALUES ($1, $2, $3)
RETURNING id, class_id, taken_by, date, created_at
`

type CreateAttendanceSessionParams struct {
	ClassID uuid.UUID `json:"class_id"`
	TakenBy uuid.UUID `json:"taken_by"`
	Date    time.Time `json:"date"`
}

func (q *Queries) CreateAttendanceSession(ctx context.Context, arg CreateAttendanceSessionParams) (AttendanceSession, error) {
	row := q.db.QueryRowContext(ctx, createAttendanceSession, arg.ClassID, arg.TakenBy, arg.Date)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.TakenBy,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const getAttendanceRecord = `-- name: GetAttendanceRecord :one
SELECT id, session_id, student_id, status, note FROM attendance_records
WHERE session_id = $1 AND student_id = $2
`

type GetAttendanceRecordParams struct {
	SessionID uuid.UUID `json:"session_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) GetAttendanceRecord(ctx context.Context, arg GetAttendanceRecordParams) (AttendanceRecord, error) {
	row := q.db.QueryRowContext(ctx, getAttendanceRecord, arg.SessionID, arg.StudentID)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StudentID,
		&i.Status,
		&i.Note,
	)
	return i, err
}

const getAttendanceSessionByClassAndDate = `-- name: GetAttendanceSessionByClassAndDate :one
SELECT id, class_id, taken_by, date, created_at FROM attendance_sessions
WHERE class_id = $1 AND date = $2
`

type GetAttendanceSessionByClassAndDateParams struct {
	ClassID uuid.UUID `json:"class_id"`
	Date    time.Time `json:"date"`
}

func (q *Queries) GetAttendanceSessionByClassAndDate(ctx context.Context, arg GetAttendanceSessionByClassAndDateParams) (AttendanceSession, error) {
	row := q.db.QueryRowContext(ctx, getAttendanceSessionByClassAndDate, arg.ClassID, arg.Date)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.TakenBy,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const getAttendanceSessionByID = `-- name: GetAttendanceSessionByID :one
SELECT id, class_id, taken_by, date, created_at FROM attendance_sessions
WHERE id = $1
`

func (q *Queries) GetAttendanceSessionByID(ctx context.Context, id uuid.UUID) (AttendanceSession, error) {
	row := q.db.QueryRowContext(ctx, getAttendanceSessionByID, id)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.TakenBy,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const getAttendanceSummaryByStudent = `-- name: GetAttendanceSummaryByStudent :one
SELECT
    COUNT(*)                                            AS total_days,
    COUNT(*) FILTER (WHERE ar.status = 'present')      AS present,
    COUNT(*) FILTER (WHERE ar.status = 'absent')       AS absent,
    COUNT(*) FILTER (WHERE ar.status = 'late')         AS late,
    COUNT(*) FILTER (WHERE ar.status = 'excused')      AS excused
FROM attendance_records ar
INNER JOIN attendance_sessions ats ON ats.id = ar.session_id
WHERE ar.student_id = $1
  AND ats.class_id  = $2
`

type GetAttendanceSummaryByStudentParams struct {
	StudentID uuid.UUID `json:"student_id"`
	ClassID   uuid.UUID `json:"class_id"`
}

type GetAttendanceSummaryByStudentRow struct {
	TotalDays int64 `json:"total_days"`
	Present   int64 `json:"present"`
	Absent    int64 `json:"absent"`
	Late      int64 `json:"late"`
	Excused   int64 `json:"excused"`
}

func (q *Queries) GetAttendanceSummaryByStudent(ctx context.Context, arg GetAttendanceSummaryByStudentParams) (GetAttendanceSummaryByStudentRow, error) {
	row := q.db.QueryRowContext(ctx, getAttendanceSummaryByStudent, arg.StudentID, arg.ClassID)
	var i GetAttendanceSummaryByStudentRow
	err := row.Scan(
		&i.TotalDays,
		&i.Present,
		&i.Absent,
		&i.Late,
		&i.Excused,
	)
	return i, err
}

const listAttendanceBySession = `-- name: ListAttendanceBySession :many
SELECT
    ar.id, ar.session_id, ar.student_id, ar.status, ar.note,
    sp.full_name     AS student_name,
    sp.index_number  AS student_index
FROM attendance_records ar
INNER JOIN student_profiles sp ON sp.id = ar.student_id
WHERE ar.session_id = $1
ORDER BY sp.full_name ASC
`

type ListAttendanceBySessionRow struct {
	ID           uuid.UUID      `json:"id"`
	SessionID    uuid.UUID      `json:"session_id"`
	StudentID    uuid.UUID      `json:"student_id"`
	Status       string         `json:"status"`
	Note         sql.NullString `json:"note"`
	StudentName  string         `json:"student_name"`
	StudentIndex string         `json:"student_index"`
}

func (q *Queries) ListAttendanceBySession(ctx context.Context, sessionID uuid.UUID) ([]ListAttendanceBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttendanceBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceBySessionRow{}
	for rows.Next() {
		var i ListAttendanceBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StudentID,
			&i.Status,
			&i.Note,
			&i.StudentName,
			&i.StudentIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceByStudent = `-- name: ListAttendanceByStudent :many
SELECT
    ar.id, ar.session_id, ar.student_id, ar.status, ar.note,
    ats.date        AS session_date,
    c.name          AS class_name
FROM attendance_records ar
INNER JOIN attendance_sessions ats ON ats.id = ar.session_id
INNER JOIN classes             c   ON c.id   = ats.class_id
WHERE ar.student_id = $1
ORDER BY ats.date DESC
`

type ListAttendanceByStudentRow struct {
	ID          uuid.UUID      `json:"id"`
	SessionID   uuid.UUID      `json:"session_id"`
	StudentID   uuid.UUID      `json:"student_id"`
	Status      string         `json:"status"`
	Note        sql.NullString `json:"note"`
	SessionDate time.Time      `json:"session_date"`
	ClassName   string         `json:"class_name"`
}

func (q *Queries) ListAttendanceByStudent(ctx context.Context, studentID uuid.UUID) ([]ListAttendanceByStudentRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttendanceByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceByStudentRow{}
	for rows.Next() {
		var i ListAttendanceByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StudentID,
			&i.Status,
			&i.Note,
			&i.SessionDate,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceSessionsByClass = `-- name: ListAttendanceSessionsByClass :many
SELECT id, class_id, taken_by, date, created_at FROM attendance_sessions
WHERE class_id = $1
ORDER BY date DESC
`

func (q *Queries) ListAttendanceSessionsByClass(ctx context.Context, classID uuid.UUID) ([]AttendanceSession, error) {
	rows, err := q.db.QueryContext(ctx, listAttendanceSessionsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceSession{}
	for rows.Next() {
		var i AttendanceSession
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.TakenBy,
			&i.Date,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttendance = `-- name: MarkAttendance :one
INSERT INTO attendance_records (session_id, student_id, status, note)
VALUES ($1, $2, $3, $4)
ON CONFLICT (session_id, student_id) DO UPDATE
SET
    status = EXCLUDED.status,
    note   = EXCLUDED.note
RETURNING id, session_id, student_id, status, note
`

type MarkAttendanceParams struct {
	SessionID uuid.UUID      `json:"session_id"`
	StudentID uuid.UUID      `json:"student_id"`
	Status    string         `json:"status"`
	Note      sql.NullString `json:"note"`
}

func (q *Queries) MarkAttendance(ctx context.Context, arg MarkAttendanceParams) (AttendanceRecord, error) {
	row := q.db.QueryRowContext(ctx, markAttendance,
		arg.SessionID,
		arg.StudentID,
		arg.Status,
		arg.Note,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StudentID,
		&i.Status,
		&i.Note,
	)
	return i, err
}
