// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classrooms.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClassroom = `-- name: CreateClassroom :one
INSERT INTO classrooms (name, code, capacity)
VALUES ($1, $2, $3)
RETURNING id, name, code, capacity, created_at
`

type CreateClassroomParams struct {
	Name     string      `json:"name"`
	Code     pgtype.Text `json:"code"`
	Capacity pgtype.Int4 `json:"capacity"`
}

func (q *Queries) CreateClassroom(ctx context.Context, arg CreateClassroomParams) (Classroom, error) {
	row := q.db.QueryRow(ctx, createClassroom, arg.Name, arg.Code, arg.Capacity)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Capacity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClassroom = `-- name: DeleteClassroom :execrows
DELETE FROM classrooms AS c
WHERE c.id = $1
AND c.id NOT IN (
    SELECT DISTINCT classroom_id FROM timetable_entries WHERE classroom_id IS NOT NULL
)
`

func (q *Queries) DeleteClassroom(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClassroom, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClassroomByID = `-- name: GetClassroomByID :one
SELECT id, name, code, capacity, created_at FROM classrooms
WHERE id = $1
`

func (q *Queries) GetClassroomByID(ctx context.Context, id uuid.UUID) (Classroom, error) {
	row := q.db.QueryRow(ctx, getClassroomByID, id)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Capacity,
		&i.CreatedAt,
	)
	return i, err
}

const listClassrooms = `-- name: ListClassrooms :many
SELECT id, name, code, capacity, created_at FROM classrooms
ORDER BY name ASC
`

func (q *Queries) ListClassrooms(ctx context.Context) ([]Classroom, error) {
	rows, err := q.db.Query(ctx, listClassrooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Classroom{}
	for rows.Next() {
		var i Classroom
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Capacity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassroom = `-- name: UpdateClassroom :one
UPDATE classrooms
SET name = $2, code = $3, capacity = $4
WHERE id = $1
RETURNING id, name, code, capacity, created_at
`

type UpdateClassroomParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	Code     pgtype.Text `json:"code"`
	Capacity pgtype.Int4 `json:"capacity"`
}

func (q *Queries) UpdateClassroom(ctx context.Context, arg UpdateClassroomParams) (Classroom, error) {
	row := q.db.QueryRow(ctx, updateClassroom,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Capacity,
	)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Capacity,
		&i.CreatedAt,
	)
	return i, err
}
