// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertActivationCodes implements pgx.CopyFromSource.
type iteratorForInsertActivationCodes struct {
	rows                 []InsertActivationCodesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertActivationCodes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertActivationCodes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BatchID,
		r.rows[0].Role,
		r.rows[0].StudentID,
		r.rows[0].GuardianID,
		r.rows[0].CodeHash,
		r.rows[0].ExpiresAt,
		r.rows[0].CreatedBy,
	}, nil
}

func (r iteratorForInsertActivationCodes) Err() error {
	return nil
}

func (q *Queries) InsertActivationCodes(ctx context.Context, arg []InsertActivationCodesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"activation_codes"}, []string{"batch_id", "role", "student_id", "guardian_id", "code_hash", "expires_at", "created_by"}, &iteratorForInsertActivationCodes{rows: arg})
}
