// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guardians.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGuardian = `-- name: CreateGuardian :one
INSERT INTO guardians (
    full_name,
    relationship,
    phone,
    email,
    nic_number
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, full_name, relationship, phone, email, created_at, nic_number
`

type CreateGuardianParams struct {
	FullName     string      `json:"full_name"`
	Relationship string      `json:"relationship"`
	Phone        string      `json:"phone"`
	Email        pgtype.Text `json:"email"`
	NicNumber    string      `json:"nic_number"`
}

func (q *Queries) CreateGuardian(ctx context.Context, arg CreateGuardianParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, createGuardian,
		arg.FullName,
		arg.Relationship,
		arg.Phone,
		arg.Email,
		arg.NicNumber,
	)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Relationship,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.NicNumber,
	)
	return i, err
}

const deleteGuardian = `-- name: DeleteGuardian :execrows
DELETE FROM guardians AS g
WHERE g.id = $1
AND g.id NOT IN (
    SELECT DISTINCT guardian_id FROM student_guardians
)
`

// Blocked while linked to any student, since student_guardians cascades on
// delete and silently unlinking a shared guardian from every child would be
// surprising — admins must unlink each student first.
func (q *Queries) DeleteGuardian(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGuardian, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findGuardianDuplicateCandidates = `-- name: FindGuardianDuplicateCandidates :many
SELECT id, user_id, full_name, relationship, phone, email, created_at, nic_number FROM guardians
WHERE phone = $1
   OR ($2::text IS NOT NULL AND email = $2)
ORDER BY full_name ASC
`

type FindGuardianDuplicateCandidatesParams struct {
	Phone string      `json:"phone"`
	Email pgtype.Text `json:"email"`
}

// Near-matches by phone or email, surfaced as a soft warning ("this
// guardian may already exist") when creating a new guardian record —
// never hard-blocked, since a shared home phone across two guardians is
// legitimate.
func (q *Queries) FindGuardianDuplicateCandidates(ctx context.Context, arg FindGuardianDuplicateCandidatesParams) ([]Guardian, error) {
	rows, err := q.db.Query(ctx, findGuardianDuplicateCandidates, arg.Phone, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Guardian{}
	for rows.Next() {
		var i Guardian
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.Relationship,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
			&i.NicNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuardianByID = `-- name: GetGuardianByID :one
SELECT id, user_id, full_name, relationship, phone, email, created_at, nic_number FROM guardians
WHERE id = $1
`

func (q *Queries) GetGuardianByID(ctx context.Context, id uuid.UUID) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardianByID, id)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Relationship,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.NicNumber,
	)
	return i, err
}

const getGuardianByUserID = `-- name: GetGuardianByUserID :one
SELECT id, user_id, full_name, relationship, phone, email, created_at, nic_number FROM guardians
WHERE user_id = $1
`

func (q *Queries) GetGuardianByUserID(ctx context.Context, userID pgtype.UUID) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardianByUserID, userID)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Relationship,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.NicNumber,
	)
	return i, err
}

const getGuardianByUserIDAndNIC = `-- name: GetGuardianByUserIDAndNIC :one
SELECT id, user_id, full_name, relationship, phone, email, created_at, nic_number FROM guardians
WHERE user_id = $1 AND nic_number = $2
`

type GetGuardianByUserIDAndNICParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	NicNumber string      `json:"nic_number"`
}

// Identity check for the unauthenticated forgot-password flow (Phase 8.4) —
// confirms the caller knows this guardian's NIC before a reset token is
// minted for their account.
func (q *Queries) GetGuardianByUserIDAndNIC(ctx context.Context, arg GetGuardianByUserIDAndNICParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardianByUserIDAndNIC, arg.UserID, arg.NicNumber)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Relationship,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.NicNumber,
	)
	return i, err
}

const getPrimaryGuardian = `-- name: GetPrimaryGuardian :one
SELECT
    g.id, g.user_id, g.full_name, g.relationship, g.phone, g.email, g.created_at, g.nic_number
FROM guardians g
INNER JOIN student_guardians sg ON sg.guardian_id = g.id
WHERE sg.student_id = $1
  AND sg.is_primary_contact = TRUE
LIMIT 1
`

func (q *Queries) GetPrimaryGuardian(ctx context.Context, studentID uuid.UUID) (Guardian, error) {
	row := q.db.QueryRow(ctx, getPrimaryGuardian, studentID)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Relationship,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.NicNumber,
	)
	return i, err
}

const isGuardianOfStudent = `-- name: IsGuardianOfStudent :one
SELECT EXISTS (
    SELECT 1
    FROM student_guardians sg
    INNER JOIN guardians g ON g.id = sg.guardian_id
    WHERE g.user_id = $1
      AND sg.student_id = $2
) AS is_guardian
`

type IsGuardianOfStudentParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	StudentID uuid.UUID   `json:"student_id"`
}

// Authorization check: does the signed-in guardian actually have this
// student linked to them? Used to gate GET /me/children/:id/... routes.
func (q *Queries) IsGuardianOfStudent(ctx context.Context, arg IsGuardianOfStudentParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGuardianOfStudent, arg.UserID, arg.StudentID)
	var is_guardian bool
	err := row.Scan(&is_guardian)
	return is_guardian, err
}

const linkGuardianToStudent = `-- name: LinkGuardianToStudent :exec
INSERT INTO student_guardians (student_id, guardian_id, is_primary_contact)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type LinkGuardianToStudentParams struct {
	StudentID        uuid.UUID `json:"student_id"`
	GuardianID       uuid.UUID `json:"guardian_id"`
	IsPrimaryContact bool      `json:"is_primary_contact"`
}

func (q *Queries) LinkGuardianToStudent(ctx context.Context, arg LinkGuardianToStudentParams) error {
	_, err := q.db.Exec(ctx, linkGuardianToStudent, arg.StudentID, arg.GuardianID, arg.IsPrimaryContact)
	return err
}

const listGuardianUserIDsByStudentIDs = `-- name: ListGuardianUserIDsByStudentIDs :many
SELECT DISTINCT g.user_id
FROM guardians g
INNER JOIN student_guardians sg ON sg.guardian_id = g.id
WHERE sg.student_id = ANY($1::uuid[])
  AND g.user_id IS NOT NULL
`

// Distinct guardian user_ids (portal logins only) for a set of students in
// one round trip — used to build notification recipient lists without a
// ListByStudent call per student (see timetable.go's notifyPublication).
func (q *Queries) ListGuardianUserIDsByStudentIDs(ctx context.Context, studentIds []uuid.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listGuardianUserIDsByStudentIDs, studentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardians = `-- name: ListGuardians :many
SELECT g.id, g.user_id, g.full_name, g.relationship, g.phone, g.email, g.created_at, g.nic_number FROM guardians g
WHERE (
    $1::text IS NULL
    OR g.full_name ILIKE '%' || $1 || '%'
    OR g.phone      ILIKE '%' || $1 || '%'
    OR g.email      ILIKE '%' || $1 || '%'
  )
  AND (
    $2::bool IS NOT TRUE
    OR NOT EXISTS (SELECT 1 FROM student_guardians sg WHERE sg.guardian_id = g.id)
  )
ORDER BY g.full_name ASC
`

type ListGuardiansParams struct {
	Search      pgtype.Text `json:"search"`
	OrphansOnly pgtype.Bool `json:"orphans_only"`
}

// Every guardian on file, optionally filtered by a search term matched
// against name/phone/email and/or restricted to "orphans" (linked to no
// student — e.g. their last child left the school). Used both by the
// guardian directory and the "link an existing guardian to this student
// too" search picker (siblings sharing a guardian).
func (q *Queries) ListGuardians(ctx context.Context, arg ListGuardiansParams) ([]Guardian, error) {
	rows, err := q.db.Query(ctx, listGuardians, arg.Search, arg.OrphansOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Guardian{}
	for rows.Next() {
		var i Guardian
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.Relationship,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
			&i.NicNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardiansByStudent = `-- name: ListGuardiansByStudent :many
SELECT
    g.id, g.user_id, g.full_name, g.relationship, g.phone, g.email, g.created_at, g.nic_number,
    sg.is_primary_contact
FROM guardians g
INNER JOIN student_guardians sg ON sg.guardian_id = g.id
WHERE sg.student_id = $1
ORDER BY sg.is_primary_contact DESC, g.full_name ASC
`

type ListGuardiansByStudentRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	FullName         string             `json:"full_name"`
	Relationship     string             `json:"relationship"`
	Phone            string             `json:"phone"`
	Email            pgtype.Text        `json:"email"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	NicNumber        string             `json:"nic_number"`
	IsPrimaryContact bool               `json:"is_primary_contact"`
}

func (q *Queries) ListGuardiansByStudent(ctx context.Context, studentID uuid.UUID) ([]ListGuardiansByStudentRow, error) {
	rows, err := q.db.Query(ctx, listGuardiansByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuardiansByStudentRow{}
	for rows.Next() {
		var i ListGuardiansByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.Relationship,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
			&i.NicNumber,
			&i.IsPrimaryContact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByGuardianID = `-- name: ListStudentsByGuardianID :many
SELECT sp.id, sp.user_id, sp.full_name, sp.index_number, sp.address, sp.phone, sp.whatsapp, sp.special_remarks, sp.created_at, sp.updated_at, sp.gender, sp.house_id, sp.enrollment_status
FROM student_profiles sp
INNER JOIN student_guardians sg ON sg.student_id = sp.id
WHERE sg.guardian_id = $1
ORDER BY sp.full_name ASC
`

// Linked students for the guardian directory's "children" column — works
// regardless of whether the guardian has a portal login (unlike
// ListStudentsByGuardianUserID, which requires one).
func (q *Queries) ListStudentsByGuardianID(ctx context.Context, guardianID uuid.UUID) ([]StudentProfile, error) {
	rows, err := q.db.Query(ctx, listStudentsByGuardianID, guardianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentProfile{}
	for rows.Next() {
		var i StudentProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.IndexNumber,
			&i.Address,
			&i.Phone,
			&i.Whatsapp,
			&i.SpecialRemarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.HouseID,
			&i.EnrollmentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByGuardianUserID = `-- name: ListStudentsByGuardianUserID :many
SELECT
    sp.id, sp.user_id, sp.full_name, sp.index_number, sp.address, sp.phone, sp.whatsapp, sp.special_remarks, sp.created_at, sp.updated_at, sp.gender, sp.house_id, sp.enrollment_status,
    c.id     AS class_id,
    c.name   AS class_name,
    gr.name  AS grade_name
FROM student_profiles sp
INNER JOIN student_guardians sg ON sg.student_id = sp.id
INNER JOIN guardians g          ON g.id = sg.guardian_id
LEFT JOIN class_students cs ON cs.student_id = sp.id
    AND cs.academic_year_id = (SELECT id FROM academic_years WHERE is_current = TRUE LIMIT 1)
LEFT JOIN classes c ON c.id = cs.class_id
LEFT JOIN grades gr ON gr.id = c.grade_id
WHERE g.user_id = $1
ORDER BY sp.full_name ASC
`

type ListStudentsByGuardianUserIDRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	FullName         string             `json:"full_name"`
	IndexNumber      string             `json:"index_number"`
	Address          pgtype.Text        `json:"address"`
	Phone            pgtype.Text        `json:"phone"`
	Whatsapp         pgtype.Text        `json:"whatsapp"`
	SpecialRemarks   pgtype.Text        `json:"special_remarks"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Gender           pgtype.Text        `json:"gender"`
	HouseID          pgtype.UUID        `json:"house_id"`
	EnrollmentStatus string             `json:"enrollment_status"`
	ClassID          pgtype.UUID        `json:"class_id"`
	ClassName        pgtype.Text        `json:"class_name"`
	GradeName        pgtype.Text        `json:"grade_name"`
}

// The signed-in parent's linked children, for the parent portal.
func (q *Queries) ListStudentsByGuardianUserID(ctx context.Context, userID pgtype.UUID) ([]ListStudentsByGuardianUserIDRow, error) {
	rows, err := q.db.Query(ctx, listStudentsByGuardianUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsByGuardianUserIDRow{}
	for rows.Next() {
		var i ListStudentsByGuardianUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.IndexNumber,
			&i.Address,
			&i.Phone,
			&i.Whatsapp,
			&i.SpecialRemarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.HouseID,
			&i.EnrollmentStatus,
			&i.ClassID,
			&i.ClassName,
			&i.GradeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGuardianUserID = `-- name: SetGuardianUserID :exec
UPDATE guardians
SET user_id = $2
WHERE id = $1
`

type SetGuardianUserIDParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Links a guardian record to the ThunderID identity created for their
// portal login (see internal/services/guardian.go ProvisionLogin).
func (q *Queries) SetGuardianUserID(ctx context.Context, arg SetGuardianUserIDParams) error {
	_, err := q.db.Exec(ctx, setGuardianUserID, arg.ID, arg.UserID)
	return err
}

const setPrimaryContact = `-- name: SetPrimaryContact :exec
UPDATE student_guardians
SET is_primary_contact = (guardian_id = $2)
WHERE student_id = $1
`

type SetPrimaryContactParams struct {
	StudentID  uuid.UUID `json:"student_id"`
	GuardianID uuid.UUID `json:"guardian_id"`
}

func (q *Queries) SetPrimaryContact(ctx context.Context, arg SetPrimaryContactParams) error {
	_, err := q.db.Exec(ctx, setPrimaryContact, arg.StudentID, arg.GuardianID)
	return err
}

const unlinkGuardianFromStudent = `-- name: UnlinkGuardianFromStudent :exec
DELETE FROM student_guardians
WHERE student_id = $1 AND guardian_id = $2
`

type UnlinkGuardianFromStudentParams struct {
	StudentID  uuid.UUID `json:"student_id"`
	GuardianID uuid.UUID `json:"guardian_id"`
}

func (q *Queries) UnlinkGuardianFromStudent(ctx context.Context, arg UnlinkGuardianFromStudentParams) error {
	_, err := q.db.Exec(ctx, unlinkGuardianFromStudent, arg.StudentID, arg.GuardianID)
	return err
}

const updateGuardian = `-- name: UpdateGuardian :one
UPDATE guardians
SET
    full_name    = $2,
    relationship = $3,
    phone        = $4,
    email        = $5,
    nic_number   = $6
WHERE id = $1
RETURNING id, user_id, full_name, relationship, phone, email, created_at, nic_number
`

type UpdateGuardianParams struct {
	ID           uuid.UUID   `json:"id"`
	FullName     string      `json:"full_name"`
	Relationship string      `json:"relationship"`
	Phone        string      `json:"phone"`
	Email        pgtype.Text `json:"email"`
	NicNumber    string      `json:"nic_number"`
}

func (q *Queries) UpdateGuardian(ctx context.Context, arg UpdateGuardianParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, updateGuardian,
		arg.ID,
		arg.FullName,
		arg.Relationship,
		arg.Phone,
		arg.Email,
		arg.NicNumber,
	)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Relationship,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.NicNumber,
	)
	return i, err
}
