// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: houses.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHouse = `-- name: CreateHouse :one
INSERT INTO houses (name, code, remainder)
VALUES ($1, $2, $3)
RETURNING id, name, code, remainder, created_at
`

type CreateHouseParams struct {
	Name      string      `json:"name"`
	Code      pgtype.Text `json:"code"`
	Remainder int32       `json:"remainder"`
}

func (q *Queries) CreateHouse(ctx context.Context, arg CreateHouseParams) (House, error) {
	row := q.db.QueryRow(ctx, createHouse, arg.Name, arg.Code, arg.Remainder)
	var i House
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Remainder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHouse = `-- name: DeleteHouse :execrows
DELETE FROM houses AS h
WHERE h.id = $1
AND h.id NOT IN (
    SELECT DISTINCT house_id FROM student_profiles WHERE house_id IS NOT NULL
)
`

func (q *Queries) DeleteHouse(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHouse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHouseByID = `-- name: GetHouseByID :one
SELECT id, name, code, remainder, created_at FROM houses
WHERE id = $1
`

func (q *Queries) GetHouseByID(ctx context.Context, id uuid.UUID) (House, error) {
	row := q.db.QueryRow(ctx, getHouseByID, id)
	var i House
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Remainder,
		&i.CreatedAt,
	)
	return i, err
}

const listHouses = `-- name: ListHouses :many
SELECT id, name, code, remainder, created_at FROM houses
ORDER BY remainder ASC, name ASC
`

func (q *Queries) ListHouses(ctx context.Context) ([]House, error) {
	rows, err := q.db.Query(ctx, listHouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []House{}
	for rows.Next() {
		var i House
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Remainder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsMissingHouse = `-- name: ListStudentsMissingHouse :many
SELECT id, user_id, full_name, index_number, address, phone, whatsapp, special_remarks, created_at, updated_at, gender, house_id FROM student_profiles
WHERE house_id IS NULL
ORDER BY index_number ASC
`

func (q *Queries) ListStudentsMissingHouse(ctx context.Context) ([]StudentProfile, error) {
	rows, err := q.db.Query(ctx, listStudentsMissingHouse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentProfile{}
	for rows.Next() {
		var i StudentProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.IndexNumber,
			&i.Address,
			&i.Phone,
			&i.Whatsapp,
			&i.SpecialRemarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.HouseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHouse = `-- name: UpdateHouse :one
UPDATE houses
SET
    name      = $2,
    code      = $3,
    remainder = $4
WHERE id = $1
RETURNING id, name, code, remainder, created_at
`

type UpdateHouseParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Code      pgtype.Text `json:"code"`
	Remainder int32       `json:"remainder"`
}

func (q *Queries) UpdateHouse(ctx context.Context, arg UpdateHouseParams) (House, error) {
	row := q.db.QueryRow(ctx, updateHouse,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Remainder,
	)
	var i House
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Remainder,
		&i.CreatedAt,
	)
	return i, err
}

const updateStudentHouse = `-- name: UpdateStudentHouse :one
UPDATE student_profiles
SET
    house_id   = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, full_name, index_number, address, phone, whatsapp, special_remarks, created_at, updated_at, gender, house_id
`

type UpdateStudentHouseParams struct {
	ID      uuid.UUID   `json:"id"`
	HouseID pgtype.UUID `json:"house_id"`
}

func (q *Queries) UpdateStudentHouse(ctx context.Context, arg UpdateStudentHouseParams) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, updateStudentHouse, arg.ID, arg.HouseID)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.IndexNumber,
		&i.Address,
		&i.Phone,
		&i.Whatsapp,
		&i.SpecialRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.HouseID,
	)
	return i, err
}
