// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_checks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :execrows

DELETE FROM password_reset_tokens
WHERE used_at IS NULL AND expires_at < NOW()
`

// ── Password reset token sweep ───────────────────────────────────────────────
func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveStudentsWithoutCurrentClass = `-- name: ListActiveStudentsWithoutCurrentClass :many

SELECT sp.id, sp.full_name, sp.index_number
FROM student_profiles sp
INNER JOIN academic_years ay ON ay.is_current = TRUE
WHERE sp.enrollment_status = 'active'
AND NOT EXISTS (
    SELECT 1 FROM class_students cs
    INNER JOIN classes c ON c.id = cs.class_id
    WHERE cs.student_id = sp.id AND c.academic_year_id = ay.id
)
ORDER BY sp.full_name
`

type ListActiveStudentsWithoutCurrentClassRow struct {
	ID          uuid.UUID `json:"id"`
	FullName    string    `json:"full_name"`
	IndexNumber string    `json:"index_number"`
}

// ── Unclassed student watcher ────────────────────────────────────────────────
// an active student with no class_students row in the current academic
// year's classes — the kind of gap promotion or manual enrollment edits
// can silently leave behind.
func (q *Queries) ListActiveStudentsWithoutCurrentClass(ctx context.Context) ([]ListActiveStudentsWithoutCurrentClassRow, error) {
	rows, err := q.db.Query(ctx, listActiveStudentsWithoutCurrentClass)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveStudentsWithoutCurrentClassRow{}
	for rows.Next() {
		var i ListActiveStudentsWithoutCurrentClassRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.IndexNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveStudentsWithoutGuardian = `-- name: ListActiveStudentsWithoutGuardian :many

SELECT sp.id, sp.full_name, sp.index_number
FROM student_profiles sp
WHERE sp.enrollment_status = 'active'
AND NOT EXISTS (SELECT 1 FROM student_guardians sg WHERE sg.student_id = sp.id)
ORDER BY sp.full_name
`

type ListActiveStudentsWithoutGuardianRow struct {
	ID          uuid.UUID `json:"id"`
	FullName    string    `json:"full_name"`
	IndexNumber string    `json:"index_number"`
}

// ── Zero-guardian student watcher ───────────────────────────────────────────
func (q *Queries) ListActiveStudentsWithoutGuardian(ctx context.Context) ([]ListActiveStudentsWithoutGuardianRow, error) {
	rows, err := q.db.Query(ctx, listActiveStudentsWithoutGuardian)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveStudentsWithoutGuardianRow{}
	for rows.Next() {
		var i ListActiveStudentsWithoutGuardianRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.IndexNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUserIDs = `-- name: ListAdminUserIDs :many

SELECT id FROM users WHERE role = 'admin' ORDER BY created_at ASC
`

// Ad-hoc, read-mostly queries backing the background agents in
// internal/modules/automation (five consolidated algorithms, each running
// several checks concurrently in its own clearly named file). Grouped in
// one file since each is a one-off used by exactly one check, not a full
// entity's CRUD.
// used by the Automation module to resolve who gets notified, and to attribute
// system-triggered notifications' created_by (NOT NULL FK to users).
func (q *Queries) ListAdminUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAdminUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditActivityBaseline = `-- name: ListAuditActivityBaseline :many

SELECT
    hourly.actor_id,
    u.full_name,
    AVG(hourly.cnt)::float8 AS mean_per_hour,
    COALESCE(STDDEV_POP(hourly.cnt), 0)::float8 AS stddev_per_hour,
    COUNT(*) AS hours_observed
FROM (
    SELECT actor_id, date_trunc('hour', created_at) AS hour_bucket, COUNT(*) AS cnt
    FROM audit_logs
    WHERE actor_id IS NOT NULL
    AND created_at >= NOW() - make_interval(days => $1::int)
    AND created_at < date_trunc('hour', NOW())
    GROUP BY actor_id, date_trunc('hour', created_at)
) hourly
INNER JOIN users u ON u.id = hourly.actor_id
GROUP BY hourly.actor_id, u.full_name
`

type ListAuditActivityBaselineRow struct {
	ActorID       pgtype.UUID `json:"actor_id"`
	FullName      string      `json:"full_name"`
	MeanPerHour   float64     `json:"mean_per_hour"`
	StddevPerHour float64     `json:"stddev_per_hour"`
	HoursObserved int64       `json:"hours_observed"`
}

// ── Audit-log anomaly watcher ────────────────────────────────────────────────
// Replaces a single fixed threshold with a per-actor statistical baseline:
// SecurityAuditAgent computes each active actor's mean and standard
// deviation of per-hour change volume from ListAuditActivityBaseline, then
// flags the current hour (ListCurrentHourAuditActivity) as an outlier via a
// z-score against that actor's *own* normal pattern — an admin who
// routinely bulk-edits won't trip the same threshold as one who never
// touches more than a few records a day. An actor with too little history
// for a meaningful baseline falls back to a fixed absolute floor (computed
// in Go), never to "never flagged".
// Per-actor mean/stddev of hourly audit-log volume over the trailing
// baseline window, counting only hours in which the actor was active at
// all (an idle hour isn't "zero activity" in this average — it's excluded
// entirely), plus how many such hours were observed so the caller can
// decide whether the baseline has enough data to trust.
func (q *Queries) ListAuditActivityBaseline(ctx context.Context, baselineDays int32) ([]ListAuditActivityBaselineRow, error) {
	rows, err := q.db.Query(ctx, listAuditActivityBaseline, baselineDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditActivityBaselineRow{}
	for rows.Next() {
		var i ListAuditActivityBaselineRow
		if err := rows.Scan(
			&i.ActorID,
			&i.FullName,
			&i.MeanPerHour,
			&i.StddevPerHour,
			&i.HoursObserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassAttendanceComplianceRecent = `-- name: ListClassAttendanceComplianceRecent :many
SELECT
    c.id,
    c.name,
    g.name AS grade_name,
    COUNT(DISTINCT s.date) AS sessions_taken,
    (
        SELECT COUNT(*)
        FROM generate_series(
            CURRENT_DATE - make_interval(days => $1::int),
            CURRENT_DATE - 1,
            INTERVAL '1 day'
        ) AS d
        WHERE EXTRACT(ISODOW FROM d) < 6
    ) AS school_days_in_window
FROM classes c
INNER JOIN academic_years ay ON ay.id = c.academic_year_id AND ay.is_current = TRUE
INNER JOIN grades g ON g.id = c.grade_id
LEFT JOIN attendance_sessions s
    ON s.class_id = c.id
    AND s.date >= CURRENT_DATE - make_interval(days => $1::int)
    AND s.date < CURRENT_DATE
GROUP BY c.id, c.name, g.name
ORDER BY g.name, c.name
`

type ListClassAttendanceComplianceRecentRow struct {
	ID                 uuid.UUID `json:"id"`
	Name               string    `json:"name"`
	GradeName          string    `json:"grade_name"`
	SessionsTaken      int64     `json:"sessions_taken"`
	SchoolDaysInWindow int64     `json:"school_days_in_window"`
}

// For each current-year class: how many distinct days had an attendance
// session created in the trailing window versus how many weekdays fell in
// that window (the system has no holiday calendar, so weekday count is
// the best available "school days" proxy). AcademicDeliveryAgent turns
// this into a compliance rate and flags classes whose attendance-taking
// has been chronically inconsistent lately — a class that's usually fine
// but simply missed today (already covered by
// ListCurrentYearClassesMissingTodaySession) is not what this is for.
func (q *Queries) ListClassAttendanceComplianceRecent(ctx context.Context, windowDays int32) ([]ListClassAttendanceComplianceRecentRow, error) {
	rows, err := q.db.Query(ctx, listClassAttendanceComplianceRecent, windowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassAttendanceComplianceRecentRow{}
	for rows.Next() {
		var i ListClassAttendanceComplianceRecentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GradeName,
			&i.SessionsTaken,
			&i.SchoolDaysInWindow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentAcademicYears = `-- name: ListCurrentAcademicYears :many

SELECT id, label, start_date, end_date, is_current, created_at FROM academic_years WHERE is_current = TRUE ORDER BY start_date
`

// ── Current-academic-year invariant checker ─────────────────────────────────
// should always return exactly 1 row
// (docs/adr/0003-single-current-academic-year.md); 0 or 2+ means the
// app-level invariant has been violated. Listed (not just counted) so the
// finding can name which years are wrongly marked current.
func (q *Queries) ListCurrentAcademicYears(ctx context.Context) ([]AcademicYear, error) {
	rows, err := q.db.Query(ctx, listCurrentAcademicYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicYear{}
	for rows.Next() {
		var i AcademicYear
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentHourAuditActivity = `-- name: ListCurrentHourAuditActivity :many
SELECT al.actor_id, u.full_name, COUNT(*) AS change_count
FROM audit_logs al
INNER JOIN users u ON u.id = al.actor_id
WHERE al.actor_id IS NOT NULL
AND al.created_at >= date_trunc('hour', NOW())
GROUP BY al.actor_id, u.full_name
`

type ListCurrentHourAuditActivityRow struct {
	ActorID     pgtype.UUID `json:"actor_id"`
	FullName    string      `json:"full_name"`
	ChangeCount int64       `json:"change_count"`
}

// Every actor's change count so far in the current (partial) hour — the
// sample SecurityAuditAgent scores against each actor's baseline.
func (q *Queries) ListCurrentHourAuditActivity(ctx context.Context) ([]ListCurrentHourAuditActivityRow, error) {
	rows, err := q.db.Query(ctx, listCurrentHourAuditActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentHourAuditActivityRow{}
	for rows.Next() {
		var i ListCurrentHourAuditActivityRow
		if err := rows.Scan(&i.ActorID, &i.FullName, &i.ChangeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentYearClassesMissingTodaySession = `-- name: ListCurrentYearClassesMissingTodaySession :many

SELECT c.id, c.name, g.name AS grade_name
FROM classes c
INNER JOIN academic_years ay ON ay.id = c.academic_year_id AND ay.is_current = TRUE
INNER JOIN grades g ON g.id = c.grade_id
WHERE NOT EXISTS (
    SELECT 1 FROM attendance_sessions s WHERE s.class_id = c.id AND s.date = CURRENT_DATE
)
ORDER BY g.name, c.name
`

type ListCurrentYearClassesMissingTodaySessionRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	GradeName string    `json:"grade_name"`
}

// ── Missing attendance session watcher ───────────────────────────────────────
func (q *Queries) ListCurrentYearClassesMissingTodaySession(ctx context.Context) ([]ListCurrentYearClassesMissingTodaySessionRow, error) {
	rows, err := q.db.Query(ctx, listCurrentYearClassesMissingTodaySession)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentYearClassesMissingTodaySessionRow{}
	for rows.Next() {
		var i ListCurrentYearClassesMissingTodaySessionRow
		if err := rows.Scan(&i.ID, &i.Name, &i.GradeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenderSchoolTypeMismatches = `-- name: ListGenderSchoolTypeMismatches :many

SELECT sp.id, sp.full_name, sp.index_number
FROM student_profiles sp, school s
WHERE sp.enrollment_status = 'active'
AND (
    (s.school_type = 'boys'  AND sp.gender IS DISTINCT FROM 'male')
    OR (s.school_type = 'girls' AND sp.gender IS DISTINCT FROM 'female')
)
ORDER BY sp.full_name
`

type ListGenderSchoolTypeMismatchesRow struct {
	ID          uuid.UUID `json:"id"`
	FullName    string    `json:"full_name"`
	IndexNumber string    `json:"index_number"`
}

// ── Student gender / school-type watcher ────────────────────────────────────
// a single-sex school's own student roster drifting out of sync with
// school.school_type (Phase 11 item 1) — e.g. the type was flipped after
// students of the other gender were already enrolled.
func (q *Queries) ListGenderSchoolTypeMismatches(ctx context.Context) ([]ListGenderSchoolTypeMismatchesRow, error) {
	rows, err := q.db.Query(ctx, listGenderSchoolTypeMismatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenderSchoolTypeMismatchesRow{}
	for rows.Next() {
		var i ListGenderSchoolTypeMismatchesRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.IndexNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGradesWithNoCurrentClasses = `-- name: ListGradesWithNoCurrentClasses :many

SELECT g.id, g.name
FROM grades g
WHERE NOT EXISTS (
    SELECT 1 FROM classes c
    INNER JOIN academic_years ay ON ay.id = c.academic_year_id AND ay.is_current = TRUE
    WHERE c.grade_id = g.id
)
ORDER BY g.sort_order, g.name
`

type ListGradesWithNoCurrentClassesRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// ── Empty grade / stream watchers ────────────────────────────────────────────
// a grade defined in the curriculum with zero classes in the current
// academic year — either never set up, or every class under it was deleted
// without anyone noticing the grade itself was left dangling.
func (q *Queries) ListGradesWithNoCurrentClasses(ctx context.Context) ([]ListGradesWithNoCurrentClassesRow, error) {
	rows, err := q.db.Query(ctx, listGradesWithNoCurrentClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGradesWithNoCurrentClassesRow{}
	for rows.Next() {
		var i ListGradesWithNoCurrentClassesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInactiveTeachersStillAssigned = `-- name: ListInactiveTeachersStillAssigned :many

SELECT DISTINCT tp.id, tp.full_name, tp.employment_status
FROM teacher_profiles tp
INNER JOIN academic_years ay ON ay.is_current = TRUE
WHERE tp.employment_status != 'active'
AND (
    EXISTS (SELECT 1 FROM classes c WHERE c.form_teacher_id = tp.id AND c.academic_year_id = ay.id)
    OR EXISTS (
        SELECT 1 FROM class_subject_teachers cst
        INNER JOIN classes c ON c.id = cst.class_id
        WHERE cst.teacher_id = tp.id AND c.academic_year_id = ay.id
    )
)
ORDER BY tp.full_name
`

type ListInactiveTeachersStillAssignedRow struct {
	ID               uuid.UUID `json:"id"`
	FullName         string    `json:"full_name"`
	EmploymentStatus string    `json:"employment_status"`
}

// ── Employment-status consistency checker ───────────────────────────────────
// a resigned/transferred teacher still wired in as a form teacher or
// subject teacher on a current-year class — attendance/marks/notifications
// would still route to them.
func (q *Queries) ListInactiveTeachersStillAssigned(ctx context.Context) ([]ListInactiveTeachersStillAssignedRow, error) {
	rows, err := q.db.Query(ctx, listInactiveTeachersStillAssigned)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInactiveTeachersStillAssignedRow{}
	for rows.Next() {
		var i ListInactiveTeachersStillAssignedRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.EmploymentStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffHoursAuditActivity = `-- name: ListOffHoursAuditActivity :many
SELECT al.actor_id, u.full_name, COUNT(*) AS change_count,
       MIN(al.created_at)::timestamptz AS first_seen, MAX(al.created_at)::timestamptz AS last_seen
FROM audit_logs al
INNER JOIN users u ON u.id = al.actor_id
WHERE al.actor_id IS NOT NULL
AND al.created_at >= NOW() - INTERVAL '24 hours'
AND EXTRACT(HOUR FROM (al.created_at AT TIME ZONE 'Asia/Colombo')) BETWEEN 0 AND 4
GROUP BY al.actor_id, u.full_name
HAVING COUNT(*) >= $1::int
ORDER BY change_count DESC
`

type ListOffHoursAuditActivityRow struct {
	ActorID     pgtype.UUID        `json:"actor_id"`
	FullName    string             `json:"full_name"`
	ChangeCount int64              `json:"change_count"`
	FirstSeen   pgtype.Timestamptz `json:"first_seen"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
}

// Actors with audit-logged changes in the trailing 24 hours between
// midnight and 5am Sri Lanka time (Asia/Colombo, fixed UTC+5:30, no DST —
// converted explicitly so this is correct regardless of the database
// server's own configured timezone) — a low-cost complementary signal to
// the volume-based check above: a handful of overnight changes is unusual
// for a school system regardless of whether it clears any volume
// threshold. Sri-Lanka-specific per this system's single-deployment scope
// (docs/adr/0003-single-current-academic-year.md).
func (q *Queries) ListOffHoursAuditActivity(ctx context.Context, minChanges int32) ([]ListOffHoursAuditActivityRow, error) {
	rows, err := q.db.Query(ctx, listOffHoursAuditActivity, minChanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOffHoursAuditActivityRow{}
	for rows.Next() {
		var i ListOffHoursAuditActivityRow
		if err := rows.Scan(
			&i.ActorID,
			&i.FullName,
			&i.ChangeCount,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenTermMarksProgress = `-- name: ListOpenTermMarksProgress :many
SELECT
    t.id,
    t.name,
    t.start_date,
    t.end_date,
    ay.label AS academic_year_label,
    (
        SELECT COUNT(DISTINCT cs.student_id)
        FROM class_students cs
        INNER JOIN classes c ON c.id = cs.class_id
        WHERE c.academic_year_id = t.academic_year_id
    ) AS enrolled_students,
    (
        SELECT COUNT(DISTINCT tm.student_id)
        FROM term_marks tm
        WHERE tm.term_id = t.id
    ) AS students_with_marks
FROM terms t
INNER JOIN academic_years ay ON ay.id = t.academic_year_id AND ay.is_current = TRUE
WHERE t.end_date >= CURRENT_DATE
ORDER BY t.end_date
`

type ListOpenTermMarksProgressRow struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	StartDate         pgtype.Date `json:"start_date"`
	EndDate           pgtype.Date `json:"end_date"`
	AcademicYearLabel string      `json:"academic_year_label"`
	EnrolledStudents  int64       `json:"enrolled_students"`
	StudentsWithMarks int64       `json:"students_with_marks"`
}

// Every term of the current academic year that hasn't ended yet, with how
// many actively-enrolled students have at least one mark recorded for it
// against how many are enrolled in total, plus the term's date span. The
// caller (AcademicDeliveryAgent) turns this into a linear time-vs-coverage
// pace comparison — "you're 40% through the term but only 10% of students
// have any mark recorded" — catching a term that's quietly falling behind
// long before ListTermsNearDeadlineWithNoMarks's all-or-nothing zero-marks
// check would fire. Coverage is deliberately "at least one mark", not
// "every subject marked" — an exact per-subject expectation would need a
// students × subjects-taught cross join this system has no single source
// for (subject selection is per-student for A/L buckets) — so this is a
// breadth proxy, not a claim of exact completion percentage.
func (q *Queries) ListOpenTermMarksProgress(ctx context.Context) ([]ListOpenTermMarksProgressRow, error) {
	rows, err := q.db.Query(ctx, listOpenTermMarksProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenTermMarksProgressRow{}
	for rows.Next() {
		var i ListOpenTermMarksProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.AcademicYearLabel,
			&i.EnrolledStudents,
			&i.StudentsWithMarks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleIncompleteSessions = `-- name: ListStaleIncompleteSessions :many

SELECT
    s.id,
    s.class_id,
    c.name AS class_name,
    s.date,
    s.created_at,
    (SELECT COUNT(*) FROM attendance_records r WHERE r.session_id = s.id) AS record_count,
    (SELECT COUNT(*) FROM class_students cs WHERE cs.class_id = s.class_id) AS roster_size
FROM attendance_sessions s
INNER JOIN classes c ON c.id = s.class_id
WHERE s.created_at < NOW() - make_interval(hours => $1::int)
AND (SELECT COUNT(*) FROM attendance_records r WHERE r.session_id = s.id)
    < (SELECT COUNT(*) FROM class_students cs WHERE cs.class_id = s.class_id)
ORDER BY s.created_at
`

type ListStaleIncompleteSessionsRow struct {
	ID          uuid.UUID          `json:"id"`
	ClassID     uuid.UUID          `json:"class_id"`
	ClassName   string             `json:"class_name"`
	Date        pgtype.Date        `json:"date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RecordCount int64              `json:"record_count"`
	RosterSize  int64              `json:"roster_size"`
}

// ── Stale/incomplete attendance session watcher ─────────────────────────────
// a session created more than the given interval ago with fewer attendance
// records than the class's roster size — a teacher started it and never
// finished marking, indistinguishable from "not started" without this.
func (q *Queries) ListStaleIncompleteSessions(ctx context.Context, olderThanHours int32) ([]ListStaleIncompleteSessionsRow, error) {
	rows, err := q.db.Query(ctx, listStaleIncompleteSessions, olderThanHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleIncompleteSessionsRow{}
	for rows.Next() {
		var i ListStaleIncompleteSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.ClassName,
			&i.Date,
			&i.CreatedAt,
			&i.RecordCount,
			&i.RosterSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleMustChangePasswordUsersByRole = `-- name: ListStaleMustChangePasswordUsersByRole :many

SELECT id, full_name, email, role, created_at
FROM users
WHERE (
    must_change_password = TRUE
    OR (kept_default_password = TRUE AND created_at < NOW() - INTERVAL '7 days')
)
AND role = $1
AND created_at < NOW() - make_interval(days => $2::int)
ORDER BY created_at
`

type ListStaleMustChangePasswordUsersByRoleParams struct {
	Role          string `json:"role"`
	OlderThanDays int32  `json:"older_than_days"`
}

type ListStaleMustChangePasswordUsersByRoleRow struct {
	ID        uuid.UUID          `json:"id"`
	FullName  string             `json:"full_name"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ── Onboarding watchers (role-scoped) ────────────────────────────────────────
// provisioned but never completed first login, past the given age, scoped
// to one role — so the finding can be shown correctly on a role-specific
// page (Teachers vs Students) instead of a mixed list. Also catches an
// account that clicked "keep this password" and is still on the default
// past its expiry window (S1) — kept_default_password alone doesn't force
// must_change_password back to TRUE in the database, only in the /me
// response, so this check has to test both.
func (q *Queries) ListStaleMustChangePasswordUsersByRole(ctx context.Context, arg ListStaleMustChangePasswordUsersByRoleParams) ([]ListStaleMustChangePasswordUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, listStaleMustChangePasswordUsersByRole, arg.Role, arg.OlderThanDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleMustChangePasswordUsersByRoleRow{}
	for rows.Next() {
		var i ListStaleMustChangePasswordUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamsWithNoCurrentClasses = `-- name: ListStreamsWithNoCurrentClasses :many
SELECT s.id, s.name
FROM streams s
WHERE NOT EXISTS (
    SELECT 1 FROM classes c
    INNER JOIN academic_years ay ON ay.id = c.academic_year_id AND ay.is_current = TRUE
    WHERE c.stream_id = s.id
)
ORDER BY s.name
`

type ListStreamsWithNoCurrentClassesRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// same gap, for A/L streams — defined but no Grade 12/13 class uses it this year.
func (q *Queries) ListStreamsWithNoCurrentClasses(ctx context.Context) ([]ListStreamsWithNoCurrentClassesRow, error) {
	rows, err := q.db.Query(ctx, listStreamsWithNoCurrentClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStreamsWithNoCurrentClassesRow{}
	for rows.Next() {
		var i ListStreamsWithNoCurrentClassesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTermsNearDeadlineWithNoMarks = `-- name: ListTermsNearDeadlineWithNoMarks :many

SELECT t.id, t.name, t.end_date, ay.label AS academic_year_label
FROM terms t
INNER JOIN academic_years ay ON ay.id = t.academic_year_id
WHERE t.end_date >= CURRENT_DATE
AND t.end_date <= CURRENT_DATE + make_interval(days => $1::int)
AND NOT EXISTS (SELECT 1 FROM term_marks tm WHERE tm.term_id = t.id)
ORDER BY t.end_date
`

type ListTermsNearDeadlineWithNoMarksRow struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	EndDate           pgtype.Date `json:"end_date"`
	AcademicYearLabel string      `json:"academic_year_label"`
}

// ── Term-marks deadline watcher ──────────────────────────────────────────────
// terms ending within the given number of days (and not already past) with
// zero term_marks rows entered anywhere — nobody has started marks entry
// for a term that's about to lock.
func (q *Queries) ListTermsNearDeadlineWithNoMarks(ctx context.Context, withinDays int32) ([]ListTermsNearDeadlineWithNoMarksRow, error) {
	rows, err := q.db.Query(ctx, listTermsNearDeadlineWithNoMarks, withinDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTermsNearDeadlineWithNoMarksRow{}
	for rows.Next() {
		var i ListTermsNearDeadlineWithNoMarksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EndDate,
			&i.AcademicYearLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
