// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leadership.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const leadershipOverviewCounts = `-- name: LeadershipOverviewCounts :one

WITH scoped_classes AS (
    SELECT c.id
    FROM classes c
    WHERE c.academic_year_id = (SELECT id FROM academic_years WHERE is_current = TRUE LIMIT 1)
      AND ($1::uuid[] IS NULL OR c.grade_id = ANY($1::uuid[]))
)
SELECT
    (SELECT COUNT(*) FROM scoped_classes) AS class_count,
    (SELECT COUNT(*) FROM class_students cs WHERE cs.class_id IN (SELECT id FROM scoped_classes)) AS student_count,
    (SELECT COUNT(DISTINCT ats.class_id) FROM attendance_sessions ats
        WHERE ats.class_id IN (SELECT id FROM scoped_classes) AND ats.date = CURRENT_DATE) AS sessions_marked_today
`

type LeadershipOverviewCountsRow struct {
	ClassCount          int64 `json:"class_count"`
	StudentCount        int64 `json:"student_count"`
	SessionsMarkedToday int64 `json:"sessions_marked_today"`
}

// Phase 9.3 — the deepened role-differentiated dashboard's "School/Grades
// Overview" panel for Principal/Vice Principal/Section Head. Both queries
// filter by grade at the SQL WHERE clause level (never fetched-then-
// filtered in application code) so a grade-scoped caller can never receive
// counts for a grade outside their scope — the same class of bug §0.1
// flagged for the cross-school attendance dashboard.
// grade_ids narrows to specific grades; NULL means whole school.
func (q *Queries) LeadershipOverviewCounts(ctx context.Context, gradeIds []uuid.UUID) (LeadershipOverviewCountsRow, error) {
	row := q.db.QueryRow(ctx, leadershipOverviewCounts, gradeIds)
	var i LeadershipOverviewCountsRow
	err := row.Scan(&i.ClassCount, &i.StudentCount, &i.SessionsMarkedToday)
	return i, err
}

const leadershipOverviewGradeNames = `-- name: LeadershipOverviewGradeNames :many
SELECT DISTINCT g.name
FROM grades g
WHERE g.id = ANY($1::uuid[])
ORDER BY g.name ASC
`

// Human-readable grade names for a grade-scoped caller's panel heading.
func (q *Queries) LeadershipOverviewGradeNames(ctx context.Context, dollar_1 []uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, leadershipOverviewGradeNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
