// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicYear struct {
	ID        uuid.UUID          `json:"id"`
	Label     string             `json:"label"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	IsCurrent bool               `json:"is_current"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AttendanceRecord struct {
	ID        uuid.UUID   `json:"id"`
	SessionID uuid.UUID   `json:"session_id"`
	StudentID uuid.UUID   `json:"student_id"`
	Status    string      `json:"status"`
	Note      pgtype.Text `json:"note"`
}

type AttendanceSession struct {
	ID        uuid.UUID          `json:"id"`
	ClassID   uuid.UUID          `json:"class_id"`
	TakenBy   uuid.UUID          `json:"taken_by"`
	Date      pgtype.Date        `json:"date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Class struct {
	ID             uuid.UUID          `json:"id"`
	GradeID        uuid.UUID          `json:"grade_id"`
	AcademicYearID uuid.UUID          `json:"academic_year_id"`
	FormTeacherID  pgtype.UUID        `json:"form_teacher_id"`
	StreamID       pgtype.UUID        `json:"stream_id"`
	StreamGroupID  pgtype.UUID        `json:"stream_group_id"`
	Name           string             `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ClassStudent struct {
	ClassID    uuid.UUID          `json:"class_id"`
	StudentID  uuid.UUID          `json:"student_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

type ClassSubjectTeacher struct {
	ClassID   uuid.UUID `json:"class_id"`
	SubjectID uuid.UUID `json:"subject_id"`
	TeacherID uuid.UUID `json:"teacher_id"`
}

type Grade struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GradeSubject struct {
	GradeID   uuid.UUID `json:"grade_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type Guardian struct {
	ID           uuid.UUID          `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	FullName     string             `json:"full_name"`
	Relationship string             `json:"relationship"`
	Phone        string             `json:"phone"`
	Email        pgtype.Text        `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type School struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	Phone     pgtype.Text        `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Stream struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StreamGroup struct {
	ID        uuid.UUID          `json:"id"`
	StreamID  uuid.UUID          `json:"stream_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StudentGuardian struct {
	StudentID        uuid.UUID `json:"student_id"`
	GuardianID       uuid.UUID `json:"guardian_id"`
	IsPrimaryContact bool      `json:"is_primary_contact"`
}

type StudentProfile struct {
	ID             uuid.UUID          `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	FullName       string             `json:"full_name"`
	IndexNumber    string             `json:"index_number"`
	Address        pgtype.Text        `json:"address"`
	Phone          pgtype.Text        `json:"phone"`
	Whatsapp       pgtype.Text        `json:"whatsapp"`
	SpecialRemarks pgtype.Text        `json:"special_remarks"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type StudentSibling struct {
	StudentID1 uuid.UUID `json:"student_id_1"`
	StudentID2 uuid.UUID `json:"student_id_2"`
}

type StudentSubjectSelection struct {
	StudentID uuid.UUID `json:"student_id"`
	BucketID  uuid.UUID `json:"bucket_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type Subject struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SubjectBucket struct {
	ID        uuid.UUID          `json:"id"`
	GradeID   uuid.UUID          `json:"grade_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SubjectBucketOption struct {
	BucketID  uuid.UUID `json:"bucket_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type TeacherProfile struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	FullName       string             `json:"full_name"`
	EmployeeNumber string             `json:"employee_number"`
	JoinedDate     pgtype.Date        `json:"joined_date"`
	Phone          pgtype.Text        `json:"phone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TeacherSubject struct {
	TeacherID uuid.UUID `json:"teacher_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
