// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_recipients.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMyNotificationBoxes = `-- name: CountMyNotificationBoxes :one
SELECT
    COUNT(*) FILTER (WHERE NOT is_archived AND NOT is_read)::int AS unread,
    COUNT(*) FILTER (WHERE NOT is_archived AND is_read)::int     AS read,
    COUNT(*) FILTER (WHERE is_archived)::int                     AS archived
FROM notification_recipients
WHERE user_id = $1
`

type CountMyNotificationBoxesRow struct {
	Unread   int32 `json:"unread"`
	Read     int32 `json:"read"`
	Archived int32 `json:"archived"`
}

func (q *Queries) CountMyNotificationBoxes(ctx context.Context, userID uuid.UUID) (CountMyNotificationBoxesRow, error) {
	row := q.db.QueryRow(ctx, countMyNotificationBoxes, userID)
	var i CountMyNotificationBoxesRow
	err := row.Scan(&i.Unread, &i.Read, &i.Archived)
	return i, err
}

const countMyUnreadNotifications = `-- name: CountMyUnreadNotifications :one
SELECT COUNT(*) FROM notification_recipients
WHERE user_id = $1 AND is_read = FALSE AND is_archived = FALSE
`

func (q *Queries) CountMyUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMyUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationRecipient = `-- name: CreateNotificationRecipient :exec
INSERT INTO notification_recipients (notification_id, user_id)
VALUES ($1, $2)
ON CONFLICT (notification_id, user_id) DO NOTHING
`

type CreateNotificationRecipientParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateNotificationRecipient(ctx context.Context, arg CreateNotificationRecipientParams) error {
	_, err := q.db.Exec(ctx, createNotificationRecipient, arg.NotificationID, arg.UserID)
	return err
}

const listMyArchivedNotifications = `-- name: ListMyArchivedNotifications :many
SELECT
    nr.id AS recipient_id,
    nr.is_read,
    nr.read_at,
    nr.is_archived,
    n.id AS notification_id,
    n.title,
    n.message,
    n.category,
    n.priority,
    n.sent_at,
    u.full_name AS sender_name
FROM notification_recipients nr
INNER JOIN notifications n ON n.id = nr.notification_id
INNER JOIN users u          ON u.id = n.created_by
WHERE nr.user_id = $1 AND nr.is_archived = TRUE
ORDER BY n.sent_at DESC
LIMIT 200
`

type ListMyArchivedNotificationsRow struct {
	RecipientID    uuid.UUID          `json:"recipient_id"`
	IsRead         bool               `json:"is_read"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	IsArchived     bool               `json:"is_archived"`
	NotificationID uuid.UUID          `json:"notification_id"`
	Title          string             `json:"title"`
	Message        string             `json:"message"`
	Category       string             `json:"category"`
	Priority       string             `json:"priority"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	SenderName     string             `json:"sender_name"`
}

func (q *Queries) ListMyArchivedNotifications(ctx context.Context, userID uuid.UUID) ([]ListMyArchivedNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listMyArchivedNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyArchivedNotificationsRow{}
	for rows.Next() {
		var i ListMyArchivedNotificationsRow
		if err := rows.Scan(
			&i.RecipientID,
			&i.IsRead,
			&i.ReadAt,
			&i.IsArchived,
			&i.NotificationID,
			&i.Title,
			&i.Message,
			&i.Category,
			&i.Priority,
			&i.SentAt,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyNotifications = `-- name: ListMyNotifications :many
SELECT
    nr.id AS recipient_id,
    nr.is_read,
    nr.read_at,
    nr.is_archived,
    n.id AS notification_id,
    n.title,
    n.message,
    n.category,
    n.priority,
    n.sent_at,
    u.full_name AS sender_name
FROM notification_recipients nr
INNER JOIN notifications n ON n.id = nr.notification_id
INNER JOIN users u          ON u.id = n.created_by
WHERE nr.user_id = $1 AND nr.is_archived = FALSE
ORDER BY n.sent_at DESC
LIMIT 200
`

type ListMyNotificationsRow struct {
	RecipientID    uuid.UUID          `json:"recipient_id"`
	IsRead         bool               `json:"is_read"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	IsArchived     bool               `json:"is_archived"`
	NotificationID uuid.UUID          `json:"notification_id"`
	Title          string             `json:"title"`
	Message        string             `json:"message"`
	Category       string             `json:"category"`
	Priority       string             `json:"priority"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	SenderName     string             `json:"sender_name"`
}

// everything not archived, most recent first; category/date/search
// filtering happens client-side, matching this app's existing convention
// for list pages (see e.g. Subjects, Streams)
func (q *Queries) ListMyNotifications(ctx context.Context, userID uuid.UUID) ([]ListMyNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listMyNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyNotificationsRow{}
	for rows.Next() {
		var i ListMyNotificationsRow
		if err := rows.Scan(
			&i.RecipientID,
			&i.IsRead,
			&i.ReadAt,
			&i.IsArchived,
			&i.NotificationID,
			&i.Title,
			&i.Message,
			&i.Category,
			&i.Priority,
			&i.SentAt,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationRecipientsRead = `-- name: MarkAllNotificationRecipientsRead :exec
UPDATE notification_recipients
SET is_read = TRUE, read_at = NOW()
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationRecipientsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationRecipientsRead, userID)
	return err
}

const markNotificationRecipientRead = `-- name: MarkNotificationRecipientRead :exec
UPDATE notification_recipients
SET is_read = TRUE, read_at = NOW()
WHERE notification_id = $1 AND user_id = $2
`

type MarkNotificationRecipientReadParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRecipientRead(ctx context.Context, arg MarkNotificationRecipientReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRecipientRead, arg.NotificationID, arg.UserID)
	return err
}

const searchMyNotifications = `-- name: SearchMyNotifications :many
SELECT
    nr.id AS recipient_id,
    nr.is_read,
    nr.is_archived,
    n.id AS notification_id,
    n.title,
    n.message,
    n.category,
    n.priority,
    n.sent_at,
    u.full_name AS sender_name,
    COUNT(*) OVER () AS total
FROM notification_recipients nr
INNER JOIN notifications n ON n.id = nr.notification_id
INNER JOIN users u          ON u.id = n.created_by
WHERE nr.user_id = $1::uuid
  AND CASE $2::text
        WHEN 'unread'   THEN NOT nr.is_archived AND NOT nr.is_read
        WHEN 'read'     THEN NOT nr.is_archived AND nr.is_read
        ELSE nr.is_archived
      END
  AND ($3::text IS NULL
       OR n.title ILIKE '%' || $3::text || '%'
       OR n.message ILIKE '%' || $3::text || '%')
  AND ($4::text IS NULL OR n.category = $4::text)
ORDER BY n.sent_at DESC, nr.id DESC
LIMIT $6::int OFFSET $5::int
`

type SearchMyNotificationsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Box        string      `json:"box"`
	Search     pgtype.Text `json:"search"`
	Category   pgtype.Text `json:"category"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type SearchMyNotificationsRow struct {
	RecipientID    uuid.UUID          `json:"recipient_id"`
	IsRead         bool               `json:"is_read"`
	IsArchived     bool               `json:"is_archived"`
	NotificationID uuid.UUID          `json:"notification_id"`
	Title          string             `json:"title"`
	Message        string             `json:"message"`
	Category       string             `json:"category"`
	Priority       string             `json:"priority"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	SenderName     string             `json:"sender_name"`
	Total          int64              `json:"total"`
}

// One page of the caller's inbox. box is 'unread', 'read' or 'archived'. Search is escaped by the caller.
func (q *Queries) SearchMyNotifications(ctx context.Context, arg SearchMyNotificationsParams) ([]SearchMyNotificationsRow, error) {
	rows, err := q.db.Query(ctx, searchMyNotifications,
		arg.UserID,
		arg.Box,
		arg.Search,
		arg.Category,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMyNotificationsRow{}
	for rows.Next() {
		var i SearchMyNotificationsRow
		if err := rows.Scan(
			&i.RecipientID,
			&i.IsRead,
			&i.IsArchived,
			&i.NotificationID,
			&i.Title,
			&i.Message,
			&i.Category,
			&i.Priority,
			&i.SentAt,
			&i.SenderName,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNotificationRecipientArchived = `-- name: SetNotificationRecipientArchived :exec
UPDATE notification_recipients
SET is_archived = $3
WHERE notification_id = $1 AND user_id = $2
`

type SetNotificationRecipientArchivedParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	UserID         uuid.UUID `json:"user_id"`
	IsArchived     bool      `json:"is_archived"`
}

func (q *Queries) SetNotificationRecipientArchived(ctx context.Context, arg SetNotificationRecipientArchivedParams) error {
	_, err := q.db.Exec(ctx, setNotificationRecipientArchived, arg.NotificationID, arg.UserID, arg.IsArchived)
	return err
}
