// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_recipient_resolution.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listAllUserIDs = `-- name: ListAllUserIDs :many

SELECT id FROM users
`

// Recipient-resolution queries for the notification composer. Each rule
// type in a notification's recipient_rules resolves through one or more
// of these into a set of users.id, unioned together in Go (see
// services/notifications).
func (q *Queries) ListAllUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAllUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassIDsByGrade = `-- name: ListClassIDsByGrade :many
SELECT id FROM classes
WHERE grade_id = $1 AND academic_year_id = $2
`

type ListClassIDsByGradeParams struct {
	GradeID        uuid.UUID `json:"grade_id"`
	AcademicYearID uuid.UUID `json:"academic_year_id"`
}

func (q *Queries) ListClassIDsByGrade(ctx context.Context, arg ListClassIDsByGradeParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listClassIDsByGrade, arg.GradeID, arg.AcademicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardianUserIDsByClass = `-- name: ListGuardianUserIDsByClass :many
SELECT DISTINCT g.user_id FROM guardians g
INNER JOIN student_guardians sg ON sg.guardian_id = g.id
INNER JOIN class_students cs    ON cs.student_id = sg.student_id
WHERE cs.class_id = $1
`

func (q *Queries) ListGuardianUserIDsByClass(ctx context.Context, classID uuid.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listGuardianUserIDsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentIDsByGuardian = `-- name: ListStudentIDsByGuardian :many
SELECT sg.student_id FROM student_guardians sg
WHERE sg.guardian_id = $1
`

// used to authorize a teacher-sent "guardian" rule: allowed only if at
// least one of the guardian's linked students is in one of the teacher's
// assigned classes
func (q *Queries) ListStudentIDsByGuardian(ctx context.Context, guardianID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStudentIDsByGuardian, guardianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var student_id uuid.UUID
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentUserIDsByClass = `-- name: ListStudentUserIDsByClass :many
SELECT sp.user_id FROM student_profiles sp
INNER JOIN class_students cs ON cs.student_id = sp.id
WHERE cs.class_id = $1
`

func (q *Queries) ListStudentUserIDsByClass(ctx context.Context, classID uuid.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listStudentUserIDsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentUserIDsBySubject = `-- name: ListStudentUserIDsBySubject :many
SELECT DISTINCT sp.user_id
FROM student_profiles sp
WHERE sp.id IN (
    SELECT sse.student_id FROM student_subject_enrollments sse
    WHERE sse.subject_id = $1 AND sse.academic_year_id = $2
    UNION
    SELECT cs.student_id
    FROM class_subject_teachers cst
    INNER JOIN class_students cs ON cs.class_id = cst.class_id
    INNER JOIN classes c         ON c.id = cst.class_id
    WHERE cst.subject_id = $1 AND c.academic_year_id = $2
)
`

type ListStudentUserIDsBySubjectParams struct {
	SubjectID      uuid.UUID `json:"subject_id"`
	AcademicYearID uuid.UUID `json:"academic_year_id"`
}

// students enrolled in the subject as a curriculum elective, plus students
// in any class where the subject is compulsorily taught
func (q *Queries) ListStudentUserIDsBySubject(ctx context.Context, arg ListStudentUserIDsBySubjectParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listStudentUserIDsBySubject, arg.SubjectID, arg.AcademicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherUserIDsByClass = `-- name: ListTeacherUserIDsByClass :many
SELECT tp.user_id FROM teacher_profiles tp
WHERE tp.id IN (
    SELECT c.form_teacher_id FROM classes c WHERE c.id = $1 AND c.form_teacher_id IS NOT NULL
    UNION
    SELECT cst.teacher_id FROM class_subject_teachers cst WHERE cst.class_id = $1
)
`

// the form teacher, plus every subject teacher assigned to this class
func (q *Queries) ListTeacherUserIDsByClass(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTeacherUserIDsByClass, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherUserIDsBySubject = `-- name: ListTeacherUserIDsBySubject :many
SELECT tp.user_id FROM teacher_profiles tp
INNER JOIN teacher_subjects ts ON ts.teacher_id = tp.id
WHERE ts.subject_id = $1
`

func (q *Queries) ListTeacherUserIDsBySubject(ctx context.Context, subjectID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTeacherUserIDsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
