// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (title, message, category, priority, status, recipient_rules, created_by, sent_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, message, category, priority, status, recipient_rules, created_by, sent_at, created_at, updated_at
`

type CreateNotificationParams struct {
	Title          string             `json:"title"`
	Message        string             `json:"message"`
	Category       string             `json:"category"`
	Priority       string             `json:"priority"`
	Status         string             `json:"status"`
	RecipientRules []byte             `json:"recipient_rules"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.Title,
		arg.Message,
		arg.Category,
		arg.Priority,
		arg.Status,
		arg.RecipientRules,
		arg.CreatedBy,
		arg.SentAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.RecipientRules,
		&i.CreatedBy,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraftNotification = `-- name: DeleteDraftNotification :execrows
DELETE FROM notifications
WHERE id = $1 AND status = 'draft'
`

func (q *Queries) DeleteDraftNotification(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftNotification, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, title, message, category, priority, status, recipient_rules, created_by, sent_at, created_at, updated_at FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.RecipientRules,
		&i.CreatedBy,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationRecipientStats = `-- name: GetNotificationRecipientStats :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE is_read)::int AS read_count
FROM notification_recipients
WHERE notification_id = $1
`

type GetNotificationRecipientStatsRow struct {
	Total     int32 `json:"total"`
	ReadCount int32 `json:"read_count"`
}

func (q *Queries) GetNotificationRecipientStats(ctx context.Context, notificationID uuid.UUID) (GetNotificationRecipientStatsRow, error) {
	row := q.db.QueryRow(ctx, getNotificationRecipientStats, notificationID)
	var i GetNotificationRecipientStatsRow
	err := row.Scan(&i.Total, &i.ReadCount)
	return i, err
}

const listAllSentNotifications = `-- name: ListAllSentNotifications :many
SELECT
    n.id, n.title, n.message, n.category, n.priority, n.status, n.recipient_rules, n.created_by, n.sent_at, n.created_at, n.updated_at,
    u.full_name AS sender_name
FROM notifications n
INNER JOIN users u ON u.id = n.created_by
WHERE n.status = 'sent'
ORDER BY n.sent_at DESC
LIMIT 100
`

type ListAllSentNotificationsRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Message        string             `json:"message"`
	Category       string             `json:"category"`
	Priority       string             `json:"priority"`
	Status         string             `json:"status"`
	RecipientRules []byte             `json:"recipient_rules"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SenderName     string             `json:"sender_name"`
}

func (q *Queries) ListAllSentNotifications(ctx context.Context) ([]ListAllSentNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listAllSentNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSentNotificationsRow{}
	for rows.Next() {
		var i ListAllSentNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.Category,
			&i.Priority,
			&i.Status,
			&i.RecipientRules,
			&i.CreatedBy,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyDraftNotifications = `-- name: ListMyDraftNotifications :many
SELECT id, title, message, category, priority, status, recipient_rules, created_by, sent_at, created_at, updated_at FROM notifications
WHERE status = 'draft' AND created_by = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListMyDraftNotifications(ctx context.Context, createdBy uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listMyDraftNotifications, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.Category,
			&i.Priority,
			&i.Status,
			&i.RecipientRules,
			&i.CreatedBy,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentNotificationsByUser = `-- name: ListSentNotificationsByUser :many
SELECT
    n.id, n.title, n.message, n.category, n.priority, n.status, n.recipient_rules, n.created_by, n.sent_at, n.created_at, n.updated_at,
    u.full_name AS sender_name
FROM notifications n
INNER JOIN users u ON u.id = n.created_by
WHERE n.status = 'sent' AND n.created_by = $1
ORDER BY n.sent_at DESC
LIMIT 100
`

type ListSentNotificationsByUserRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Message        string             `json:"message"`
	Category       string             `json:"category"`
	Priority       string             `json:"priority"`
	Status         string             `json:"status"`
	RecipientRules []byte             `json:"recipient_rules"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SenderName     string             `json:"sender_name"`
}

func (q *Queries) ListSentNotificationsByUser(ctx context.Context, createdBy uuid.UUID) ([]ListSentNotificationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSentNotificationsByUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSentNotificationsByUserRow{}
	for rows.Next() {
		var i ListSentNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.Category,
			&i.Priority,
			&i.Status,
			&i.RecipientRules,
			&i.CreatedBy,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationSent = `-- name: MarkNotificationSent :one
UPDATE notifications
SET status = 'sent', sent_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'draft'
RETURNING id, title, message, category, priority, status, recipient_rules, created_by, sent_at, created_at, updated_at
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationSent, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.RecipientRules,
		&i.CreatedBy,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationDraft = `-- name: UpdateNotificationDraft :one
UPDATE notifications
SET title = $2, message = $3, category = $4, priority = $5, recipient_rules = $6, updated_at = NOW()
WHERE id = $1 AND status = 'draft'
RETURNING id, title, message, category, priority, status, recipient_rules, created_by, sent_at, created_at, updated_at
`

type UpdateNotificationDraftParams struct {
	ID             uuid.UUID `json:"id"`
	Title          string    `json:"title"`
	Message        string    `json:"message"`
	Category       string    `json:"category"`
	Priority       string    `json:"priority"`
	RecipientRules []byte    `json:"recipient_rules"`
}

func (q *Queries) UpdateNotificationDraft(ctx context.Context, arg UpdateNotificationDraftParams) (Notification, error) {
	row := q.db.QueryRow(ctx, updateNotificationDraft,
		arg.ID,
		arg.Title,
		arg.Message,
		arg.Category,
		arg.Priority,
		arg.RecipientRules,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.RecipientRules,
		&i.CreatedBy,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
