// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotion.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkDeleteClassStudentsForYear = `-- name: BulkDeleteClassStudentsForYear :exec
DELETE FROM class_students
WHERE academic_year_id = $1 AND student_id = ANY($2::uuid[])
`

type BulkDeleteClassStudentsForYearParams struct {
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	StudentIds     []uuid.UUID `json:"student_ids"`
}

// clears any existing enrollment (in any class) for these students in this
// academic year, so BulkInsertClassStudents can freely (re)assign them —
// safe to re-run, since promotion is a preview-then-commit workflow.
func (q *Queries) BulkDeleteClassStudentsForYear(ctx context.Context, arg BulkDeleteClassStudentsForYearParams) error {
	_, err := q.db.Exec(ctx, bulkDeleteClassStudentsForYear, arg.AcademicYearID, arg.StudentIds)
	return err
}

const bulkInsertClassStudents = `-- name: BulkInsertClassStudents :exec
INSERT INTO class_students (class_id, student_id)
SELECT c.class_id, s.student_id
FROM UNNEST($1::uuid[])   WITH ORDINALITY AS c(class_id, ord)
INNER JOIN UNNEST($2::uuid[]) WITH ORDINALITY AS s(student_id, ord) ON c.ord = s.ord
`

type BulkInsertClassStudentsParams struct {
	ClassIds   []uuid.UUID `json:"class_ids"`
	StudentIds []uuid.UUID `json:"student_ids"`
}

// the first batched UNNEST-based bulk write in the codebase — one
// round-trip for the whole assignment set instead of a per-student loop.
// Paired via WITH ORDINALITY rather than the two-array UNNEST(a, b) form,
// since sqlc's static analyzer doesn't resolve that overload.
func (q *Queries) BulkInsertClassStudents(ctx context.Context, arg BulkInsertClassStudentsParams) error {
	_, err := q.db.Exec(ctx, bulkInsertClassStudents, arg.ClassIds, arg.StudentIds)
	return err
}

const countClassesInYearByIDs = `-- name: CountClassesInYearByIDs :one
SELECT COUNT(*) FROM classes
WHERE academic_year_id = $1 AND id = ANY($2::uuid[])
`

type CountClassesInYearByIDsParams struct {
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	ClassIds       []uuid.UUID `json:"class_ids"`
}

// validates that every target class ID a commit request references
// actually belongs to the target academic year, before writing anything.
func (q *Queries) CountClassesInYearByIDs(ctx context.Context, arg CountClassesInYearByIDsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClassesInYearByIDs, arg.AcademicYearID, arg.ClassIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findClassByGradeAndMedium = `-- name: FindClassByGradeAndMedium :one
SELECT id, grade_id, academic_year_id, form_teacher_id, stream_id, stream_group_id, name, created_at, girl_monitor_id, boy_monitor_id, medium_id, home_classroom_id FROM classes
WHERE grade_id = $1 AND academic_year_id = $2 AND medium_id = $3
ORDER BY name ASC
LIMIT 1
`

type FindClassByGradeAndMediumParams struct {
	GradeID        uuid.UUID   `json:"grade_id"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	MediumID       pgtype.UUID `json:"medium_id"`
}

// same-medium carryover for a medium-locked class: a student in the English
// section of grade 6 should land in the English section of grade 7 regardless
// of what the sections are named. Ordered by name so a grade with more than
// one section in the same medium resolves deterministically to the first.
func (q *Queries) FindClassByGradeAndMedium(ctx context.Context, arg FindClassByGradeAndMediumParams) (Class, error) {
	row := q.db.QueryRow(ctx, findClassByGradeAndMedium, arg.GradeID, arg.AcademicYearID, arg.MediumID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.GradeID,
		&i.AcademicYearID,
		&i.FormTeacherID,
		&i.StreamID,
		&i.StreamGroupID,
		&i.Name,
		&i.CreatedAt,
		&i.GirlMonitorID,
		&i.BoyMonitorID,
		&i.MediumID,
		&i.HomeClassroomID,
	)
	return i, err
}

const findClassByGradeAndName = `-- name: FindClassByGradeAndName :one
SELECT id, grade_id, academic_year_id, form_teacher_id, stream_id, stream_group_id, name, created_at, girl_monitor_id, boy_monitor_id, medium_id, home_classroom_id FROM classes
WHERE grade_id = $1 AND academic_year_id = $2 AND name = $3
`

type FindClassByGradeAndNameParams struct {
	GradeID        uuid.UUID `json:"grade_id"`
	AcademicYearID uuid.UUID `json:"academic_year_id"`
	Name           string    `json:"name"`
}

// same-name carryover suggestion (e.g. "6A" -> "7A"); ErrNoRows means no
// suggestion, the frontend leaves the target class blank for a manual pick.
func (q *Queries) FindClassByGradeAndName(ctx context.Context, arg FindClassByGradeAndNameParams) (Class, error) {
	row := q.db.QueryRow(ctx, findClassByGradeAndName, arg.GradeID, arg.AcademicYearID, arg.Name)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.GradeID,
		&i.AcademicYearID,
		&i.FormTeacherID,
		&i.StreamID,
		&i.StreamGroupID,
		&i.Name,
		&i.CreatedAt,
		&i.GirlMonitorID,
		&i.BoyMonitorID,
		&i.MediumID,
		&i.HomeClassroomID,
	)
	return i, err
}

const getNextGrade = `-- name: GetNextGrade :one
SELECT g2.id, g2.name, g2.sort_order, g2.created_at
FROM grades g1
INNER JOIN grades g2 ON g2.sort_order > g1.sort_order
WHERE g1.id = $1
ORDER BY g2.sort_order ASC
LIMIT 1
`

// the grade with the smallest sort_order greater than the given grade's;
// pgx.ErrNoRows means the given grade is the top grade (no promotion target
// — the student is graduating, not being promoted to a new class).
func (q *Queries) GetNextGrade(ctx context.Context, id uuid.UUID) (Grade, error) {
	row := q.db.QueryRow(ctx, getNextGrade, id)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveStudentsForYear = `-- name: ListActiveStudentsForYear :many
SELECT
    sp.id           AS student_id,
    sp.full_name    AS student_name,
    sp.index_number AS student_index,
    c.id            AS class_id,
    c.name          AS class_name,
    c.medium_id     AS medium_id,
    m.name          AS medium_name,
    g.id            AS grade_id,
    g.name          AS grade_name,
    g.sort_order    AS grade_sort_order
FROM class_students cs
INNER JOIN student_profiles sp ON sp.id = cs.student_id
INNER JOIN classes c           ON c.id = cs.class_id
INNER JOIN grades g            ON g.id = c.grade_id
LEFT JOIN  mediums m           ON m.id = c.medium_id
WHERE cs.academic_year_id = $1
  AND sp.enrollment_status = 'active'
ORDER BY g.sort_order ASC, c.name ASC, sp.full_name ASC
`

type ListActiveStudentsForYearRow struct {
	StudentID      uuid.UUID   `json:"student_id"`
	StudentName    string      `json:"student_name"`
	StudentIndex   string      `json:"student_index"`
	ClassID        uuid.UUID   `json:"class_id"`
	ClassName      string      `json:"class_name"`
	MediumID       pgtype.UUID `json:"medium_id"`
	MediumName     pgtype.Text `json:"medium_name"`
	GradeID        uuid.UUID   `json:"grade_id"`
	GradeName      string      `json:"grade_name"`
	GradeSortOrder int32       `json:"grade_sort_order"`
}

// every actively-enrolled student's current class/grade for an academic
// year — the source list for a promotion/reassignment preview.
func (q *Queries) ListActiveStudentsForYear(ctx context.Context, academicYearID uuid.UUID) ([]ListActiveStudentsForYearRow, error) {
	rows, err := q.db.Query(ctx, listActiveStudentsForYear, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveStudentsForYearRow{}
	for rows.Next() {
		var i ListActiveStudentsForYearRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.StudentIndex,
			&i.ClassID,
			&i.ClassName,
			&i.MediumID,
			&i.MediumName,
			&i.GradeID,
			&i.GradeName,
			&i.GradeSortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentTotalMarksForTerm = `-- name: ListStudentTotalMarksForTerm :many
SELECT
    student_id,
    SUM(marks)::float8     AS total_marks,
    SUM(max_marks)::float8 AS total_max_marks
FROM term_marks
WHERE term_id = $1 AND student_id = ANY($2::uuid[])
GROUP BY student_id
`

type ListStudentTotalMarksForTermParams struct {
	TermID     uuid.UUID   `json:"term_id"`
	StudentIds []uuid.UUID `json:"student_ids"`
}

type ListStudentTotalMarksForTermRow struct {
	StudentID     uuid.UUID `json:"student_id"`
	TotalMarks    float64   `json:"total_marks"`
	TotalMaxMarks float64   `json:"total_max_marks"`
}

// per-student total marks for one term, across every subject they have a
// mark for — a manual-distribution sort aid, not an auto-ranking algorithm.
// cast to float8 rather than leaving as numeric — sqlc's static analyzer
// (no live DB connection) mis-infers a bare SUM(numeric) as int64, which
// would silently truncate marks with a fractional part.
func (q *Queries) ListStudentTotalMarksForTerm(ctx context.Context, arg ListStudentTotalMarksForTermParams) ([]ListStudentTotalMarksForTermRow, error) {
	rows, err := q.db.Query(ctx, listStudentTotalMarksForTerm, arg.TermID, arg.StudentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentTotalMarksForTermRow{}
	for rows.Next() {
		var i ListStudentTotalMarksForTermRow
		if err := rows.Scan(&i.StudentID, &i.TotalMarks, &i.TotalMaxMarks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
