// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ── group subjects ──────────────────────────────────────────────────────────
	AddGroupSubject(ctx context.Context, arg AddGroupSubjectParams) (GroupSubject, error)
	AssignFormTeacher(ctx context.Context, arg AssignFormTeacherParams) (Class, error)
	AssignSubjectTeacherToClass(ctx context.Context, arg AssignSubjectTeacherToClassParams) error
	AssignSubjectToTeacher(ctx context.Context, arg AssignSubjectToTeacherParams) error
	CountGroupSubjects(ctx context.Context, groupID uuid.UUID) (int64, error)
	CreateAcademicYear(ctx context.Context, arg CreateAcademicYearParams) (AcademicYear, error)
	CreateAttendanceSession(ctx context.Context, arg CreateAttendanceSessionParams) (AttendanceSession, error)
	CreateClass(ctx context.Context, arg CreateClassParams) (Class, error)
	CreateGrade(ctx context.Context, arg CreateGradeParams) (Grade, error)
	CreateGuardian(ctx context.Context, arg CreateGuardianParams) (Guardian, error)
	CreateHouse(ctx context.Context, arg CreateHouseParams) (House, error)
	// ── levels ──────────────────────────────────────────────────────────────────
	CreateLevel(ctx context.Context, arg CreateLevelParams) (Level, error)
	// ── mediums ─────────────────────────────────────────────────────────────────
	CreateMedium(ctx context.Context, name string) (Medium, error)
	CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error)
	// ── selection groups ────────────────────────────────────────────────────────
	CreateSelectionGroup(ctx context.Context, arg CreateSelectionGroupParams) (SelectionGroup, error)
	CreateStream(ctx context.Context, name string) (Stream, error)
	CreateStreamGroup(ctx context.Context, arg CreateStreamGroupParams) (StreamGroup, error)
	CreateStudentProfile(ctx context.Context, arg CreateStudentProfileParams) (StudentProfile, error)
	CreateStudentSubjectEnrollment(ctx context.Context, arg CreateStudentSubjectEnrollmentParams) (StudentSubjectEnrollment, error)
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	CreateTeacherProfile(ctx context.Context, arg CreateTeacherProfileParams) (TeacherProfile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) (User, error)
	DeleteAcademicYear(ctx context.Context, id uuid.UUID) (int64, error)
	// attendance_records cascade with the session
	DeleteAttendanceSession(ctx context.Context, id uuid.UUID) error
	DeleteClass(ctx context.Context, id uuid.UUID) error
	DeleteGrade(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteHouse(ctx context.Context, id uuid.UUID) (int64, error)
	// blocked while any of its groups still carry enrollments
	DeleteLevel(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMedium(ctx context.Context, id uuid.UUID) (int64, error)
	// blocked while enrollments reference it
	DeleteSelectionGroup(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteStream(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteStreamGroup(ctx context.Context, id uuid.UUID) (int64, error)
	// clears a student's picks for one level/year so a re-submit replaces them
	DeleteStudentEnrollmentsForLevel(ctx context.Context, arg DeleteStudentEnrollmentsForLevelParams) error
	DeleteStudentProfile(ctx context.Context, id uuid.UUID) error
	DeleteStudentSubjectEnrollment(ctx context.Context, arg DeleteStudentSubjectEnrollmentParams) error
	DeleteSubject(ctx context.Context, id uuid.UUID) (int64, error)
	// blocked while the teacher is assigned to teach a class subject, or has
	// taken an attendance session (both ON DELETE RESTRICT)
	DeleteTeacher(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	EnrollStudentInClass(ctx context.Context, arg EnrollStudentInClassParams) error
	GetAcademicYearByID(ctx context.Context, id uuid.UUID) (AcademicYear, error)
	GetAttendanceRecord(ctx context.Context, arg GetAttendanceRecordParams) (AttendanceRecord, error)
	GetAttendanceSessionByClassAndDate(ctx context.Context, arg GetAttendanceSessionByClassAndDateParams) (AttendanceSession, error)
	GetAttendanceSessionByID(ctx context.Context, id uuid.UUID) (AttendanceSession, error)
	GetAttendanceSummaryByStudent(ctx context.Context, arg GetAttendanceSummaryByStudentParams) (GetAttendanceSummaryByStudentRow, error)
	GetClassByID(ctx context.Context, id uuid.UUID) (Class, error)
	GetClassStudentCount(ctx context.Context, classID uuid.UUID) (int64, error)
	GetCurrentAcademicYear(ctx context.Context) (AcademicYear, error)
	// ── curriculum tree ─────────────────────────────────────────────────────────
	// every group of a level with its subjects flattened alongside it.
	// LEFT JOIN so a group with no subjects yet still comes back.
	GetCurriculumTreeByLevel(ctx context.Context, levelID uuid.UUID) ([]GetCurriculumTreeByLevelRow, error)
	GetFormTeacherClass(ctx context.Context, formTeacherID pgtype.UUID) (Class, error)
	GetGradeByID(ctx context.Context, id uuid.UUID) (Grade, error)
	GetGuardianByID(ctx context.Context, id uuid.UUID) (Guardian, error)
	GetHouseByID(ctx context.Context, id uuid.UUID) (House, error)
	GetLevelByID(ctx context.Context, id uuid.UUID) (Level, error)
	GetMediumByID(ctx context.Context, id uuid.UUID) (Medium, error)
	GetPrimaryGuardian(ctx context.Context, studentID uuid.UUID) (Guardian, error)
	GetSchool(ctx context.Context) (School, error)
	GetSelectionGroupByID(ctx context.Context, id uuid.UUID) (SelectionGroup, error)
	GetStreamByID(ctx context.Context, id uuid.UUID) (Stream, error)
	GetStreamGroupByID(ctx context.Context, id uuid.UUID) (StreamGroup, error)
	GetStudentByID(ctx context.Context, id uuid.UUID) (StudentProfile, error)
	GetStudentByIndexNumber(ctx context.Context, indexNumber string) (StudentProfile, error)
	GetStudentByUserID(ctx context.Context, userID pgtype.UUID) (StudentProfile, error)
	GetStudentCurrentClass(ctx context.Context, studentID uuid.UUID) (Class, error)
	GetStudentWithClass(ctx context.Context, id uuid.UUID) (GetStudentWithClassRow, error)
	GetSubjectByCode(ctx context.Context, code string) (Subject, error)
	GetSubjectByID(ctx context.Context, id uuid.UUID) (Subject, error)
	GetTeacherByEmployeeNumber(ctx context.Context, employeeNumber string) (TeacherProfile, error)
	GetTeacherByID(ctx context.Context, id uuid.UUID) (TeacherProfile, error)
	GetTeacherByUserID(ctx context.Context, userID uuid.UUID) (TeacherProfile, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	LinkGuardianToStudent(ctx context.Context, arg LinkGuardianToStudentParams) error
	ListAcademicYears(ctx context.Context) ([]AcademicYear, error)
	ListAttendanceBySession(ctx context.Context, sessionID uuid.UUID) ([]ListAttendanceBySessionRow, error)
	ListAttendanceByStudent(ctx context.Context, studentID uuid.UUID) ([]ListAttendanceByStudentRow, error)
	ListAttendanceSessionsByClass(ctx context.Context, classID uuid.UUID) ([]AttendanceSession, error)
	// the cross-class daily dashboard: every session on one date, with the class,
	// grade and teacher resolved, plus enough counts to show marked/pending and
	// how many of the enrolled students have a record so far
	ListAttendanceSessionsByDate(ctx context.Context, date pgtype.Date) ([]ListAttendanceSessionsByDateRow, error)
	ListClassesByAcademicYear(ctx context.Context, academicYearID uuid.UUID) ([]ListClassesByAcademicYearRow, error)
	ListCurrentClasses(ctx context.Context) ([]ListCurrentClassesRow, error)
	ListGrades(ctx context.Context) ([]Grade, error)
	ListGroupSubjects(ctx context.Context, groupID uuid.UUID) ([]ListGroupSubjectsRow, error)
	ListGuardiansByStudent(ctx context.Context, studentID uuid.UUID) ([]ListGuardiansByStudentRow, error)
	ListHouses(ctx context.Context) ([]House, error)
	ListLevels(ctx context.Context) ([]Level, error)
	ListLevelsByGrade(ctx context.Context, gradeID pgtype.UUID) ([]Level, error)
	ListMediums(ctx context.Context) ([]Medium, error)
	ListSelectionGroupsByLevel(ctx context.Context, levelID uuid.UUID) ([]SelectionGroup, error)
	// everything needed to validate a set of picks against a level in one round trip
	ListSelectionGroupsWithSubjectIDsByLevel(ctx context.Context, levelID uuid.UUID) ([]ListSelectionGroupsWithSubjectIDsByLevelRow, error)
	ListStreamGroupsByStream(ctx context.Context, streamID uuid.UUID) ([]StreamGroup, error)
	ListStreams(ctx context.Context) ([]Stream, error)
	ListStudentEnrollments(ctx context.Context, arg ListStudentEnrollmentsParams) ([]ListStudentEnrollmentsRow, error)
	ListStudentEnrollmentsByLevel(ctx context.Context, arg ListStudentEnrollmentsByLevelParams) ([]ListStudentEnrollmentsByLevelRow, error)
	ListStudents(ctx context.Context) ([]ListStudentsRow, error)
	ListStudentsByClass(ctx context.Context, classID uuid.UUID) ([]StudentProfile, error)
	ListStudentsByGroup(ctx context.Context, arg ListStudentsByGroupParams) ([]ListStudentsByGroupRow, error)
	ListStudentsBySubject(ctx context.Context, arg ListStudentsBySubjectParams) ([]ListStudentsBySubjectRow, error)
	ListStudentsMissingHouse(ctx context.Context) ([]StudentProfile, error)
	ListSubjectTeachersByClass(ctx context.Context, classID uuid.UUID) ([]ListSubjectTeachersByClassRow, error)
	ListSubjects(ctx context.Context) ([]Subject, error)
	ListSubjectsByTeacher(ctx context.Context, teacherID uuid.UUID) ([]Subject, error)
	ListTeachers(ctx context.Context) ([]TeacherProfile, error)
	ListTeachersBySubject(ctx context.Context, subjectID uuid.UUID) ([]TeacherProfile, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByRole(ctx context.Context, role string) ([]User, error)
	MarkAttendance(ctx context.Context, arg MarkAttendanceParams) (AttendanceRecord, error)
	RemoveGroupSubject(ctx context.Context, arg RemoveGroupSubjectParams) error
	RemoveSubjectFromTeacher(ctx context.Context, arg RemoveSubjectFromTeacherParams) error
	SetCurrentAcademicYear(ctx context.Context, id uuid.UUID) error
	SetPrimaryContact(ctx context.Context, arg SetPrimaryContactParams) error
	UnenrollStudentFromClass(ctx context.Context, arg UnenrollStudentFromClassParams) error
	UnlinkGuardianFromStudent(ctx context.Context, arg UnlinkGuardianFromStudentParams) error
	UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error)
	UpdateGrade(ctx context.Context, arg UpdateGradeParams) (Grade, error)
	UpdateGuardian(ctx context.Context, arg UpdateGuardianParams) (Guardian, error)
	UpdateHouse(ctx context.Context, arg UpdateHouseParams) (House, error)
	UpdateLevel(ctx context.Context, arg UpdateLevelParams) (Level, error)
	UpdateMedium(ctx context.Context, arg UpdateMediumParams) (Medium, error)
	UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error)
	UpdateSelectionGroup(ctx context.Context, arg UpdateSelectionGroupParams) (SelectionGroup, error)
	UpdateStream(ctx context.Context, arg UpdateStreamParams) (Stream, error)
	UpdateStreamGroup(ctx context.Context, arg UpdateStreamGroupParams) (StreamGroup, error)
	UpdateStudentHouse(ctx context.Context, arg UpdateStudentHouseParams) (StudentProfile, error)
	UpdateStudentProfile(ctx context.Context, arg UpdateStudentProfileParams) (StudentProfile, error)
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
	UpdateTeacherProfile(ctx context.Context, arg UpdateTeacherProfileParams) (TeacherProfile, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
