// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const searchGuardians = `-- name: SearchGuardians :many
SELECT id, full_name, phone
FROM guardians
WHERE full_name ILIKE '%' || $1 || '%'
   OR phone ILIKE '%' || $1 || '%'
ORDER BY full_name ASC
LIMIT 5
`

type SearchGuardiansRow struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Phone    string    `json:"phone"`
}

// Top 5 guardians matching a name/phone fragment, for the admin header's
// global search.
func (q *Queries) SearchGuardians(ctx context.Context, dollar_1 pgtype.Text) ([]SearchGuardiansRow, error) {
	rows, err := q.db.Query(ctx, searchGuardians, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchGuardiansRow{}
	for rows.Next() {
		var i SearchGuardiansRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.Phone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNonAcademicStaff = `-- name: SearchNonAcademicStaff :many
SELECT id, full_name, employee_number
FROM non_academic_staff
WHERE full_name ILIKE '%' || $1 || '%'
   OR employee_number ILIKE '%' || $1 || '%'
ORDER BY full_name ASC
LIMIT 5
`

type SearchNonAcademicStaffRow struct {
	ID             uuid.UUID `json:"id"`
	FullName       string    `json:"full_name"`
	EmployeeNumber string    `json:"employee_number"`
}

// Top 5 non-academic staff matching a name/employee-number fragment, for
// the admin header's global search.
func (q *Queries) SearchNonAcademicStaff(ctx context.Context, dollar_1 pgtype.Text) ([]SearchNonAcademicStaffRow, error) {
	rows, err := q.db.Query(ctx, searchNonAcademicStaff, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNonAcademicStaffRow{}
	for rows.Next() {
		var i SearchNonAcademicStaffRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.EmployeeNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchStudents = `-- name: SearchStudents :many
SELECT id, full_name, index_number
FROM student_profiles
WHERE full_name ILIKE '%' || $1 || '%'
   OR index_number ILIKE '%' || $1 || '%'
ORDER BY full_name ASC
LIMIT 5
`

type SearchStudentsRow struct {
	ID          uuid.UUID `json:"id"`
	FullName    string    `json:"full_name"`
	IndexNumber string    `json:"index_number"`
}

// Top 5 students matching a name/index-number fragment, for the admin
// header's global search — not a full paginated list endpoint.
func (q *Queries) SearchStudents(ctx context.Context, dollar_1 pgtype.Text) ([]SearchStudentsRow, error) {
	rows, err := q.db.Query(ctx, searchStudents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchStudentsRow{}
	for rows.Next() {
		var i SearchStudentsRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.IndexNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTeachers = `-- name: SearchTeachers :many
SELECT id, full_name, employee_number
FROM teacher_profiles
WHERE full_name ILIKE '%' || $1 || '%'
   OR employee_number ILIKE '%' || $1 || '%'
ORDER BY full_name ASC
LIMIT 5
`

type SearchTeachersRow struct {
	ID             uuid.UUID `json:"id"`
	FullName       string    `json:"full_name"`
	EmployeeNumber string    `json:"employee_number"`
}

// Top 5 teachers matching a name/employee-number fragment, for the admin
// header's global search.
func (q *Queries) SearchTeachers(ctx context.Context, dollar_1 pgtype.Text) ([]SearchTeachersRow, error) {
	rows, err := q.db.Query(ctx, searchTeachers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTeachersRow{}
	for rows.Next() {
		var i SearchTeachersRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.EmployeeNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
