// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: society.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSociety = `-- name: CreateSociety :one
INSERT INTO societies (name, teacher_in_charge_id, academic_year_id)
VALUES ($1, $2, $3)
RETURNING id, name, teacher_in_charge_id, academic_year_id, created_at
`

type CreateSocietyParams struct {
	Name              string    `json:"name"`
	TeacherInChargeID uuid.UUID `json:"teacher_in_charge_id"`
	AcademicYearID    uuid.UUID `json:"academic_year_id"`
}

func (q *Queries) CreateSociety(ctx context.Context, arg CreateSocietyParams) (Society, error) {
	row := q.db.QueryRow(ctx, createSociety, arg.Name, arg.TeacherInChargeID, arg.AcademicYearID)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeacherInChargeID,
		&i.AcademicYearID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSociety = `-- name: DeleteSociety :execrows
DELETE FROM societies WHERE id = $1
`

func (q *Queries) DeleteSociety(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSociety, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSocietyByID = `-- name: GetSocietyByID :one
SELECT id, name, teacher_in_charge_id, academic_year_id, created_at FROM societies WHERE id = $1
`

func (q *Queries) GetSocietyByID(ctx context.Context, id uuid.UUID) (Society, error) {
	row := q.db.QueryRow(ctx, getSocietyByID, id)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeacherInChargeID,
		&i.AcademicYearID,
		&i.CreatedAt,
	)
	return i, err
}

const getSocietyForTeacher = `-- name: GetSocietyForTeacher :one
SELECT id, name, teacher_in_charge_id, academic_year_id, created_at FROM societies
WHERE teacher_in_charge_id = $1 AND academic_year_id = $2
`

type GetSocietyForTeacherParams struct {
	TeacherInChargeID uuid.UUID `json:"teacher_in_charge_id"`
	AcademicYearID    uuid.UUID `json:"academic_year_id"`
}

// resolves the "My Society" page: the society a teacher is TIC of, for a
// given academic year.
func (q *Queries) GetSocietyForTeacher(ctx context.Context, arg GetSocietyForTeacherParams) (Society, error) {
	row := q.db.QueryRow(ctx, getSocietyForTeacher, arg.TeacherInChargeID, arg.AcademicYearID)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeacherInChargeID,
		&i.AcademicYearID,
		&i.CreatedAt,
	)
	return i, err
}

const listSocietiesByYear = `-- name: ListSocietiesByYear :many
SELECT
    s.id,
    s.name,
    s.teacher_in_charge_id,
    s.academic_year_id,
    s.created_at,
    tp.full_name AS teacher_name,
    (SELECT COUNT(*) FROM society_members sm WHERE sm.society_id = s.id) AS member_count
FROM societies s
INNER JOIN teacher_profiles tp ON tp.id = s.teacher_in_charge_id
WHERE s.academic_year_id = $1
ORDER BY s.name ASC
`

type ListSocietiesByYearRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	TeacherInChargeID uuid.UUID          `json:"teacher_in_charge_id"`
	AcademicYearID    uuid.UUID          `json:"academic_year_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	TeacherName       string             `json:"teacher_name"`
	MemberCount       int64              `json:"member_count"`
}

func (q *Queries) ListSocietiesByYear(ctx context.Context, academicYearID uuid.UUID) ([]ListSocietiesByYearRow, error) {
	rows, err := q.db.Query(ctx, listSocietiesByYear, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocietiesByYearRow{}
	for rows.Next() {
		var i ListSocietiesByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeacherInChargeID,
			&i.AcademicYearID,
			&i.CreatedAt,
			&i.TeacherName,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocietyMembersBySociety = `-- name: ListSocietyMembersBySociety :many
SELECT
    sm.id,
    sm.society_id,
    sm.student_id,
    sm.role,
    sm.academic_year_id,
    sm.created_at,
    sp.full_name    AS student_name,
    sp.index_number AS student_index,
    g.name          AS grade_name
FROM society_members sm
INNER JOIN student_profiles sp ON sp.id = sm.student_id
LEFT JOIN  class_students cs   ON cs.student_id = sp.id AND cs.academic_year_id = sm.academic_year_id
LEFT JOIN  classes c           ON c.id = cs.class_id
LEFT JOIN  grades g            ON g.id = c.grade_id
WHERE sm.society_id = $1
ORDER BY
    CASE sm.role
        WHEN 'leader' THEN 1
        WHEN 'deputy_leader' THEN 2
        WHEN 'secretary' THEN 3
        WHEN 'treasurer' THEN 4
        WHEN 'member' THEN 5
    END,
    sp.full_name ASC
`

type ListSocietyMembersBySocietyRow struct {
	ID             uuid.UUID          `json:"id"`
	SocietyID      uuid.UUID          `json:"society_id"`
	StudentID      uuid.UUID          `json:"student_id"`
	Role           string             `json:"role"`
	AcademicYearID uuid.UUID          `json:"academic_year_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StudentName    string             `json:"student_name"`
	StudentIndex   string             `json:"student_index"`
	GradeName      pgtype.Text        `json:"grade_name"`
}

// class_students carries one row per (student, academic_year) — filtering
// to the membership's own year here (not just at the classes join below)
// keeps this to at most one row per student; without it, a student with
// class history in other years produced one duplicate output row per
// extra year, each with grade_name NULL except the matching one.
func (q *Queries) ListSocietyMembersBySociety(ctx context.Context, societyID uuid.UUID) ([]ListSocietyMembersBySocietyRow, error) {
	rows, err := q.db.Query(ctx, listSocietyMembersBySociety, societyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocietyMembersBySocietyRow{}
	for rows.Next() {
		var i ListSocietyMembersBySocietyRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.StudentID,
			&i.Role,
			&i.AcademicYearID,
			&i.CreatedAt,
			&i.StudentName,
			&i.StudentIndex,
			&i.GradeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocietyMembershipsByStudent = `-- name: ListSocietyMembershipsByStudent :many
SELECT
    sm.id,
    sm.society_id,
    sm.role,
    sm.academic_year_id,
    sm.created_at,
    s.name   AS society_name,
    ay.label AS academic_year_label
FROM society_members sm
INNER JOIN societies s       ON s.id = sm.society_id
INNER JOIN academic_years ay ON ay.id = sm.academic_year_id
WHERE sm.student_id = $1
ORDER BY ay.start_date DESC
`

type ListSocietyMembershipsByStudentRow struct {
	ID                uuid.UUID          `json:"id"`
	SocietyID         uuid.UUID          `json:"society_id"`
	Role              string             `json:"role"`
	AcademicYearID    uuid.UUID          `json:"academic_year_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SocietyName       string             `json:"society_name"`
	AcademicYearLabel string             `json:"academic_year_label"`
}

// every society membership a student holds, across all years — for the
// student portfolio view.
func (q *Queries) ListSocietyMembershipsByStudent(ctx context.Context, studentID uuid.UUID) ([]ListSocietyMembershipsByStudentRow, error) {
	rows, err := q.db.Query(ctx, listSocietyMembershipsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocietyMembershipsByStudentRow{}
	for rows.Next() {
		var i ListSocietyMembershipsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.Role,
			&i.AcademicYearID,
			&i.CreatedAt,
			&i.SocietyName,
			&i.AcademicYearLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocietyYears = `-- name: ListSocietyYears :many
SELECT DISTINCT ay.id, ay.label, ay.start_date
FROM societies s
INNER JOIN academic_years ay ON ay.id = s.academic_year_id
ORDER BY ay.start_date DESC
`

type ListSocietyYearsRow struct {
	ID        uuid.UUID   `json:"id"`
	Label     string      `json:"label"`
	StartDate pgtype.Date `json:"start_date"`
}

// every academic year that has at least one society — powers the
// year-selector's archive view, same pattern as ListPrefectYears.
func (q *Queries) ListSocietyYears(ctx context.Context) ([]ListSocietyYearsRow, error) {
	rows, err := q.db.Query(ctx, listSocietyYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocietyYearsRow{}
	for rows.Next() {
		var i ListSocietyYearsRow
		if err := rows.Scan(&i.ID, &i.Label, &i.StartDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSocietyMember = `-- name: RemoveSocietyMember :execrows
DELETE FROM society_members WHERE id = $1 AND society_id = $2
`

type RemoveSocietyMemberParams struct {
	ID        uuid.UUID `json:"id"`
	SocietyID uuid.UUID `json:"society_id"`
}

// scoped by society_id as well as id: the caller is only authorized for one
// society (SocietyService.authorizeTeacherInCharge), so the delete itself
// must not be able to reach a membership row belonging to a different one.
func (q *Queries) RemoveSocietyMember(ctx context.Context, arg RemoveSocietyMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSocietyMember, arg.ID, arg.SocietyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSociety = `-- name: UpdateSociety :one
UPDATE societies
SET name = $2, teacher_in_charge_id = $3
WHERE id = $1
RETURNING id, name, teacher_in_charge_id, academic_year_id, created_at
`

type UpdateSocietyParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	TeacherInChargeID uuid.UUID `json:"teacher_in_charge_id"`
}

func (q *Queries) UpdateSociety(ctx context.Context, arg UpdateSocietyParams) (Society, error) {
	row := q.db.QueryRow(ctx, updateSociety, arg.ID, arg.Name, arg.TeacherInChargeID)
	var i Society
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeacherInChargeID,
		&i.AcademicYearID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSocietyMember = `-- name: UpsertSocietyMember :one
INSERT INTO society_members (society_id, student_id, role, academic_year_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (society_id, student_id, academic_year_id)
DO UPDATE SET role = EXCLUDED.role
RETURNING id, society_id, student_id, role, academic_year_id, created_at
`

type UpsertSocietyMemberParams struct {
	SocietyID      uuid.UUID `json:"society_id"`
	StudentID      uuid.UUID `json:"student_id"`
	Role           string    `json:"role"`
	AcademicYearID uuid.UUID `json:"academic_year_id"`
}

func (q *Queries) UpsertSocietyMember(ctx context.Context, arg UpsertSocietyMemberParams) (SocietyMember, error) {
	row := q.db.QueryRow(ctx, upsertSocietyMember,
		arg.SocietyID,
		arg.StudentID,
		arg.Role,
		arg.AcademicYearID,
	)
	var i SocietyMember
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.StudentID,
		&i.Role,
		&i.AcademicYearID,
		&i.CreatedAt,
	)
	return i, err
}
