// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff_attendance.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listNonAcademicStaffAttendanceByDate = `-- name: ListNonAcademicStaffAttendanceByDate :many
SELECT
    nas.id            AS staff_id,
    nas.full_name     AS full_name,
    nas.employee_number AS employee_number,
    sar.id            AS record_id,
    sar.status        AS status,
    sar.note          AS note
FROM non_academic_staff nas
LEFT JOIN staff_attendance_records sar
    ON sar.non_academic_staff_id = nas.id AND sar.date = $1
WHERE nas.employment_status = 'active'
ORDER BY nas.full_name ASC
`

type ListNonAcademicStaffAttendanceByDateRow struct {
	StaffID        uuid.UUID   `json:"staff_id"`
	FullName       string      `json:"full_name"`
	EmployeeNumber string      `json:"employee_number"`
	RecordID       pgtype.UUID `json:"record_id"`
	Status         pgtype.Text `json:"status"`
	Note           pgtype.Text `json:"note"`
}

func (q *Queries) ListNonAcademicStaffAttendanceByDate(ctx context.Context, date pgtype.Date) ([]ListNonAcademicStaffAttendanceByDateRow, error) {
	rows, err := q.db.Query(ctx, listNonAcademicStaffAttendanceByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNonAcademicStaffAttendanceByDateRow{}
	for rows.Next() {
		var i ListNonAcademicStaffAttendanceByDateRow
		if err := rows.Scan(
			&i.StaffID,
			&i.FullName,
			&i.EmployeeNumber,
			&i.RecordID,
			&i.Status,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonAcademicStaffAttendanceHistory = `-- name: ListNonAcademicStaffAttendanceHistory :many
SELECT id, teacher_id, non_academic_staff_id, date, status, marked_by, note, created_at, updated_at FROM staff_attendance_records
WHERE non_academic_staff_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date DESC
`

type ListNonAcademicStaffAttendanceHistoryParams struct {
	NonAcademicStaffID pgtype.UUID `json:"non_academic_staff_id"`
	Date               pgtype.Date `json:"date"`
	Date_2             pgtype.Date `json:"date_2"`
}

func (q *Queries) ListNonAcademicStaffAttendanceHistory(ctx context.Context, arg ListNonAcademicStaffAttendanceHistoryParams) ([]StaffAttendanceRecord, error) {
	rows, err := q.db.Query(ctx, listNonAcademicStaffAttendanceHistory, arg.NonAcademicStaffID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffAttendanceRecord{}
	for rows.Next() {
		var i StaffAttendanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.NonAcademicStaffID,
			&i.Date,
			&i.Status,
			&i.MarkedBy,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffAttendanceMonthly = `-- name: ListStaffAttendanceMonthly :many
WITH people AS (
    SELECT tp.id, tp.full_name, tp.employee_number, 'teacher'::text AS kind
    FROM teacher_profiles tp
    WHERE tp.employment_status = 'active' AND $6::text = 'teacher'
    UNION ALL
    SELECT nas.id, nas.full_name, nas.employee_number, 'staff'::text AS kind
    FROM non_academic_staff nas
    WHERE nas.employment_status = 'active' AND $6::text = 'staff'
)
SELECT
    p.id              AS staff_id,
    p.full_name       AS full_name,
    p.employee_number AS employee_number,
    COUNT(sar.id) FILTER (WHERE sar.status = 'present') AS present_count,
    COUNT(sar.id) FILTER (WHERE sar.status = 'late')    AS late_count,
    COUNT(sar.id) FILTER (WHERE sar.status = 'absent')  AS absent_count,
    COUNT(sar.id) FILTER (WHERE sar.status = 'leave')   AS leave_count,
    COUNT(*) OVER () AS total
FROM people p
LEFT JOIN staff_attendance_records sar
    ON sar.date BETWEEN $1::date AND $2::date
   AND ((p.kind = 'teacher' AND sar.teacher_id = p.id) OR (p.kind = 'staff' AND sar.non_academic_staff_id = p.id))
WHERE ($3::text IS NULL OR p.full_name ILIKE '%' || $3::text || '%' OR p.employee_number ILIKE '%' || $3::text || '%')
GROUP BY p.id, p.full_name, p.employee_number
ORDER BY p.full_name ASC, p.id ASC
LIMIT $5::int OFFSET $4::int
`

type ListStaffAttendanceMonthlyParams struct {
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	Search     pgtype.Text `json:"search"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
	Kind       string      `json:"kind"`
}

type ListStaffAttendanceMonthlyRow struct {
	StaffID        uuid.UUID `json:"staff_id"`
	FullName       string    `json:"full_name"`
	EmployeeNumber string    `json:"employee_number"`
	PresentCount   int64     `json:"present_count"`
	LateCount      int64     `json:"late_count"`
	AbsentCount    int64     `json:"absent_count"`
	LeaveCount     int64     `json:"leave_count"`
	Total          int64     `json:"total"`
}

// One page of per-person status counts for the date range, same kind/search contract as above.
func (q *Queries) ListStaffAttendanceMonthly(ctx context.Context, arg ListStaffAttendanceMonthlyParams) ([]ListStaffAttendanceMonthlyRow, error) {
	rows, err := q.db.Query(ctx, listStaffAttendanceMonthly,
		arg.FromDate,
		arg.ToDate,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
		arg.Kind,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaffAttendanceMonthlyRow{}
	for rows.Next() {
		var i ListStaffAttendanceMonthlyRow
		if err := rows.Scan(
			&i.StaffID,
			&i.FullName,
			&i.EmployeeNumber,
			&i.PresentCount,
			&i.LateCount,
			&i.AbsentCount,
			&i.LeaveCount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffAttendanceRoster = `-- name: ListStaffAttendanceRoster :many
WITH people AS (
    SELECT tp.id, tp.full_name, tp.employee_number, 'teacher'::text AS kind
    FROM teacher_profiles tp
    WHERE tp.employment_status = 'active' AND $5::text = 'teacher'
    UNION ALL
    SELECT nas.id, nas.full_name, nas.employee_number, 'staff'::text AS kind
    FROM non_academic_staff nas
    WHERE nas.employment_status = 'active' AND $5::text = 'staff'
)
SELECT
    p.id              AS staff_id,
    p.full_name       AS full_name,
    p.employee_number AS employee_number,
    sar.id            AS record_id,
    sar.status        AS status,
    sar.note          AS note,
    COUNT(*) OVER () AS total,
    COUNT(sar.id) FILTER (WHERE sar.status = 'present') OVER () AS present_total,
    COUNT(sar.id) FILTER (WHERE sar.status = 'late')    OVER () AS late_total,
    COUNT(sar.id) FILTER (WHERE sar.status = 'absent')  OVER () AS absent_total,
    COUNT(sar.id) FILTER (WHERE sar.status = 'leave')   OVER () AS leave_total
FROM people p
LEFT JOIN staff_attendance_records sar
    ON sar.date = $1::date
   AND ((p.kind = 'teacher' AND sar.teacher_id = p.id) OR (p.kind = 'staff' AND sar.non_academic_staff_id = p.id))
WHERE ($2::text IS NULL OR p.full_name ILIKE '%' || $2::text || '%' OR p.employee_number ILIKE '%' || $2::text || '%')
ORDER BY p.full_name ASC, p.id ASC
LIMIT $4::int OFFSET $3::int
`

type ListStaffAttendanceRosterParams struct {
	Date       pgtype.Date `json:"date"`
	Search     pgtype.Text `json:"search"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
	Kind       string      `json:"kind"`
}

type ListStaffAttendanceRosterRow struct {
	StaffID        uuid.UUID   `json:"staff_id"`
	FullName       string      `json:"full_name"`
	EmployeeNumber string      `json:"employee_number"`
	RecordID       pgtype.UUID `json:"record_id"`
	Status         pgtype.Text `json:"status"`
	Note           pgtype.Text `json:"note"`
	Total          int64       `json:"total"`
	PresentTotal   int64       `json:"present_total"`
	LateTotal      int64       `json:"late_total"`
	AbsentTotal    int64       `json:"absent_total"`
	LeaveTotal     int64       `json:"leave_total"`
}

// One page of active teachers or non-academic staff (kind = 'teacher' | 'staff') with
// their record for the date. The window totals cover the whole filtered set, not just
// the page, so the UI can show "12 unmarked" correctly. Search is escaped by the caller.
func (q *Queries) ListStaffAttendanceRoster(ctx context.Context, arg ListStaffAttendanceRosterParams) ([]ListStaffAttendanceRosterRow, error) {
	rows, err := q.db.Query(ctx, listStaffAttendanceRoster,
		arg.Date,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
		arg.Kind,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaffAttendanceRosterRow{}
	for rows.Next() {
		var i ListStaffAttendanceRosterRow
		if err := rows.Scan(
			&i.StaffID,
			&i.FullName,
			&i.EmployeeNumber,
			&i.RecordID,
			&i.Status,
			&i.Note,
			&i.Total,
			&i.PresentTotal,
			&i.LateTotal,
			&i.AbsentTotal,
			&i.LeaveTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherAttendanceByDate = `-- name: ListTeacherAttendanceByDate :many
SELECT
    tp.id          AS teacher_id,
    tp.full_name   AS full_name,
    tp.employee_number AS employee_number,
    sar.id         AS record_id,
    sar.status     AS status,
    sar.note       AS note
FROM teacher_profiles tp
LEFT JOIN staff_attendance_records sar
    ON sar.teacher_id = tp.id AND sar.date = $1
WHERE tp.employment_status = 'active'
ORDER BY tp.full_name ASC
`

type ListTeacherAttendanceByDateRow struct {
	TeacherID      uuid.UUID   `json:"teacher_id"`
	FullName       string      `json:"full_name"`
	EmployeeNumber string      `json:"employee_number"`
	RecordID       pgtype.UUID `json:"record_id"`
	Status         pgtype.Text `json:"status"`
	Note           pgtype.Text `json:"note"`
}

func (q *Queries) ListTeacherAttendanceByDate(ctx context.Context, date pgtype.Date) ([]ListTeacherAttendanceByDateRow, error) {
	rows, err := q.db.Query(ctx, listTeacherAttendanceByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeacherAttendanceByDateRow{}
	for rows.Next() {
		var i ListTeacherAttendanceByDateRow
		if err := rows.Scan(
			&i.TeacherID,
			&i.FullName,
			&i.EmployeeNumber,
			&i.RecordID,
			&i.Status,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherAttendanceHistory = `-- name: ListTeacherAttendanceHistory :many
SELECT id, teacher_id, non_academic_staff_id, date, status, marked_by, note, created_at, updated_at FROM staff_attendance_records
WHERE teacher_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date DESC
`

type ListTeacherAttendanceHistoryParams struct {
	TeacherID pgtype.UUID `json:"teacher_id"`
	Date      pgtype.Date `json:"date"`
	Date_2    pgtype.Date `json:"date_2"`
}

func (q *Queries) ListTeacherAttendanceHistory(ctx context.Context, arg ListTeacherAttendanceHistoryParams) ([]StaffAttendanceRecord, error) {
	rows, err := q.db.Query(ctx, listTeacherAttendanceHistory, arg.TeacherID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffAttendanceRecord{}
	for rows.Next() {
		var i StaffAttendanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.NonAcademicStaffID,
			&i.Date,
			&i.Status,
			&i.MarkedBy,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUnmarkedNonAcademicStaffPresent = `-- name: MarkUnmarkedNonAcademicStaffPresent :execrows
INSERT INTO staff_attendance_records (non_academic_staff_id, date, status, marked_by)
SELECT nas.id, $1::date, 'present', $2::uuid
FROM non_academic_staff nas
WHERE nas.employment_status = 'active'
ON CONFLICT (non_academic_staff_id, date) WHERE non_academic_staff_id IS NOT NULL DO NOTHING
`

type MarkUnmarkedNonAcademicStaffPresentParams struct {
	Date     pgtype.Date `json:"date"`
	MarkedBy uuid.UUID   `json:"marked_by"`
}

func (q *Queries) MarkUnmarkedNonAcademicStaffPresent(ctx context.Context, arg MarkUnmarkedNonAcademicStaffPresentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUnmarkedNonAcademicStaffPresent, arg.Date, arg.MarkedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markUnmarkedTeachersPresent = `-- name: MarkUnmarkedTeachersPresent :execrows
INSERT INTO staff_attendance_records (teacher_id, date, status, marked_by)
SELECT tp.id, $1::date, 'present', $2::uuid
FROM teacher_profiles tp
WHERE tp.employment_status = 'active'
ON CONFLICT (teacher_id, date) WHERE teacher_id IS NOT NULL DO NOTHING
`

type MarkUnmarkedTeachersPresentParams struct {
	Date     pgtype.Date `json:"date"`
	MarkedBy uuid.UUID   `json:"marked_by"`
}

// Present for every active teacher with no record that day; existing marks are left alone.
func (q *Queries) MarkUnmarkedTeachersPresent(ctx context.Context, arg MarkUnmarkedTeachersPresentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUnmarkedTeachersPresent, arg.Date, arg.MarkedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const monthlyNonAcademicStaffAttendanceSummary = `-- name: MonthlyNonAcademicStaffAttendanceSummary :many
SELECT
    nas.id        AS staff_id,
    nas.full_name AS full_name,
    COUNT(*) FILTER (WHERE sar.status = 'present') AS present_count,
    COUNT(*) FILTER (WHERE sar.status = 'late')    AS late_count,
    COUNT(*) FILTER (WHERE sar.status = 'absent')  AS absent_count,
    COUNT(*) FILTER (WHERE sar.status = 'leave')   AS leave_count
FROM non_academic_staff nas
LEFT JOIN staff_attendance_records sar
    ON sar.non_academic_staff_id = nas.id AND sar.date BETWEEN $1 AND $2
WHERE nas.employment_status = 'active'
GROUP BY nas.id, nas.full_name
ORDER BY nas.full_name ASC
`

type MonthlyNonAcademicStaffAttendanceSummaryParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type MonthlyNonAcademicStaffAttendanceSummaryRow struct {
	StaffID      uuid.UUID `json:"staff_id"`
	FullName     string    `json:"full_name"`
	PresentCount int64     `json:"present_count"`
	LateCount    int64     `json:"late_count"`
	AbsentCount  int64     `json:"absent_count"`
	LeaveCount   int64     `json:"leave_count"`
}

func (q *Queries) MonthlyNonAcademicStaffAttendanceSummary(ctx context.Context, arg MonthlyNonAcademicStaffAttendanceSummaryParams) ([]MonthlyNonAcademicStaffAttendanceSummaryRow, error) {
	rows, err := q.db.Query(ctx, monthlyNonAcademicStaffAttendanceSummary, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyNonAcademicStaffAttendanceSummaryRow{}
	for rows.Next() {
		var i MonthlyNonAcademicStaffAttendanceSummaryRow
		if err := rows.Scan(
			&i.StaffID,
			&i.FullName,
			&i.PresentCount,
			&i.LateCount,
			&i.AbsentCount,
			&i.LeaveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyTeacherAttendanceSummary = `-- name: MonthlyTeacherAttendanceSummary :many
SELECT
    tp.id        AS teacher_id,
    tp.full_name AS full_name,
    COUNT(*) FILTER (WHERE sar.status = 'present') AS present_count,
    COUNT(*) FILTER (WHERE sar.status = 'late')    AS late_count,
    COUNT(*) FILTER (WHERE sar.status = 'absent')  AS absent_count,
    COUNT(*) FILTER (WHERE sar.status = 'leave')   AS leave_count
FROM teacher_profiles tp
LEFT JOIN staff_attendance_records sar
    ON sar.teacher_id = tp.id AND sar.date BETWEEN $1 AND $2
WHERE tp.employment_status = 'active'
GROUP BY tp.id, tp.full_name
ORDER BY tp.full_name ASC
`

type MonthlyTeacherAttendanceSummaryParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type MonthlyTeacherAttendanceSummaryRow struct {
	TeacherID    uuid.UUID `json:"teacher_id"`
	FullName     string    `json:"full_name"`
	PresentCount int64     `json:"present_count"`
	LateCount    int64     `json:"late_count"`
	AbsentCount  int64     `json:"absent_count"`
	LeaveCount   int64     `json:"leave_count"`
}

// one row per teacher with a count for each status in the given date range
// (the caller passes the first/last day of the month).
func (q *Queries) MonthlyTeacherAttendanceSummary(ctx context.Context, arg MonthlyTeacherAttendanceSummaryParams) ([]MonthlyTeacherAttendanceSummaryRow, error) {
	rows, err := q.db.Query(ctx, monthlyTeacherAttendanceSummary, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyTeacherAttendanceSummaryRow{}
	for rows.Next() {
		var i MonthlyTeacherAttendanceSummaryRow
		if err := rows.Scan(
			&i.TeacherID,
			&i.FullName,
			&i.PresentCount,
			&i.LateCount,
			&i.AbsentCount,
			&i.LeaveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNonAcademicStaffAttendance = `-- name: UpsertNonAcademicStaffAttendance :one
INSERT INTO staff_attendance_records (non_academic_staff_id, date, status, marked_by, note)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (non_academic_staff_id, date) WHERE non_academic_staff_id IS NOT NULL
DO UPDATE SET status = $3, marked_by = $4, note = $5, updated_at = NOW()
RETURNING id, teacher_id, non_academic_staff_id, date, status, marked_by, note, created_at, updated_at
`

type UpsertNonAcademicStaffAttendanceParams struct {
	NonAcademicStaffID pgtype.UUID `json:"non_academic_staff_id"`
	Date               pgtype.Date `json:"date"`
	Status             string      `json:"status"`
	MarkedBy           pgtype.UUID `json:"marked_by"`
	Note               pgtype.Text `json:"note"`
}

func (q *Queries) UpsertNonAcademicStaffAttendance(ctx context.Context, arg UpsertNonAcademicStaffAttendanceParams) (StaffAttendanceRecord, error) {
	row := q.db.QueryRow(ctx, upsertNonAcademicStaffAttendance,
		arg.NonAcademicStaffID,
		arg.Date,
		arg.Status,
		arg.MarkedBy,
		arg.Note,
	)
	var i StaffAttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.NonAcademicStaffID,
		&i.Date,
		&i.Status,
		&i.MarkedBy,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTeacherAttendance = `-- name: UpsertTeacherAttendance :one
INSERT INTO staff_attendance_records (teacher_id, date, status, marked_by, note)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (teacher_id, date) WHERE teacher_id IS NOT NULL
DO UPDATE SET status = $3, marked_by = $4, note = $5, updated_at = NOW()
RETURNING id, teacher_id, non_academic_staff_id, date, status, marked_by, note, created_at, updated_at
`

type UpsertTeacherAttendanceParams struct {
	TeacherID pgtype.UUID `json:"teacher_id"`
	Date      pgtype.Date `json:"date"`
	Status    string      `json:"status"`
	MarkedBy  pgtype.UUID `json:"marked_by"`
	Note      pgtype.Text `json:"note"`
}

func (q *Queries) UpsertTeacherAttendance(ctx context.Context, arg UpsertTeacherAttendanceParams) (StaffAttendanceRecord, error) {
	row := q.db.QueryRow(ctx, upsertTeacherAttendance,
		arg.TeacherID,
		arg.Date,
		arg.Status,
		arg.MarkedBy,
		arg.Note,
	)
	var i StaffAttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.NonAcademicStaffID,
		&i.Date,
		&i.Status,
		&i.MarkedBy,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
