// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student_portfolio.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDisciplinaryRecord = `-- name: CreateDisciplinaryRecord :one

INSERT INTO student_disciplinary_records (student_id, academic_year_id, incident_date, description, action_taken, severity, recorded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, student_id, academic_year_id, incident_date, description, action_taken, severity, recorded_by, created_at
`

type CreateDisciplinaryRecordParams struct {
	StudentID      uuid.UUID   `json:"student_id"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	IncidentDate   pgtype.Date `json:"incident_date"`
	Description    string      `json:"description"`
	ActionTaken    pgtype.Text `json:"action_taken"`
	Severity       string      `json:"severity"`
	RecordedBy     pgtype.UUID `json:"recorded_by"`
}

// Disciplinary records --------------------------------------------------------
func (q *Queries) CreateDisciplinaryRecord(ctx context.Context, arg CreateDisciplinaryRecordParams) (StudentDisciplinaryRecord, error) {
	row := q.db.QueryRow(ctx, createDisciplinaryRecord,
		arg.StudentID,
		arg.AcademicYearID,
		arg.IncidentDate,
		arg.Description,
		arg.ActionTaken,
		arg.Severity,
		arg.RecordedBy,
	)
	var i StudentDisciplinaryRecord
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.AcademicYearID,
		&i.IncidentDate,
		&i.Description,
		&i.ActionTaken,
		&i.Severity,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createProgressReport = `-- name: CreateProgressReport :one

INSERT INTO student_progress_reports (student_id, term_id, narrative, written_by)
VALUES ($1, $2, $3, $4)
RETURNING id, student_id, term_id, narrative, written_by, created_at, updated_at
`

type CreateProgressReportParams struct {
	StudentID uuid.UUID   `json:"student_id"`
	TermID    uuid.UUID   `json:"term_id"`
	Narrative string      `json:"narrative"`
	WrittenBy pgtype.UUID `json:"written_by"`
}

// Progress reports --------------------------------------------------------
func (q *Queries) CreateProgressReport(ctx context.Context, arg CreateProgressReportParams) (StudentProgressReport, error) {
	row := q.db.QueryRow(ctx, createProgressReport,
		arg.StudentID,
		arg.TermID,
		arg.Narrative,
		arg.WrittenBy,
	)
	var i StudentProgressReport
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.TermID,
		&i.Narrative,
		&i.WrittenBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStudentActivity = `-- name: CreateStudentActivity :one

INSERT INTO student_activities (student_id, academic_year_id, category, name, role, achievement)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, student_id, academic_year_id, category, name, role, achievement, created_at
`

type CreateStudentActivityParams struct {
	StudentID      uuid.UUID   `json:"student_id"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	Category       string      `json:"category"`
	Name           string      `json:"name"`
	Role           pgtype.Text `json:"role"`
	Achievement    pgtype.Text `json:"achievement"`
}

// Activities ---------------------------------------------------------------
func (q *Queries) CreateStudentActivity(ctx context.Context, arg CreateStudentActivityParams) (StudentActivity, error) {
	row := q.db.QueryRow(ctx, createStudentActivity,
		arg.StudentID,
		arg.AcademicYearID,
		arg.Category,
		arg.Name,
		arg.Role,
		arg.Achievement,
	)
	var i StudentActivity
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.AcademicYearID,
		&i.Category,
		&i.Name,
		&i.Role,
		&i.Achievement,
		&i.CreatedAt,
	)
	return i, err
}

const createStudentAward = `-- name: CreateStudentAward :one

INSERT INTO student_awards (student_id, academic_year_id, title, category, awarded_date, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, student_id, academic_year_id, title, category, awarded_date, description, created_at
`

type CreateStudentAwardParams struct {
	StudentID      uuid.UUID   `json:"student_id"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	Title          string      `json:"title"`
	Category       pgtype.Text `json:"category"`
	AwardedDate    pgtype.Date `json:"awarded_date"`
	Description    pgtype.Text `json:"description"`
}

// Awards ---------------------------------------------------------------------
func (q *Queries) CreateStudentAward(ctx context.Context, arg CreateStudentAwardParams) (StudentAward, error) {
	row := q.db.QueryRow(ctx, createStudentAward,
		arg.StudentID,
		arg.AcademicYearID,
		arg.Title,
		arg.Category,
		arg.AwardedDate,
		arg.Description,
	)
	var i StudentAward
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.AcademicYearID,
		&i.Title,
		&i.Category,
		&i.AwardedDate,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createStudentLeadershipRole = `-- name: CreateStudentLeadershipRole :one

INSERT INTO student_leadership_roles (student_id, academic_year_id, title, scope)
VALUES ($1, $2, $3, $4)
RETURNING id, student_id, academic_year_id, title, scope, created_at
`

type CreateStudentLeadershipRoleParams struct {
	StudentID      uuid.UUID   `json:"student_id"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	Title          string      `json:"title"`
	Scope          pgtype.Text `json:"scope"`
}

// Leadership roles -----------------------------------------------------------
func (q *Queries) CreateStudentLeadershipRole(ctx context.Context, arg CreateStudentLeadershipRoleParams) (StudentLeadershipRole, error) {
	row := q.db.QueryRow(ctx, createStudentLeadershipRole,
		arg.StudentID,
		arg.AcademicYearID,
		arg.Title,
		arg.Scope,
	)
	var i StudentLeadershipRole
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.AcademicYearID,
		&i.Title,
		&i.Scope,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDisciplinaryRecord = `-- name: DeleteDisciplinaryRecord :execrows
DELETE FROM student_disciplinary_records WHERE id = $1
`

func (q *Queries) DeleteDisciplinaryRecord(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDisciplinaryRecord, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProgressReport = `-- name: DeleteProgressReport :execrows
DELETE FROM student_progress_reports WHERE id = $1
`

func (q *Queries) DeleteProgressReport(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgressReport, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStudentActivity = `-- name: DeleteStudentActivity :execrows
DELETE FROM student_activities WHERE id = $1
`

func (q *Queries) DeleteStudentActivity(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentActivity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStudentAward = `-- name: DeleteStudentAward :execrows
DELETE FROM student_awards WHERE id = $1
`

func (q *Queries) DeleteStudentAward(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentAward, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStudentLeadershipRole = `-- name: DeleteStudentLeadershipRole :execrows
DELETE FROM student_leadership_roles WHERE id = $1
`

func (q *Queries) DeleteStudentLeadershipRole(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentLeadershipRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDisciplinaryRecordsByStudent = `-- name: ListDisciplinaryRecordsByStudent :many
SELECT id, student_id, academic_year_id, incident_date, description, action_taken, severity, recorded_by, created_at FROM student_disciplinary_records
WHERE student_id = $1
ORDER BY incident_date DESC
`

func (q *Queries) ListDisciplinaryRecordsByStudent(ctx context.Context, studentID uuid.UUID) ([]StudentDisciplinaryRecord, error) {
	rows, err := q.db.Query(ctx, listDisciplinaryRecordsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentDisciplinaryRecord{}
	for rows.Next() {
		var i StudentDisciplinaryRecord
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.AcademicYearID,
			&i.IncidentDate,
			&i.Description,
			&i.ActionTaken,
			&i.Severity,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressReportsByStudent = `-- name: ListProgressReportsByStudent :many
SELECT spr.id, spr.student_id, spr.term_id, spr.narrative, spr.written_by, spr.created_at, spr.updated_at, t.name AS term_name
FROM student_progress_reports spr
INNER JOIN terms t ON t.id = spr.term_id
WHERE spr.student_id = $1
ORDER BY t.sort_order DESC
`

type ListProgressReportsByStudentRow struct {
	ID        uuid.UUID          `json:"id"`
	StudentID uuid.UUID          `json:"student_id"`
	TermID    uuid.UUID          `json:"term_id"`
	Narrative string             `json:"narrative"`
	WrittenBy pgtype.UUID        `json:"written_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	TermName  string             `json:"term_name"`
}

func (q *Queries) ListProgressReportsByStudent(ctx context.Context, studentID uuid.UUID) ([]ListProgressReportsByStudentRow, error) {
	rows, err := q.db.Query(ctx, listProgressReportsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgressReportsByStudentRow{}
	for rows.Next() {
		var i ListProgressReportsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TermID,
			&i.Narrative,
			&i.WrittenBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TermName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentActivitiesByStudent = `-- name: ListStudentActivitiesByStudent :many
SELECT id, student_id, academic_year_id, category, name, role, achievement, created_at FROM student_activities
WHERE student_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStudentActivitiesByStudent(ctx context.Context, studentID uuid.UUID) ([]StudentActivity, error) {
	rows, err := q.db.Query(ctx, listStudentActivitiesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentActivity{}
	for rows.Next() {
		var i StudentActivity
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.AcademicYearID,
			&i.Category,
			&i.Name,
			&i.Role,
			&i.Achievement,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentAwardsByStudent = `-- name: ListStudentAwardsByStudent :many
SELECT id, student_id, academic_year_id, title, category, awarded_date, description, created_at FROM student_awards
WHERE student_id = $1
ORDER BY awarded_date DESC
`

func (q *Queries) ListStudentAwardsByStudent(ctx context.Context, studentID uuid.UUID) ([]StudentAward, error) {
	rows, err := q.db.Query(ctx, listStudentAwardsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentAward{}
	for rows.Next() {
		var i StudentAward
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.AcademicYearID,
			&i.Title,
			&i.Category,
			&i.AwardedDate,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentLeadershipRolesByStudent = `-- name: ListStudentLeadershipRolesByStudent :many
SELECT id, student_id, academic_year_id, title, scope, created_at FROM student_leadership_roles
WHERE student_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStudentLeadershipRolesByStudent(ctx context.Context, studentID uuid.UUID) ([]StudentLeadershipRole, error) {
	rows, err := q.db.Query(ctx, listStudentLeadershipRolesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentLeadershipRole{}
	for rows.Next() {
		var i StudentLeadershipRole
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.AcademicYearID,
			&i.Title,
			&i.Scope,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgressReport = `-- name: UpdateProgressReport :one
UPDATE student_progress_reports
SET narrative = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, student_id, term_id, narrative, written_by, created_at, updated_at
`

type UpdateProgressReportParams struct {
	ID        uuid.UUID `json:"id"`
	Narrative string    `json:"narrative"`
}

func (q *Queries) UpdateProgressReport(ctx context.Context, arg UpdateProgressReportParams) (StudentProgressReport, error) {
	row := q.db.QueryRow(ctx, updateProgressReport, arg.ID, arg.Narrative)
	var i StudentProgressReport
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.TermID,
		&i.Narrative,
		&i.WrittenBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStudentActivity = `-- name: UpdateStudentActivity :one
UPDATE student_activities
SET category = $2, name = $3, role = $4, achievement = $5
WHERE id = $1
RETURNING id, student_id, academic_year_id, category, name, role, achievement, created_at
`

type UpdateStudentActivityParams struct {
	ID          uuid.UUID   `json:"id"`
	Category    string      `json:"category"`
	Name        string      `json:"name"`
	Role        pgtype.Text `json:"role"`
	Achievement pgtype.Text `json:"achievement"`
}

func (q *Queries) UpdateStudentActivity(ctx context.Context, arg UpdateStudentActivityParams) (StudentActivity, error) {
	row := q.db.QueryRow(ctx, updateStudentActivity,
		arg.ID,
		arg.Category,
		arg.Name,
		arg.Role,
		arg.Achievement,
	)
	var i StudentActivity
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.AcademicYearID,
		&i.Category,
		&i.Name,
		&i.Role,
		&i.Achievement,
		&i.CreatedAt,
	)
	return i, err
}
