// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (name, code, type)
VALUES ($1, $2, $3)
RETURNING id, name, code, created_at, type
`

type CreateSubjectParams struct {
	Name string      `json:"name"`
	Code string      `json:"code"`
	Type pgtype.Text `json:"type"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.Name, arg.Code, arg.Type)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.Type,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :execrows
DELETE FROM subjects AS s
WHERE s.id = $1
AND s.id NOT IN (
    SELECT DISTINCT subject_id FROM group_subjects
    UNION
    SELECT DISTINCT subject_id FROM class_subject_teachers
    UNION
    SELECT DISTINCT subject_id FROM student_subject_enrollments
)
`

func (q *Queries) DeleteSubject(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubjectByCode = `-- name: GetSubjectByCode :one
SELECT id, name, code, created_at, type FROM subjects
WHERE code = $1
`

func (q *Queries) GetSubjectByCode(ctx context.Context, code string) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByCode, code)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.Type,
	)
	return i, err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, name, code, created_at, type FROM subjects
WHERE id = $1
`

func (q *Queries) GetSubjectByID(ctx context.Context, id uuid.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.Type,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name, code, created_at, type FROM subjects
ORDER BY name ASC
`

func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects
SET
    name = $2,
    code = $3,
    type = $4
WHERE id = $1
RETURNING id, name, code, created_at, type
`

type UpdateSubjectParams struct {
	ID   uuid.UUID   `json:"id"`
	Name string      `json:"name"`
	Code string      `json:"code"`
	Type pgtype.Text `json:"type"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Type,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.Type,
	)
	return i, err
}
