// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teachers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignSubjectToTeacher = `-- name: AssignSubjectToTeacher :exec
INSERT INTO teacher_subjects (teacher_id, subject_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignSubjectToTeacherParams struct {
	TeacherID uuid.UUID `json:"teacher_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

func (q *Queries) AssignSubjectToTeacher(ctx context.Context, arg AssignSubjectToTeacherParams) error {
	_, err := q.db.Exec(ctx, assignSubjectToTeacher, arg.TeacherID, arg.SubjectID)
	return err
}

const createTeacherProfile = `-- name: CreateTeacherProfile :one
INSERT INTO teacher_profiles (
    user_id,
    full_name,
    employee_number,
    joined_date,
    phone
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, full_name, employee_number, joined_date, phone, created_at, updated_at
`

type CreateTeacherProfileParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	FullName       string      `json:"full_name"`
	EmployeeNumber string      `json:"employee_number"`
	JoinedDate     pgtype.Date `json:"joined_date"`
	Phone          pgtype.Text `json:"phone"`
}

func (q *Queries) CreateTeacherProfile(ctx context.Context, arg CreateTeacherProfileParams) (TeacherProfile, error) {
	row := q.db.QueryRow(ctx, createTeacherProfile,
		arg.UserID,
		arg.FullName,
		arg.EmployeeNumber,
		arg.JoinedDate,
		arg.Phone,
	)
	var i TeacherProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.EmployeeNumber,
		&i.JoinedDate,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeacher = `-- name: DeleteTeacher :exec
DELETE FROM teacher_profiles
WHERE id = $1
`

func (q *Queries) DeleteTeacher(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeacher, id)
	return err
}

const getFormTeacherClass = `-- name: GetFormTeacherClass :one
SELECT
    c.id, c.grade_id, c.academic_year_id, c.form_teacher_id, c.stream_id, c.stream_group_id, c.name, c.created_at
FROM classes c
WHERE c.form_teacher_id = $1
  AND c.academic_year_id = (
      SELECT id FROM academic_years WHERE is_current = TRUE LIMIT 1
  )
`

func (q *Queries) GetFormTeacherClass(ctx context.Context, formTeacherID pgtype.UUID) (Class, error) {
	row := q.db.QueryRow(ctx, getFormTeacherClass, formTeacherID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.GradeID,
		&i.AcademicYearID,
		&i.FormTeacherID,
		&i.StreamID,
		&i.StreamGroupID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTeacherByEmployeeNumber = `-- name: GetTeacherByEmployeeNumber :one
SELECT id, user_id, full_name, employee_number, joined_date, phone, created_at, updated_at FROM teacher_profiles
WHERE employee_number = $1
`

func (q *Queries) GetTeacherByEmployeeNumber(ctx context.Context, employeeNumber string) (TeacherProfile, error) {
	row := q.db.QueryRow(ctx, getTeacherByEmployeeNumber, employeeNumber)
	var i TeacherProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.EmployeeNumber,
		&i.JoinedDate,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeacherByID = `-- name: GetTeacherByID :one
SELECT id, user_id, full_name, employee_number, joined_date, phone, created_at, updated_at FROM teacher_profiles
WHERE id = $1
`

func (q *Queries) GetTeacherByID(ctx context.Context, id uuid.UUID) (TeacherProfile, error) {
	row := q.db.QueryRow(ctx, getTeacherByID, id)
	var i TeacherProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.EmployeeNumber,
		&i.JoinedDate,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeacherByUserID = `-- name: GetTeacherByUserID :one
SELECT id, user_id, full_name, employee_number, joined_date, phone, created_at, updated_at FROM teacher_profiles
WHERE user_id = $1
`

func (q *Queries) GetTeacherByUserID(ctx context.Context, userID uuid.UUID) (TeacherProfile, error) {
	row := q.db.QueryRow(ctx, getTeacherByUserID, userID)
	var i TeacherProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.EmployeeNumber,
		&i.JoinedDate,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjectsByTeacher = `-- name: ListSubjectsByTeacher :many
SELECT
    s.id, s.name, s.code, s.created_at
FROM subjects s
INNER JOIN teacher_subjects ts ON ts.subject_id = s.id
WHERE ts.teacher_id = $1
ORDER BY s.name ASC
`

func (q *Queries) ListSubjectsByTeacher(ctx context.Context, teacherID uuid.UUID) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachers = `-- name: ListTeachers :many
SELECT id, user_id, full_name, employee_number, joined_date, phone, created_at, updated_at FROM teacher_profiles
ORDER BY full_name ASC
`

func (q *Queries) ListTeachers(ctx context.Context) ([]TeacherProfile, error) {
	rows, err := q.db.Query(ctx, listTeachers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherProfile{}
	for rows.Next() {
		var i TeacherProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.EmployeeNumber,
			&i.JoinedDate,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersBySubject = `-- name: ListTeachersBySubject :many
SELECT
    tp.id, tp.user_id, tp.full_name, tp.employee_number, tp.joined_date, tp.phone, tp.created_at, tp.updated_at
FROM teacher_profiles tp
INNER JOIN teacher_subjects ts ON ts.teacher_id = tp.id
WHERE ts.subject_id = $1
ORDER BY tp.full_name ASC
`

func (q *Queries) ListTeachersBySubject(ctx context.Context, subjectID uuid.UUID) ([]TeacherProfile, error) {
	rows, err := q.db.Query(ctx, listTeachersBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherProfile{}
	for rows.Next() {
		var i TeacherProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.EmployeeNumber,
			&i.JoinedDate,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSubjectFromTeacher = `-- name: RemoveSubjectFromTeacher :exec
DELETE FROM teacher_subjects
WHERE teacher_id = $1 AND subject_id = $2
`

type RemoveSubjectFromTeacherParams struct {
	TeacherID uuid.UUID `json:"teacher_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

func (q *Queries) RemoveSubjectFromTeacher(ctx context.Context, arg RemoveSubjectFromTeacherParams) error {
	_, err := q.db.Exec(ctx, removeSubjectFromTeacher, arg.TeacherID, arg.SubjectID)
	return err
}

const updateTeacherProfile = `-- name: UpdateTeacherProfile :one
UPDATE teacher_profiles
SET
    full_name       = $2,
    employee_number = $3,
    phone           = $4,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, user_id, full_name, employee_number, joined_date, phone, created_at, updated_at
`

type UpdateTeacherProfileParams struct {
	ID             uuid.UUID   `json:"id"`
	FullName       string      `json:"full_name"`
	EmployeeNumber string      `json:"employee_number"`
	Phone          pgtype.Text `json:"phone"`
}

func (q *Queries) UpdateTeacherProfile(ctx context.Context, arg UpdateTeacherProfileParams) (TeacherProfile, error) {
	row := q.db.QueryRow(ctx, updateTeacherProfile,
		arg.ID,
		arg.FullName,
		arg.EmployeeNumber,
		arg.Phone,
	)
	var i TeacherProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.EmployeeNumber,
		&i.JoinedDate,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
