// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: term_marks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTermMark = `-- name: DeleteTermMark :exec
DELETE FROM term_marks
WHERE id = $1
`

func (q *Queries) DeleteTermMark(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTermMark, id)
	return err
}

const listClassMarksForTermSubject = `-- name: ListClassMarksForTermSubject :many
SELECT
    sp.id          AS student_id,
    sp.full_name   AS student_name,
    sp.index_number,
    tm.id          AS term_mark_id,
    tm.marks,
    tm.max_marks
FROM student_profiles sp
INNER JOIN class_students cs ON cs.student_id = sp.id
LEFT JOIN term_marks tm
    ON tm.student_id = sp.id
   AND tm.term_id = $2
   AND tm.subject_id = $3
WHERE cs.class_id = $1
ORDER BY sp.full_name ASC
`

type ListClassMarksForTermSubjectParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	TermID    uuid.UUID `json:"term_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type ListClassMarksForTermSubjectRow struct {
	StudentID   uuid.UUID      `json:"student_id"`
	StudentName string         `json:"student_name"`
	IndexNumber string         `json:"index_number"`
	TermMarkID  pgtype.UUID    `json:"term_mark_id"`
	Marks       pgtype.Numeric `json:"marks"`
	MaxMarks    pgtype.Numeric `json:"max_marks"`
}

// Every student in the class, with their mark for this term+subject if one
// has been entered yet (NULL columns otherwise) — powers the marks-entry
// grid, which needs to show blanks for students not yet marked.
func (q *Queries) ListClassMarksForTermSubject(ctx context.Context, arg ListClassMarksForTermSubjectParams) ([]ListClassMarksForTermSubjectRow, error) {
	rows, err := q.db.Query(ctx, listClassMarksForTermSubject, arg.ClassID, arg.TermID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassMarksForTermSubjectRow{}
	for rows.Next() {
		var i ListClassMarksForTermSubjectRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.IndexNumber,
			&i.TermMarkID,
			&i.Marks,
			&i.MaxMarks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentMarksByTerm = `-- name: ListStudentMarksByTerm :many
SELECT
    tm.id,
    tm.marks,
    tm.max_marks,
    s.id         AS subject_id,
    s.name       AS subject_name,
    s.code       AS subject_code,
    tp.id        AS teacher_id,
    tp.full_name AS teacher_name
FROM term_marks tm
INNER JOIN subjects s ON s.id = tm.subject_id
INNER JOIN terms t ON t.id = tm.term_id
LEFT JOIN class_students cs
    ON cs.student_id = tm.student_id
LEFT JOIN classes c
    ON c.id = cs.class_id AND c.academic_year_id = t.academic_year_id
LEFT JOIN class_subject_teachers cst
    ON cst.class_id = c.id AND cst.subject_id = tm.subject_id
LEFT JOIN teacher_profiles tp ON tp.id = cst.teacher_id
WHERE tm.student_id = $1
  AND tm.term_id = $2
ORDER BY s.name ASC
`

type ListStudentMarksByTermParams struct {
	StudentID uuid.UUID `json:"student_id"`
	TermID    uuid.UUID `json:"term_id"`
}

type ListStudentMarksByTermRow struct {
	ID          uuid.UUID      `json:"id"`
	Marks       pgtype.Numeric `json:"marks"`
	MaxMarks    pgtype.Numeric `json:"max_marks"`
	SubjectID   uuid.UUID      `json:"subject_id"`
	SubjectName string         `json:"subject_name"`
	SubjectCode string         `json:"subject_code"`
	TeacherID   pgtype.UUID    `json:"teacher_id"`
	TeacherName pgtype.Text    `json:"teacher_name"`
}

// teacher_id/teacher_name are NULL if the student's current-year class has
// no assigned teacher for that subject (or the student has no current class)
func (q *Queries) ListStudentMarksByTerm(ctx context.Context, arg ListStudentMarksByTermParams) ([]ListStudentMarksByTermRow, error) {
	rows, err := q.db.Query(ctx, listStudentMarksByTerm, arg.StudentID, arg.TermID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentMarksByTermRow{}
	for rows.Next() {
		var i ListStudentMarksByTermRow
		if err := rows.Scan(
			&i.ID,
			&i.Marks,
			&i.MaxMarks,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectCode,
			&i.TeacherID,
			&i.TeacherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTermMark = `-- name: UpsertTermMark :one
INSERT INTO term_marks (
    student_id,
    subject_id,
    term_id,
    marks,
    max_marks,
    entered_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (student_id, subject_id, term_id)
DO UPDATE SET
    marks      = EXCLUDED.marks,
    max_marks  = EXCLUDED.max_marks,
    entered_by = EXCLUDED.entered_by,
    updated_at = NOW()
RETURNING id, student_id, subject_id, term_id, marks, max_marks, entered_by, created_at, updated_at
`

type UpsertTermMarkParams struct {
	StudentID uuid.UUID      `json:"student_id"`
	SubjectID uuid.UUID      `json:"subject_id"`
	TermID    uuid.UUID      `json:"term_id"`
	Marks     pgtype.Numeric `json:"marks"`
	MaxMarks  pgtype.Numeric `json:"max_marks"`
	EnteredBy pgtype.UUID    `json:"entered_by"`
}

func (q *Queries) UpsertTermMark(ctx context.Context, arg UpsertTermMarkParams) (TermMark, error) {
	row := q.db.QueryRow(ctx, upsertTermMark,
		arg.StudentID,
		arg.SubjectID,
		arg.TermID,
		arg.Marks,
		arg.MaxMarks,
		arg.EnteredBy,
	)
	var i TermMark
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SubjectID,
		&i.TermID,
		&i.Marks,
		&i.MaxMarks,
		&i.EnteredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
