// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terms.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTerm = `-- name: CreateTerm :one
INSERT INTO terms (
    academic_year_id,
    name,
    start_date,
    end_date,
    sort_order
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, academic_year_id, name, start_date, end_date, is_current, sort_order, created_at
`

type CreateTermParams struct {
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	Name           string      `json:"name"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	SortOrder      int32       `json:"sort_order"`
}

func (q *Queries) CreateTerm(ctx context.Context, arg CreateTermParams) (Term, error) {
	row := q.db.QueryRow(ctx, createTerm,
		arg.AcademicYearID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.SortOrder,
	)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTerm = `-- name: DeleteTerm :execrows
DELETE FROM terms AS t
WHERE t.id = $1
AND t.id NOT IN (
    SELECT DISTINCT term_id FROM term_marks
)
`

func (q *Queries) DeleteTerm(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTerm, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCurrentTerm = `-- name: GetCurrentTerm :one
SELECT id, academic_year_id, name, start_date, end_date, is_current, sort_order, created_at FROM terms
WHERE is_current = TRUE
LIMIT 1
`

func (q *Queries) GetCurrentTerm(ctx context.Context) (Term, error) {
	row := q.db.QueryRow(ctx, getCurrentTerm)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getTermByID = `-- name: GetTermByID :one
SELECT id, academic_year_id, name, start_date, end_date, is_current, sort_order, created_at FROM terms
WHERE id = $1
`

func (q *Queries) GetTermByID(ctx context.Context, id uuid.UUID) (Term, error) {
	row := q.db.QueryRow(ctx, getTermByID, id)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listTermsByAcademicYear = `-- name: ListTermsByAcademicYear :many
SELECT id, academic_year_id, name, start_date, end_date, is_current, sort_order, created_at FROM terms
WHERE academic_year_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListTermsByAcademicYear(ctx context.Context, academicYearID uuid.UUID) ([]Term, error) {
	rows, err := q.db.Query(ctx, listTermsByAcademicYear, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Term{}
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.AcademicYearID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrent,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentTerm = `-- name: SetCurrentTerm :exec
UPDATE terms
SET is_current = (id = $1)
WHERE id = $1 OR is_current = true
`

func (q *Queries) SetCurrentTerm(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setCurrentTerm, id)
	return err
}

const updateTerm = `-- name: UpdateTerm :one
UPDATE terms
SET
    name       = $2,
    start_date = $3,
    end_date   = $4,
    sort_order = $5
WHERE id = $1
RETURNING id, academic_year_id, name, start_date, end_date, is_current, sort_order, created_at
`

type UpdateTermParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateTerm(ctx context.Context, arg UpdateTermParams) (Term, error) {
	row := q.db.QueryRow(ctx, updateTerm,
		arg.ID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.SortOrder,
	)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
