// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable_option_blocks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addOptionBlockClass = `-- name: AddOptionBlockClass :exec
INSERT INTO timetable_option_block_classes (block_id, class_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddOptionBlockClassParams struct {
	BlockID uuid.UUID `json:"block_id"`
	ClassID uuid.UUID `json:"class_id"`
}

func (q *Queries) AddOptionBlockClass(ctx context.Context, arg AddOptionBlockClassParams) error {
	_, err := q.db.Exec(ctx, addOptionBlockClass, arg.BlockID, arg.ClassID)
	return err
}

const addOptionBlockSubject = `-- name: AddOptionBlockSubject :exec
INSERT INTO timetable_option_block_subjects (block_id, subject_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddOptionBlockSubjectParams struct {
	BlockID   uuid.UUID `json:"block_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

func (q *Queries) AddOptionBlockSubject(ctx context.Context, arg AddOptionBlockSubjectParams) error {
	_, err := q.db.Exec(ctx, addOptionBlockSubject, arg.BlockID, arg.SubjectID)
	return err
}

const createOptionBlock = `-- name: CreateOptionBlock :one
INSERT INTO timetable_option_blocks (academic_year_id, grade_id, name, periods_per_week)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateOptionBlockParams struct {
	AcademicYearID uuid.UUID `json:"academic_year_id"`
	GradeID        uuid.UUID `json:"grade_id"`
	Name           string    `json:"name"`
	PeriodsPerWeek int32     `json:"periods_per_week"`
}

func (q *Queries) CreateOptionBlock(ctx context.Context, arg CreateOptionBlockParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOptionBlock,
		arg.AcademicYearID,
		arg.GradeID,
		arg.Name,
		arg.PeriodsPerWeek,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOptionBlocks = `-- name: DeleteOptionBlocks :exec
DELETE FROM timetable_option_blocks WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteOptionBlocks(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOptionBlocks, ids)
	return err
}

const listOptionBlockClasses = `-- name: ListOptionBlockClasses :many
SELECT bc.block_id, bc.class_id FROM timetable_option_block_classes bc
WHERE bc.block_id = ANY($1::uuid[])
`

func (q *Queries) ListOptionBlockClasses(ctx context.Context, blockIds []uuid.UUID) ([]TimetableOptionBlockClass, error) {
	rows, err := q.db.Query(ctx, listOptionBlockClasses, blockIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimetableOptionBlockClass{}
	for rows.Next() {
		var i TimetableOptionBlockClass
		if err := rows.Scan(&i.BlockID, &i.ClassID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionBlockSubjects = `-- name: ListOptionBlockSubjects :many
SELECT bs.block_id, bs.subject_id, s.name AS subject_name
FROM timetable_option_block_subjects bs
INNER JOIN subjects s ON s.id = bs.subject_id
WHERE bs.block_id = ANY($1::uuid[])
ORDER BY s.name
`

type ListOptionBlockSubjectsRow struct {
	BlockID     uuid.UUID `json:"block_id"`
	SubjectID   uuid.UUID `json:"subject_id"`
	SubjectName string    `json:"subject_name"`
}

func (q *Queries) ListOptionBlockSubjects(ctx context.Context, blockIds []uuid.UUID) ([]ListOptionBlockSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listOptionBlockSubjects, blockIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOptionBlockSubjectsRow{}
	for rows.Next() {
		var i ListOptionBlockSubjectsRow
		if err := rows.Scan(&i.BlockID, &i.SubjectID, &i.SubjectName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionBlockTeachersForClass = `-- name: ListOptionBlockTeachersForClass :many
SELECT DISTINCT cst.teacher_id, tp.full_name AS teacher_name
FROM timetable_option_block_subjects bs
INNER JOIN class_subject_teachers cst ON cst.subject_id = bs.subject_id AND cst.class_id = $1::uuid
INNER JOIN teacher_profiles tp ON tp.id = cst.teacher_id
WHERE bs.block_id = $2::uuid
`

type ListOptionBlockTeachersForClassParams struct {
	ClassID uuid.UUID `json:"class_id"`
	BlockID uuid.UUID `json:"block_id"`
}

type ListOptionBlockTeachersForClassRow struct {
	TeacherID   uuid.UUID `json:"teacher_id"`
	TeacherName string    `json:"teacher_name"`
}

// the teachers a class's students go to in one option block period
func (q *Queries) ListOptionBlockTeachersForClass(ctx context.Context, arg ListOptionBlockTeachersForClassParams) ([]ListOptionBlockTeachersForClassRow, error) {
	rows, err := q.db.Query(ctx, listOptionBlockTeachersForClass, arg.ClassID, arg.BlockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOptionBlockTeachersForClassRow{}
	for rows.Next() {
		var i ListOptionBlockTeachersForClassRow
		if err := rows.Scan(&i.TeacherID, &i.TeacherName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionBlocksForClasses = `-- name: ListOptionBlocksForClasses :many
SELECT DISTINCT b.id, b.grade_id, b.name, b.periods_per_week
FROM timetable_option_blocks b
INNER JOIN timetable_option_block_classes bc ON bc.block_id = b.id
WHERE bc.class_id = ANY($1::uuid[])
ORDER BY b.name, b.id
`

type ListOptionBlocksForClassesRow struct {
	ID             uuid.UUID `json:"id"`
	GradeID        uuid.UUID `json:"grade_id"`
	Name           string    `json:"name"`
	PeriodsPerWeek int32     `json:"periods_per_week"`
}

// every option block that includes at least one of these classes
func (q *Queries) ListOptionBlocksForClasses(ctx context.Context, classIds []uuid.UUID) ([]ListOptionBlocksForClassesRow, error) {
	rows, err := q.db.Query(ctx, listOptionBlocksForClasses, classIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOptionBlocksForClassesRow{}
	for rows.Next() {
		var i ListOptionBlocksForClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.GradeID,
			&i.Name,
			&i.PeriodsPerWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionBlocksForYear = `-- name: ListOptionBlocksForYear :many
SELECT id, grade_id, name, periods_per_week FROM timetable_option_blocks
WHERE academic_year_id = $1
ORDER BY name, id
`

type ListOptionBlocksForYearRow struct {
	ID             uuid.UUID `json:"id"`
	GradeID        uuid.UUID `json:"grade_id"`
	Name           string    `json:"name"`
	PeriodsPerWeek int32     `json:"periods_per_week"`
}

func (q *Queries) ListOptionBlocksForYear(ctx context.Context, academicYearID uuid.UUID) ([]ListOptionBlocksForYearRow, error) {
	rows, err := q.db.Query(ctx, listOptionBlocksForYear, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOptionBlocksForYearRow{}
	for rows.Next() {
		var i ListOptionBlocksForYearRow
		if err := rows.Scan(
			&i.ID,
			&i.GradeID,
			&i.Name,
			&i.PeriodsPerWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const optionBlocksInSubmittedTimetables = `-- name: OptionBlocksInSubmittedTimetables :one
SELECT EXISTS (
    SELECT 1 FROM timetable_entries te
    INNER JOIN timetables t ON t.id = te.timetable_id
    WHERE te.option_block_id = ANY($1::uuid[]) AND t.status <> 'draft'
)::bool AS in_use
`

// a block already used by a timetable past draft cannot be replaced
func (q *Queries) OptionBlocksInSubmittedTimetables(ctx context.Context, ids []uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, optionBlocksInSubmittedTimetables, ids)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}
