// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTimetableSettingsByYear = `-- name: GetTimetableSettingsByYear :one
SELECT id, academic_year_id, school_start_time, school_end_time, number_of_periods, period_duration_minutes, interval_duration_minutes, created_at, updated_at FROM timetable_settings
WHERE academic_year_id = $1
`

func (q *Queries) GetTimetableSettingsByYear(ctx context.Context, academicYearID uuid.UUID) (TimetableSetting, error) {
	row := q.db.QueryRow(ctx, getTimetableSettingsByYear, academicYearID)
	var i TimetableSetting
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.SchoolStartTime,
		&i.SchoolEndTime,
		&i.NumberOfPeriods,
		&i.PeriodDurationMinutes,
		&i.IntervalDurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTimetableSettings = `-- name: UpsertTimetableSettings :one
INSERT INTO timetable_settings (
    academic_year_id, school_start_time, school_end_time, number_of_periods,
    period_duration_minutes, interval_duration_minutes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (academic_year_id) DO UPDATE
SET
    school_start_time         = EXCLUDED.school_start_time,
    school_end_time           = EXCLUDED.school_end_time,
    number_of_periods         = EXCLUDED.number_of_periods,
    period_duration_minutes   = EXCLUDED.period_duration_minutes,
    interval_duration_minutes = EXCLUDED.interval_duration_minutes,
    updated_at                = NOW()
RETURNING id, academic_year_id, school_start_time, school_end_time, number_of_periods, period_duration_minutes, interval_duration_minutes, created_at, updated_at
`

type UpsertTimetableSettingsParams struct {
	AcademicYearID          uuid.UUID   `json:"academic_year_id"`
	SchoolStartTime         pgtype.Time `json:"school_start_time"`
	SchoolEndTime           pgtype.Time `json:"school_end_time"`
	NumberOfPeriods         int32       `json:"number_of_periods"`
	PeriodDurationMinutes   int32       `json:"period_duration_minutes"`
	IntervalDurationMinutes int32       `json:"interval_duration_minutes"`
}

func (q *Queries) UpsertTimetableSettings(ctx context.Context, arg UpsertTimetableSettingsParams) (TimetableSetting, error) {
	row := q.db.QueryRow(ctx, upsertTimetableSettings,
		arg.AcademicYearID,
		arg.SchoolStartTime,
		arg.SchoolEndTime,
		arg.NumberOfPeriods,
		arg.PeriodDurationMinutes,
		arg.IntervalDurationMinutes,
	)
	var i TimetableSetting
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.SchoolStartTime,
		&i.SchoolEndTime,
		&i.NumberOfPeriods,
		&i.PeriodDurationMinutes,
		&i.IntervalDurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
