// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable_status_history.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTimetableStatusHistory = `-- name: CreateTimetableStatusHistory :one
INSERT INTO timetable_status_history (timetable_id, from_status, to_status, changed_by, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, timetable_id, from_status, to_status, changed_by, comment, changed_at
`

type CreateTimetableStatusHistoryParams struct {
	TimetableID uuid.UUID   `json:"timetable_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	ChangedBy   uuid.UUID   `json:"changed_by"`
	Comment     pgtype.Text `json:"comment"`
}

func (q *Queries) CreateTimetableStatusHistory(ctx context.Context, arg CreateTimetableStatusHistoryParams) (TimetableStatusHistory, error) {
	row := q.db.QueryRow(ctx, createTimetableStatusHistory,
		arg.TimetableID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.Comment,
	)
	var i TimetableStatusHistory
	err := row.Scan(
		&i.ID,
		&i.TimetableID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ChangedBy,
		&i.Comment,
		&i.ChangedAt,
	)
	return i, err
}

const listTimetableStatusHistory = `-- name: ListTimetableStatusHistory :many
SELECT
    h.id, h.timetable_id, h.from_status, h.to_status, h.changed_by, h.comment, h.changed_at,
    u.full_name AS changed_by_name
FROM timetable_status_history h
INNER JOIN users u ON u.id = h.changed_by
WHERE h.timetable_id = $1
ORDER BY h.changed_at ASC
`

type ListTimetableStatusHistoryRow struct {
	ID            uuid.UUID          `json:"id"`
	TimetableID   uuid.UUID          `json:"timetable_id"`
	FromStatus    pgtype.Text        `json:"from_status"`
	ToStatus      string             `json:"to_status"`
	ChangedBy     uuid.UUID          `json:"changed_by"`
	Comment       pgtype.Text        `json:"comment"`
	ChangedAt     pgtype.Timestamptz `json:"changed_at"`
	ChangedByName string             `json:"changed_by_name"`
}

func (q *Queries) ListTimetableStatusHistory(ctx context.Context, timetableID uuid.UUID) ([]ListTimetableStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, listTimetableStatusHistory, timetableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimetableStatusHistoryRow{}
	for rows.Next() {
		var i ListTimetableStatusHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.TimetableID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.Comment,
			&i.ChangedAt,
			&i.ChangedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
