// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable_entries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const copyTimetableEntries = `-- name: CopyTimetableEntries :exec
INSERT INTO timetable_entries (timetable_id, day_of_week, period_number, subject_id, teacher_id, classroom_id)
SELECT $2, src.day_of_week, src.period_number, src.subject_id, src.teacher_id, src.classroom_id
FROM timetable_entries src
WHERE src.timetable_id = $1
`

type CopyTimetableEntriesParams struct {
	TimetableID   uuid.UUID `json:"timetable_id"`
	TimetableID_2 uuid.UUID `json:"timetable_id_2"`
}

func (q *Queries) CopyTimetableEntries(ctx context.Context, arg CopyTimetableEntriesParams) error {
	_, err := q.db.Exec(ctx, copyTimetableEntries, arg.TimetableID, arg.TimetableID_2)
	return err
}

const countEntriesBySubjectForTimetable = `-- name: CountEntriesBySubjectForTimetable :many
SELECT subject_id, COUNT(*)::int AS entry_count
FROM timetable_entries
WHERE timetable_id = $1 AND subject_id IS NOT NULL
GROUP BY subject_id
`

type CountEntriesBySubjectForTimetableRow struct {
	SubjectID  pgtype.UUID `json:"subject_id"`
	EntryCount int32       `json:"entry_count"`
}

func (q *Queries) CountEntriesBySubjectForTimetable(ctx context.Context, timetableID uuid.UUID) ([]CountEntriesBySubjectForTimetableRow, error) {
	rows, err := q.db.Query(ctx, countEntriesBySubjectForTimetable, timetableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEntriesBySubjectForTimetableRow{}
	for rows.Next() {
		var i CountEntriesBySubjectForTimetableRow
		if err := rows.Scan(&i.SubjectID, &i.EntryCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTimetableEntry = `-- name: DeleteTimetableEntry :exec
DELETE FROM timetable_entries
WHERE timetable_id = $1 AND day_of_week = $2 AND period_number = $3
`

type DeleteTimetableEntryParams struct {
	TimetableID  uuid.UUID `json:"timetable_id"`
	DayOfWeek    int16     `json:"day_of_week"`
	PeriodNumber int16     `json:"period_number"`
}

func (q *Queries) DeleteTimetableEntry(ctx context.Context, arg DeleteTimetableEntryParams) error {
	_, err := q.db.Exec(ctx, deleteTimetableEntry, arg.TimetableID, arg.DayOfWeek, arg.PeriodNumber)
	return err
}

const isTeacherAssignedToSubject = `-- name: IsTeacherAssignedToSubject :one
SELECT EXISTS (
    SELECT 1 FROM teacher_subjects WHERE teacher_id = $1 AND subject_id = $2
) AS assigned
`

type IsTeacherAssignedToSubjectParams struct {
	TeacherID uuid.UUID `json:"teacher_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

func (q *Queries) IsTeacherAssignedToSubject(ctx context.Context, arg IsTeacherAssignedToSubjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeacherAssignedToSubject, arg.TeacherID, arg.SubjectID)
	var assigned bool
	err := row.Scan(&assigned)
	return assigned, err
}

const listEntriesForYearExcludingTimetable = `-- name: ListEntriesForYearExcludingTimetable :many
SELECT te.day_of_week, te.period_number, te.teacher_id, te.classroom_id, t.id AS timetable_id, t.class_id, c.name AS class_name
FROM timetable_entries te
INNER JOIN timetables t ON t.id = te.timetable_id
INNER JOIN classes c    ON c.id = t.class_id
WHERE t.academic_year_id = $1
  AND t.id != $2
  AND t.status IN ('draft', 'under_review', 'approved', 'published')
  AND (te.teacher_id IS NOT NULL OR te.classroom_id IS NOT NULL)
`

type ListEntriesForYearExcludingTimetableParams struct {
	AcademicYearID uuid.UUID `json:"academic_year_id"`
	ID             uuid.UUID `json:"id"`
}

type ListEntriesForYearExcludingTimetableRow struct {
	DayOfWeek    int16       `json:"day_of_week"`
	PeriodNumber int16       `json:"period_number"`
	TeacherID    pgtype.UUID `json:"teacher_id"`
	ClassroomID  pgtype.UUID `json:"classroom_id"`
	TimetableID  uuid.UUID   `json:"timetable_id"`
	ClassID      uuid.UUID   `json:"class_id"`
	ClassName    string      `json:"class_name"`
}

// every booked (teacher or classroom) cell across other timetables in the
// same academic year, used for cross-timetable clash detection
func (q *Queries) ListEntriesForYearExcludingTimetable(ctx context.Context, arg ListEntriesForYearExcludingTimetableParams) ([]ListEntriesForYearExcludingTimetableRow, error) {
	rows, err := q.db.Query(ctx, listEntriesForYearExcludingTimetable, arg.AcademicYearID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesForYearExcludingTimetableRow{}
	for rows.Next() {
		var i ListEntriesForYearExcludingTimetableRow
		if err := rows.Scan(
			&i.DayOfWeek,
			&i.PeriodNumber,
			&i.TeacherID,
			&i.ClassroomID,
			&i.TimetableID,
			&i.ClassID,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherScheduleForYear = `-- name: ListTeacherScheduleForYear :many
SELECT
    te.day_of_week, te.period_number,
    te.subject_id, s.name AS subject_name,
    te.classroom_id, cr.name AS classroom_name,
    t.class_id, c.name AS class_name, g.name AS grade_name
FROM timetable_entries te
INNER JOIN timetables t ON t.id = te.timetable_id
INNER JOIN classes c    ON c.id = t.class_id
INNER JOIN grades g     ON g.id = c.grade_id
LEFT JOIN subjects s    ON s.id = te.subject_id
LEFT JOIN classrooms cr ON cr.id = te.classroom_id
WHERE te.teacher_id = $1 AND t.academic_year_id = $2 AND t.status = 'published'
ORDER BY te.day_of_week ASC, te.period_number ASC
`

type ListTeacherScheduleForYearParams struct {
	TeacherID      pgtype.UUID `json:"teacher_id"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
}

type ListTeacherScheduleForYearRow struct {
	DayOfWeek     int16       `json:"day_of_week"`
	PeriodNumber  int16       `json:"period_number"`
	SubjectID     pgtype.UUID `json:"subject_id"`
	SubjectName   pgtype.Text `json:"subject_name"`
	ClassroomID   pgtype.UUID `json:"classroom_id"`
	ClassroomName pgtype.Text `json:"classroom_name"`
	ClassID       uuid.UUID   `json:"class_id"`
	ClassName     string      `json:"class_name"`
	GradeName     string      `json:"grade_name"`
}

// a teacher's full weekly schedule across every published timetable, for
// the teacher's own "My Timetable" view
func (q *Queries) ListTeacherScheduleForYear(ctx context.Context, arg ListTeacherScheduleForYearParams) ([]ListTeacherScheduleForYearRow, error) {
	rows, err := q.db.Query(ctx, listTeacherScheduleForYear, arg.TeacherID, arg.AcademicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeacherScheduleForYearRow{}
	for rows.Next() {
		var i ListTeacherScheduleForYearRow
		if err := rows.Scan(
			&i.DayOfWeek,
			&i.PeriodNumber,
			&i.SubjectID,
			&i.SubjectName,
			&i.ClassroomID,
			&i.ClassroomName,
			&i.ClassID,
			&i.ClassName,
			&i.GradeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimetableEntriesByTimetable = `-- name: ListTimetableEntriesByTimetable :many
SELECT
    te.id, te.timetable_id, te.day_of_week, te.period_number, te.subject_id, te.teacher_id, te.classroom_id, te.created_at, te.updated_at,
    s.name       AS subject_name,
    tp.full_name AS teacher_name,
    cr.name      AS classroom_name
FROM timetable_entries te
LEFT JOIN subjects         s  ON s.id  = te.subject_id
LEFT JOIN teacher_profiles tp ON tp.id = te.teacher_id
LEFT JOIN classrooms       cr ON cr.id = te.classroom_id
WHERE te.timetable_id = $1
ORDER BY te.day_of_week ASC, te.period_number ASC
`

type ListTimetableEntriesByTimetableRow struct {
	ID            uuid.UUID          `json:"id"`
	TimetableID   uuid.UUID          `json:"timetable_id"`
	DayOfWeek     int16              `json:"day_of_week"`
	PeriodNumber  int16              `json:"period_number"`
	SubjectID     pgtype.UUID        `json:"subject_id"`
	TeacherID     pgtype.UUID        `json:"teacher_id"`
	ClassroomID   pgtype.UUID        `json:"classroom_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	SubjectName   pgtype.Text        `json:"subject_name"`
	TeacherName   pgtype.Text        `json:"teacher_name"`
	ClassroomName pgtype.Text        `json:"classroom_name"`
}

func (q *Queries) ListTimetableEntriesByTimetable(ctx context.Context, timetableID uuid.UUID) ([]ListTimetableEntriesByTimetableRow, error) {
	rows, err := q.db.Query(ctx, listTimetableEntriesByTimetable, timetableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimetableEntriesByTimetableRow{}
	for rows.Next() {
		var i ListTimetableEntriesByTimetableRow
		if err := rows.Scan(
			&i.ID,
			&i.TimetableID,
			&i.DayOfWeek,
			&i.PeriodNumber,
			&i.SubjectID,
			&i.TeacherID,
			&i.ClassroomID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubjectName,
			&i.TeacherName,
			&i.ClassroomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTimetableEntry = `-- name: UpsertTimetableEntry :one
INSERT INTO timetable_entries (timetable_id, day_of_week, period_number, subject_id, teacher_id, classroom_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (timetable_id, day_of_week, period_number) DO UPDATE
SET subject_id = EXCLUDED.subject_id,
    teacher_id = EXCLUDED.teacher_id,
    classroom_id = EXCLUDED.classroom_id,
    updated_at = NOW()
RETURNING id, timetable_id, day_of_week, period_number, subject_id, teacher_id, classroom_id, created_at, updated_at
`

type UpsertTimetableEntryParams struct {
	TimetableID  uuid.UUID   `json:"timetable_id"`
	DayOfWeek    int16       `json:"day_of_week"`
	PeriodNumber int16       `json:"period_number"`
	SubjectID    pgtype.UUID `json:"subject_id"`
	TeacherID    pgtype.UUID `json:"teacher_id"`
	ClassroomID  pgtype.UUID `json:"classroom_id"`
}

func (q *Queries) UpsertTimetableEntry(ctx context.Context, arg UpsertTimetableEntryParams) (TimetableEntry, error) {
	row := q.db.QueryRow(ctx, upsertTimetableEntry,
		arg.TimetableID,
		arg.DayOfWeek,
		arg.PeriodNumber,
		arg.SubjectID,
		arg.TeacherID,
		arg.ClassroomID,
	)
	var i TimetableEntry
	err := row.Scan(
		&i.ID,
		&i.TimetableID,
		&i.DayOfWeek,
		&i.PeriodNumber,
		&i.SubjectID,
		&i.TeacherID,
		&i.ClassroomID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
