// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable_notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadTimetableNotifications = `-- name: CountUnreadTimetableNotifications :one
SELECT COUNT(*) FROM timetable_notifications
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadTimetableNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadTimetableNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTimetableNotification = `-- name: CreateTimetableNotification :one
INSERT INTO timetable_notifications (user_id, timetable_id, type, message)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, timetable_id, type, message, is_read, created_at
`

type CreateTimetableNotificationParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	TimetableID pgtype.UUID `json:"timetable_id"`
	Type        string      `json:"type"`
	Message     string      `json:"message"`
}

func (q *Queries) CreateTimetableNotification(ctx context.Context, arg CreateTimetableNotificationParams) (TimetableNotification, error) {
	row := q.db.QueryRow(ctx, createTimetableNotification,
		arg.UserID,
		arg.TimetableID,
		arg.Type,
		arg.Message,
	)
	var i TimetableNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TimetableID,
		&i.Type,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listTimetableNotificationsByUser = `-- name: ListTimetableNotificationsByUser :many
SELECT id, user_id, timetable_id, type, message, is_read, created_at FROM timetable_notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListTimetableNotificationsByUser(ctx context.Context, userID uuid.UUID) ([]TimetableNotification, error) {
	rows, err := q.db.Query(ctx, listTimetableNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimetableNotification{}
	for rows.Next() {
		var i TimetableNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TimetableID,
			&i.Type,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTimetableNotificationRead = `-- name: MarkTimetableNotificationRead :exec
UPDATE timetable_notifications
SET is_read = TRUE
WHERE id = $1 AND user_id = $2
`

type MarkTimetableNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkTimetableNotificationRead(ctx context.Context, arg MarkTimetableNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markTimetableNotificationRead, arg.ID, arg.UserID)
	return err
}
