// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (workflow_key, scope_key, state, inputs, proposal, trace, summary, created_by)
VALUES ($1, $2, 'proposed', $3, $4, $5, $6, $7)
RETURNING id, workflow_key, scope_key, state, inputs, proposal, trace, snapshot, summary, error, created_by, applied_by, created_at, updated_at, applied_at, reverted_at
`

type CreateWorkflowRunParams struct {
	WorkflowKey string      `json:"workflow_key"`
	ScopeKey    string      `json:"scope_key"`
	Inputs      []byte      `json:"inputs"`
	Proposal    []byte      `json:"proposal"`
	Trace       []byte      `json:"trace"`
	Summary     pgtype.Text `json:"summary"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.WorkflowKey,
		arg.ScopeKey,
		arg.Inputs,
		arg.Proposal,
		arg.Trace,
		arg.Summary,
		arg.CreatedBy,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowKey,
		&i.ScopeKey,
		&i.State,
		&i.Inputs,
		&i.Proposal,
		&i.Trace,
		&i.Snapshot,
		&i.Summary,
		&i.Error,
		&i.CreatedBy,
		&i.AppliedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedAt,
		&i.RevertedAt,
	)
	return i, err
}

const discardOpenWorkflowRuns = `-- name: DiscardOpenWorkflowRuns :exec
UPDATE workflow_runs SET state = 'discarded', updated_at = NOW()
WHERE workflow_key = $1 AND scope_key = $2 AND state = 'proposed'
`

type DiscardOpenWorkflowRunsParams struct {
	WorkflowKey string `json:"workflow_key"`
	ScopeKey    string `json:"scope_key"`
}

func (q *Queries) DiscardOpenWorkflowRuns(ctx context.Context, arg DiscardOpenWorkflowRunsParams) error {
	_, err := q.db.Exec(ctx, discardOpenWorkflowRuns, arg.WorkflowKey, arg.ScopeKey)
	return err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, workflow_key, scope_key, state, inputs, proposal, trace, snapshot, summary, error, created_by, applied_by, created_at, updated_at, applied_at, reverted_at FROM workflow_runs WHERE id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowKey,
		&i.ScopeKey,
		&i.State,
		&i.Inputs,
		&i.Proposal,
		&i.Trace,
		&i.Snapshot,
		&i.Summary,
		&i.Error,
		&i.CreatedBy,
		&i.AppliedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedAt,
		&i.RevertedAt,
	)
	return i, err
}

const getWorkflowRunForUpdate = `-- name: GetWorkflowRunForUpdate :one
SELECT id, workflow_key, scope_key, state, inputs, proposal, trace, snapshot, summary, error, created_by, applied_by, created_at, updated_at, applied_at, reverted_at FROM workflow_runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetWorkflowRunForUpdate(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRunForUpdate, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowKey,
		&i.ScopeKey,
		&i.State,
		&i.Inputs,
		&i.Proposal,
		&i.Trace,
		&i.Snapshot,
		&i.Summary,
		&i.Error,
		&i.CreatedBy,
		&i.AppliedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedAt,
		&i.RevertedAt,
	)
	return i, err
}

const latestWorkflowRuns = `-- name: LatestWorkflowRuns :many
SELECT DISTINCT ON (workflow_key) id, workflow_key, state, summary, created_at, applied_at
FROM workflow_runs
WHERE state <> 'discarded'
ORDER BY workflow_key, created_at DESC
`

type LatestWorkflowRunsRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkflowKey string             `json:"workflow_key"`
	State       string             `json:"state"`
	Summary     pgtype.Text        `json:"summary"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AppliedAt   pgtype.Timestamptz `json:"applied_at"`
}

// Latest run per workflow for the hub cards.
func (q *Queries) LatestWorkflowRuns(ctx context.Context) ([]LatestWorkflowRunsRow, error) {
	rows, err := q.db.Query(ctx, latestWorkflowRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestWorkflowRunsRow{}
	for rows.Next() {
		var i LatestWorkflowRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowKey,
			&i.State,
			&i.Summary,
			&i.CreatedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT r.id, r.workflow_key, r.scope_key, r.state, r.summary, r.error, r.created_at, r.applied_at, r.reverted_at,
       cu.full_name AS created_by_name, au.full_name AS applied_by_name
FROM workflow_runs r
LEFT JOIN users cu ON cu.id = r.created_by
LEFT JOIN users au ON au.id = r.applied_by
WHERE r.workflow_key = $1
ORDER BY r.created_at DESC
LIMIT 20
`

type ListWorkflowRunsRow struct {
	ID            uuid.UUID          `json:"id"`
	WorkflowKey   string             `json:"workflow_key"`
	ScopeKey      string             `json:"scope_key"`
	State         string             `json:"state"`
	Summary       pgtype.Text        `json:"summary"`
	Error         pgtype.Text        `json:"error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AppliedAt     pgtype.Timestamptz `json:"applied_at"`
	RevertedAt    pgtype.Timestamptz `json:"reverted_at"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
	AppliedByName pgtype.Text        `json:"applied_by_name"`
}

func (q *Queries) ListWorkflowRuns(ctx context.Context, workflowKey string) ([]ListWorkflowRunsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowRuns, workflowKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowRunsRow{}
	for rows.Next() {
		var i ListWorkflowRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowKey,
			&i.ScopeKey,
			&i.State,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.AppliedAt,
			&i.RevertedAt,
			&i.CreatedByName,
			&i.AppliedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkflowRunApplied = `-- name: MarkWorkflowRunApplied :exec
UPDATE workflow_runs
SET state = 'applied', snapshot = $2, trace = $3, summary = $4, applied_by = $5, applied_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type MarkWorkflowRunAppliedParams struct {
	ID        uuid.UUID   `json:"id"`
	Snapshot  []byte      `json:"snapshot"`
	Trace     []byte      `json:"trace"`
	Summary   pgtype.Text `json:"summary"`
	AppliedBy pgtype.UUID `json:"applied_by"`
}

func (q *Queries) MarkWorkflowRunApplied(ctx context.Context, arg MarkWorkflowRunAppliedParams) error {
	_, err := q.db.Exec(ctx, markWorkflowRunApplied,
		arg.ID,
		arg.Snapshot,
		arg.Trace,
		arg.Summary,
		arg.AppliedBy,
	)
	return err
}

const markWorkflowRunFailed = `-- name: MarkWorkflowRunFailed :exec
UPDATE workflow_runs SET state = 'failed', error = $2, trace = $3, updated_at = NOW() WHERE id = $1
`

type MarkWorkflowRunFailedParams struct {
	ID    uuid.UUID   `json:"id"`
	Error pgtype.Text `json:"error"`
	Trace []byte      `json:"trace"`
}

func (q *Queries) MarkWorkflowRunFailed(ctx context.Context, arg MarkWorkflowRunFailedParams) error {
	_, err := q.db.Exec(ctx, markWorkflowRunFailed, arg.ID, arg.Error, arg.Trace)
	return err
}

const markWorkflowRunState = `-- name: MarkWorkflowRunState :exec
UPDATE workflow_runs
SET state = $1::text, updated_at = NOW(),
    reverted_at = CASE WHEN $1::text = 'reverted' THEN NOW() ELSE reverted_at END
WHERE id = $2::uuid
`

type MarkWorkflowRunStateParams struct {
	State string    `json:"state"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) MarkWorkflowRunState(ctx context.Context, arg MarkWorkflowRunStateParams) error {
	_, err := q.db.Exec(ctx, markWorkflowRunState, arg.State, arg.ID)
	return err
}

const updateWorkflowRunProposal = `-- name: UpdateWorkflowRunProposal :exec
UPDATE workflow_runs SET proposal = $2, updated_at = NOW() WHERE id = $1
`

type UpdateWorkflowRunProposalParams struct {
	ID       uuid.UUID `json:"id"`
	Proposal []byte    `json:"proposal"`
}

func (q *Queries) UpdateWorkflowRunProposal(ctx context.Context, arg UpdateWorkflowRunProposalParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowRunProposal, arg.ID, arg.Proposal)
	return err
}

const wfAcademicYearLabelExists = `-- name: WfAcademicYearLabelExists :one
SELECT EXISTS (SELECT 1 FROM academic_years WHERE lower(label) = lower($1))
`

func (q *Queries) WfAcademicYearLabelExists(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, wfAcademicYearLabelExists, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const wfClassesHaveRecords = `-- name: WfClassesHaveRecords :one
SELECT (EXISTS (SELECT 1 FROM attendance_sessions a WHERE a.class_id = ANY($1::uuid[]))
     OR EXISTS (SELECT 1 FROM term_marks m JOIN terms t ON t.id = m.term_id
                WHERE t.academic_year_id = $2::uuid AND m.student_id = ANY($3::uuid[])))::bool AS has_records
`

type WfClassesHaveRecordsParams struct {
	ClassIds   []uuid.UUID `json:"class_ids"`
	Year       uuid.UUID   `json:"year"`
	StudentIds []uuid.UUID `json:"student_ids"`
}

// Attendance or marks already recorded in these classes; a placement can no longer be reverted.
func (q *Queries) WfClassesHaveRecords(ctx context.Context, arg WfClassesHaveRecordsParams) (bool, error) {
	row := q.db.QueryRow(ctx, wfClassesHaveRecords, arg.ClassIds, arg.Year, arg.StudentIds)
	var has_records bool
	err := row.Scan(&has_records)
	return has_records, err
}

const wfCopyGradeSectionGrades = `-- name: WfCopyGradeSectionGrades :exec
INSERT INTO grade_section_grades (grade_section_id, grade_id, academic_year_id)
SELECT $1::uuid, grade_id, $2::uuid FROM grade_section_grades WHERE grade_section_id = $3::uuid
`

type WfCopyGradeSectionGradesParams struct {
	NewSection uuid.UUID `json:"new_section"`
	NewYear    uuid.UUID `json:"new_year"`
	OldSection uuid.UUID `json:"old_section"`
}

func (q *Queries) WfCopyGradeSectionGrades(ctx context.Context, arg WfCopyGradeSectionGradesParams) error {
	_, err := q.db.Exec(ctx, wfCopyGradeSectionGrades, arg.NewSection, arg.NewYear, arg.OldSection)
	return err
}

const wfCopySectionHeads = `-- name: WfCopySectionHeads :execrows
INSERT INTO section_heads (academic_year_id, grade_id, stream_id, teacher_id)
SELECT $1::uuid, grade_id, stream_id, teacher_id FROM section_heads WHERE academic_year_id = $2::uuid
`

type WfCopySectionHeadsParams struct {
	NewYear uuid.UUID `json:"new_year"`
	OldYear uuid.UUID `json:"old_year"`
}

func (q *Queries) WfCopySectionHeads(ctx context.Context, arg WfCopySectionHeadsParams) (int64, error) {
	result, err := q.db.Exec(ctx, wfCopySectionHeads, arg.NewYear, arg.OldYear)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wfCopySubjectPeriodRequirements = `-- name: WfCopySubjectPeriodRequirements :execrows
INSERT INTO subject_period_requirements (academic_year_id, grade_id, subject_id, periods_per_week, lab_periods_per_week, double_period_blocks)
SELECT $1::uuid, grade_id, subject_id, periods_per_week, lab_periods_per_week, double_period_blocks
FROM subject_period_requirements WHERE academic_year_id = $2::uuid
`

type WfCopySubjectPeriodRequirementsParams struct {
	NewYear uuid.UUID `json:"new_year"`
	OldYear uuid.UUID `json:"old_year"`
}

func (q *Queries) WfCopySubjectPeriodRequirements(ctx context.Context, arg WfCopySubjectPeriodRequirementsParams) (int64, error) {
	result, err := q.db.Exec(ctx, wfCopySubjectPeriodRequirements, arg.NewYear, arg.OldYear)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wfCopyTimetablePeriods = `-- name: WfCopyTimetablePeriods :exec
INSERT INTO timetable_periods (grade_section_id, sort_order, period_number, start_time, end_time, slot_type)
SELECT $1::uuid, sort_order, period_number, start_time, end_time, slot_type FROM timetable_periods WHERE grade_section_id = $2::uuid
`

type WfCopyTimetablePeriodsParams struct {
	NewSection uuid.UUID `json:"new_section"`
	OldSection uuid.UUID `json:"old_section"`
}

func (q *Queries) WfCopyTimetablePeriods(ctx context.Context, arg WfCopyTimetablePeriodsParams) error {
	_, err := q.db.Exec(ctx, wfCopyTimetablePeriods, arg.NewSection, arg.OldSection)
	return err
}

const wfCopyTimetableSettings = `-- name: WfCopyTimetableSettings :execrows
INSERT INTO timetable_settings (academic_year_id, school_start_time, school_end_time, number_of_periods, period_duration_minutes, interval_duration_minutes)
SELECT $1::uuid, school_start_time, school_end_time, number_of_periods, period_duration_minutes, interval_duration_minutes
FROM timetable_settings WHERE academic_year_id = $2::uuid
`

type WfCopyTimetableSettingsParams struct {
	NewYear uuid.UUID `json:"new_year"`
	OldYear uuid.UUID `json:"old_year"`
}

func (q *Queries) WfCopyTimetableSettings(ctx context.Context, arg WfCopyTimetableSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, wfCopyTimetableSettings, arg.NewYear, arg.OldYear)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wfCreateAcademicYear = `-- name: WfCreateAcademicYear :one

INSERT INTO academic_years (label, start_date, end_date, is_current) VALUES ($1, $2, $3, FALSE) RETURNING id
`

type WfCreateAcademicYearParams struct {
	Label     string      `json:"label"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

// ---- W1 year rollover ----
func (q *Queries) WfCreateAcademicYear(ctx context.Context, arg WfCreateAcademicYearParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, wfCreateAcademicYear, arg.Label, arg.StartDate, arg.EndDate)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const wfCreateClass = `-- name: WfCreateClass :one
INSERT INTO classes (grade_id, academic_year_id, name, stream_id, stream_group_id, medium_id, home_classroom_id, form_teacher_id, capacity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type WfCreateClassParams struct {
	GradeID         uuid.UUID   `json:"grade_id"`
	AcademicYearID  uuid.UUID   `json:"academic_year_id"`
	Name            string      `json:"name"`
	StreamID        pgtype.UUID `json:"stream_id"`
	StreamGroupID   pgtype.UUID `json:"stream_group_id"`
	MediumID        pgtype.UUID `json:"medium_id"`
	HomeClassroomID pgtype.UUID `json:"home_classroom_id"`
	FormTeacherID   pgtype.UUID `json:"form_teacher_id"`
	Capacity        int32       `json:"capacity"`
}

func (q *Queries) WfCreateClass(ctx context.Context, arg WfCreateClassParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, wfCreateClass,
		arg.GradeID,
		arg.AcademicYearID,
		arg.Name,
		arg.StreamID,
		arg.StreamGroupID,
		arg.MediumID,
		arg.HomeClassroomID,
		arg.FormTeacherID,
		arg.Capacity,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const wfCreateGradeSection = `-- name: WfCreateGradeSection :one
INSERT INTO grade_sections (academic_year_id, name, interval_start_time, interval_end_time, section_head_teacher_id, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type WfCreateGradeSectionParams struct {
	AcademicYearID       uuid.UUID   `json:"academic_year_id"`
	Name                 string      `json:"name"`
	IntervalStartTime    pgtype.Time `json:"interval_start_time"`
	IntervalEndTime      pgtype.Time `json:"interval_end_time"`
	SectionHeadTeacherID pgtype.UUID `json:"section_head_teacher_id"`
	SortOrder            int32       `json:"sort_order"`
}

func (q *Queries) WfCreateGradeSection(ctx context.Context, arg WfCreateGradeSectionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, wfCreateGradeSection,
		arg.AcademicYearID,
		arg.Name,
		arg.IntervalStartTime,
		arg.IntervalEndTime,
		arg.SectionHeadTeacherID,
		arg.SortOrder,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const wfCreateGuardian = `-- name: WfCreateGuardian :one
INSERT INTO guardians (full_name, relationship, phone, email, nic_number)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type WfCreateGuardianParams struct {
	FullName     string      `json:"full_name"`
	Relationship string      `json:"relationship"`
	Phone        string      `json:"phone"`
	Email        pgtype.Text `json:"email"`
	NicNumber    string      `json:"nic_number"`
}

func (q *Queries) WfCreateGuardian(ctx context.Context, arg WfCreateGuardianParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, wfCreateGuardian,
		arg.FullName,
		arg.Relationship,
		arg.Phone,
		arg.Email,
		arg.NicNumber,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const wfCreateIntake = `-- name: WfCreateIntake :exec
INSERT INTO student_intakes (student_id, academic_year_id, grade_id, medium_id) VALUES ($1, $2, $3, $4)
`

type WfCreateIntakeParams struct {
	StudentID      uuid.UUID   `json:"student_id"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	GradeID        uuid.UUID   `json:"grade_id"`
	MediumID       pgtype.UUID `json:"medium_id"`
}

func (q *Queries) WfCreateIntake(ctx context.Context, arg WfCreateIntakeParams) error {
	_, err := q.db.Exec(ctx, wfCreateIntake,
		arg.StudentID,
		arg.AcademicYearID,
		arg.GradeID,
		arg.MediumID,
	)
	return err
}

const wfCreateIntakeStudent = `-- name: WfCreateIntakeStudent :one
INSERT INTO student_profiles (full_name, index_number, address, phone, gender, house_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type WfCreateIntakeStudentParams struct {
	FullName    string      `json:"full_name"`
	IndexNumber string      `json:"index_number"`
	Address     pgtype.Text `json:"address"`
	Phone       pgtype.Text `json:"phone"`
	Gender      pgtype.Text `json:"gender"`
	HouseID     pgtype.UUID `json:"house_id"`
}

func (q *Queries) WfCreateIntakeStudent(ctx context.Context, arg WfCreateIntakeStudentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, wfCreateIntakeStudent,
		arg.FullName,
		arg.IndexNumber,
		arg.Address,
		arg.Phone,
		arg.Gender,
		arg.HouseID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const wfCreateTerm = `-- name: WfCreateTerm :exec
INSERT INTO terms (academic_year_id, name, start_date, end_date, sort_order, is_current) VALUES ($1, $2, $3, $4, $5, FALSE)
`

type WfCreateTermParams struct {
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	Name           string      `json:"name"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	SortOrder      int32       `json:"sort_order"`
}

func (q *Queries) WfCreateTerm(ctx context.Context, arg WfCreateTermParams) error {
	_, err := q.db.Exec(ctx, wfCreateTerm,
		arg.AcademicYearID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.SortOrder,
	)
	return err
}

const wfCurrentTerm = `-- name: WfCurrentTerm :one
SELECT id FROM terms WHERE is_current = TRUE LIMIT 1
`

func (q *Queries) WfCurrentTerm(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, wfCurrentTerm)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const wfDeleteAcademicYear = `-- name: WfDeleteAcademicYear :exec
DELETE FROM academic_years WHERE id = $1
`

func (q *Queries) WfDeleteAcademicYear(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, wfDeleteAcademicYear, id)
	return err
}

const wfDeleteEmptyClasses = `-- name: WfDeleteEmptyClasses :exec
DELETE FROM classes c WHERE c.id = ANY($1::uuid[]) AND NOT EXISTS (SELECT 1 FROM class_students cs WHERE cs.class_id = c.id)
`

func (q *Queries) WfDeleteEmptyClasses(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, wfDeleteEmptyClasses, ids)
	return err
}

const wfDeleteIntakes = `-- name: WfDeleteIntakes :exec
DELETE FROM student_intakes WHERE student_id = ANY($1::uuid[])
`

func (q *Queries) WfDeleteIntakes(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, wfDeleteIntakes, ids)
	return err
}

const wfDeleteStudents = `-- name: WfDeleteStudents :exec
DELETE FROM student_profiles WHERE id = ANY($1::uuid[])
`

func (q *Queries) WfDeleteStudents(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, wfDeleteStudents, ids)
	return err
}

const wfDeleteUnlinkedGuardians = `-- name: WfDeleteUnlinkedGuardians :exec
DELETE FROM guardians g WHERE g.id = ANY($1::uuid[])
  AND NOT EXISTS (SELECT 1 FROM student_guardians sg WHERE sg.guardian_id = g.id)
`

func (q *Queries) WfDeleteUnlinkedGuardians(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, wfDeleteUnlinkedGuardians, ids)
	return err
}

const wfDeleteYearClasses = `-- name: WfDeleteYearClasses :exec
DELETE FROM classes WHERE academic_year_id = $1
`

// Classes RESTRICT their year, so they go first; the rest cascades from the year.
func (q *Queries) WfDeleteYearClasses(ctx context.Context, academicYearID uuid.UUID) error {
	_, err := q.db.Exec(ctx, wfDeleteYearClasses, academicYearID)
	return err
}

const wfExistingIndexNumbers = `-- name: WfExistingIndexNumbers :many
SELECT index_number FROM student_profiles WHERE index_number = ANY($1::text[])
`

func (q *Queries) WfExistingIndexNumbers(ctx context.Context, numbers []string) ([]string, error) {
	rows, err := q.db.Query(ctx, wfExistingIndexNumbers, numbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var index_number string
		if err := rows.Scan(&index_number); err != nil {
			return nil, err
		}
		items = append(items, index_number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfGetAcademicYear = `-- name: WfGetAcademicYear :one
SELECT id, label, start_date, end_date, is_current FROM academic_years WHERE id = $1
`

type WfGetAcademicYearRow struct {
	ID        uuid.UUID   `json:"id"`
	Label     string      `json:"label"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	IsCurrent bool        `json:"is_current"`
}

func (q *Queries) WfGetAcademicYear(ctx context.Context, id uuid.UUID) (WfGetAcademicYearRow, error) {
	row := q.db.QueryRow(ctx, wfGetAcademicYear, id)
	var i WfGetAcademicYearRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
	)
	return i, err
}

const wfGradesWithChoiceGroups = `-- name: WfGradesWithChoiceGroups :many
SELECT DISTINCT l.grade_id::uuid AS grade_id
FROM levels l JOIN selection_groups g ON g.level_id = l.id
WHERE l.grade_id IS NOT NULL AND (SELECT COUNT(*) FROM group_subjects gs WHERE gs.group_id = g.id) > g.max_select
`

// Grades whose curriculum has a real subject choice; their incoming students default to by_subject_choice.
func (q *Queries) WfGradesWithChoiceGroups(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, wfGradesWithChoiceGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var grade_id uuid.UUID
		if err := rows.Scan(&grade_id); err != nil {
			return nil, err
		}
		items = append(items, grade_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfGradesWithStreamLevels = `-- name: WfGradesWithStreamLevels :many
SELECT DISTINCT grade_id::uuid AS grade_id FROM levels WHERE grade_id IS NOT NULL AND stream_id IS NOT NULL
`

// Grades whose levels are tied to an A/L stream; their incoming students default to by_stream.
func (q *Queries) WfGradesWithStreamLevels(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, wfGradesWithStreamLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var grade_id uuid.UUID
		if err := rows.Scan(&grade_id); err != nil {
			return nil, err
		}
		items = append(items, grade_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfGuardiansByNIC = `-- name: WfGuardiansByNIC :many
SELECT id, nic_number, full_name FROM guardians WHERE nic_number = ANY($1::text[])
`

type WfGuardiansByNICRow struct {
	ID        uuid.UUID `json:"id"`
	NicNumber string    `json:"nic_number"`
	FullName  string    `json:"full_name"`
}

func (q *Queries) WfGuardiansByNIC(ctx context.Context, nics []string) ([]WfGuardiansByNICRow, error) {
	rows, err := q.db.Query(ctx, wfGuardiansByNIC, nics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfGuardiansByNICRow{}
	for rows.Next() {
		var i WfGuardiansByNICRow
		if err := rows.Scan(&i.ID, &i.NicNumber, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfIntakeStudents = `-- name: WfIntakeStudents :many
SELECT sp.id, sp.full_name, sp.index_number, COALESCE(sp.gender, '')::text AS gender,
       COALESCE(sp.house_id::text, '')::text AS house_id,
       i.grade_id, COALESCE(i.medium_id::text, '')::text AS medium_id
FROM student_intakes i
JOIN student_profiles sp ON sp.id = i.student_id
WHERE i.academic_year_id = $1 AND sp.enrollment_status = 'active'
ORDER BY sp.full_name, sp.id
`

type WfIntakeStudentsRow struct {
	ID          uuid.UUID `json:"id"`
	FullName    string    `json:"full_name"`
	IndexNumber string    `json:"index_number"`
	Gender      string    `json:"gender"`
	HouseID     string    `json:"house_id"`
	GradeID     uuid.UUID `json:"grade_id"`
	MediumID    string    `json:"medium_id"`
}

// Admitted students waiting for a class in the target year.
func (q *Queries) WfIntakeStudents(ctx context.Context, academicYearID uuid.UUID) ([]WfIntakeStudentsRow, error) {
	rows, err := q.db.Query(ctx, wfIntakeStudents, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfIntakeStudentsRow{}
	for rows.Next() {
		var i WfIntakeStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.IndexNumber,
			&i.Gender,
			&i.HouseID,
			&i.GradeID,
			&i.MediumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfIntakesByIDs = `-- name: WfIntakesByIDs :many
SELECT student_id, academic_year_id, grade_id, medium_id FROM student_intakes WHERE student_id = ANY($1::uuid[])
`

type WfIntakesByIDsRow struct {
	StudentID      uuid.UUID   `json:"student_id"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	GradeID        uuid.UUID   `json:"grade_id"`
	MediumID       pgtype.UUID `json:"medium_id"`
}

func (q *Queries) WfIntakesByIDs(ctx context.Context, ids []uuid.UUID) ([]WfIntakesByIDsRow, error) {
	rows, err := q.db.Query(ctx, wfIntakesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfIntakesByIDsRow{}
	for rows.Next() {
		var i WfIntakesByIDsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.AcademicYearID,
			&i.GradeID,
			&i.MediumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfLatestAverages = `-- name: WfLatestAverages :many
WITH latest AS (
    SELECT t.id FROM terms t
    WHERE t.academic_year_id = $2::uuid AND EXISTS (SELECT 1 FROM term_marks m WHERE m.term_id = t.id)
    ORDER BY t.sort_order DESC, t.start_date DESC LIMIT 1
)
SELECT m.student_id, (AVG(m.marks / NULLIF(m.max_marks, 0) * 100))::float8 AS average
FROM term_marks m JOIN latest ON latest.id = m.term_id
WHERE m.student_id = ANY($1::uuid[]) AND NOT m.is_absent
GROUP BY m.student_id
`

type WfLatestAveragesParams struct {
	Ids  []uuid.UUID `json:"ids"`
	Year uuid.UUID   `json:"year"`
}

type WfLatestAveragesRow struct {
	StudentID uuid.UUID `json:"student_id"`
	Average   float64   `json:"average"`
}

// Each student's average percentage in the latest term of the year that has marks.
func (q *Queries) WfLatestAverages(ctx context.Context, arg WfLatestAveragesParams) ([]WfLatestAveragesRow, error) {
	rows, err := q.db.Query(ctx, wfLatestAverages, arg.Ids, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfLatestAveragesRow{}
	for rows.Next() {
		var i WfLatestAveragesRow
		if err := rows.Scan(&i.StudentID, &i.Average); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfLeastUsedHouse = `-- name: WfLeastUsedHouse :one
SELECT h.id FROM houses h
LEFT JOIN student_profiles sp ON sp.house_id = h.id AND sp.enrollment_status = 'active'
GROUP BY h.id, h.name
ORDER BY COUNT(sp.id), h.name
LIMIT 1
`

// The house with the fewest active students, so imported students spread evenly.
func (q *Queries) WfLeastUsedHouse(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, wfLeastUsedHouse)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const wfLinkGuardian = `-- name: WfLinkGuardian :exec
INSERT INTO student_guardians (student_id, guardian_id, is_primary_contact) VALUES ($1, $2, TRUE)
ON CONFLICT DO NOTHING
`

type WfLinkGuardianParams struct {
	StudentID  uuid.UUID `json:"student_id"`
	GuardianID uuid.UUID `json:"guardian_id"`
}

func (q *Queries) WfLinkGuardian(ctx context.Context, arg WfLinkGuardianParams) error {
	_, err := q.db.Exec(ctx, wfLinkGuardian, arg.StudentID, arg.GuardianID)
	return err
}

const wfListAcademicYears = `-- name: WfListAcademicYears :many

SELECT id, label, start_date, end_date, is_current FROM academic_years ORDER BY start_date DESC
`

type WfListAcademicYearsRow struct {
	ID        uuid.UUID   `json:"id"`
	Label     string      `json:"label"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	IsCurrent bool        `json:"is_current"`
}

// ---- Shared reads ----
func (q *Queries) WfListAcademicYears(ctx context.Context) ([]WfListAcademicYearsRow, error) {
	rows, err := q.db.Query(ctx, wfListAcademicYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfListAcademicYearsRow{}
	for rows.Next() {
		var i WfListAcademicYearsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfListActiveStudentsInGrades = `-- name: WfListActiveStudentsInGrades :many

SELECT sp.id, sp.full_name, sp.index_number, c.name AS class_name, g.id AS grade_id, g.name AS grade_name, g.sort_order AS grade_order
FROM student_profiles sp
JOIN class_students cs ON cs.student_id = sp.id
JOIN classes c ON c.id = cs.class_id AND c.academic_year_id = $1::uuid
JOIN grades g ON g.id = c.grade_id
WHERE sp.enrollment_status = 'active' AND g.id = ANY($2::uuid[])
ORDER BY g.sort_order, c.name, sp.full_name
`

type WfListActiveStudentsInGradesParams struct {
	Year     uuid.UUID   `json:"year"`
	GradeIds []uuid.UUID `json:"grade_ids"`
}

type WfListActiveStudentsInGradesRow struct {
	ID          uuid.UUID `json:"id"`
	FullName    string    `json:"full_name"`
	IndexNumber string    `json:"index_number"`
	ClassName   string    `json:"class_name"`
	GradeID     uuid.UUID `json:"grade_id"`
	GradeName   string    `json:"grade_name"`
	GradeOrder  int32     `json:"grade_order"`
}

// ---- W2 leavers ----
func (q *Queries) WfListActiveStudentsInGrades(ctx context.Context, arg WfListActiveStudentsInGradesParams) ([]WfListActiveStudentsInGradesRow, error) {
	rows, err := q.db.Query(ctx, wfListActiveStudentsInGrades, arg.Year, arg.GradeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfListActiveStudentsInGradesRow{}
	for rows.Next() {
		var i WfListActiveStudentsInGradesRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.IndexNumber,
			&i.ClassName,
			&i.GradeID,
			&i.GradeName,
			&i.GradeOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfListGradeSections = `-- name: WfListGradeSections :many
SELECT id, name, interval_start_time, interval_end_time, section_head_teacher_id, sort_order FROM grade_sections WHERE academic_year_id = $1 ORDER BY sort_order, name
`

type WfListGradeSectionsRow struct {
	ID                   uuid.UUID   `json:"id"`
	Name                 string      `json:"name"`
	IntervalStartTime    pgtype.Time `json:"interval_start_time"`
	IntervalEndTime      pgtype.Time `json:"interval_end_time"`
	SectionHeadTeacherID pgtype.UUID `json:"section_head_teacher_id"`
	SortOrder            int32       `json:"sort_order"`
}

func (q *Queries) WfListGradeSections(ctx context.Context, academicYearID uuid.UUID) ([]WfListGradeSectionsRow, error) {
	rows, err := q.db.Query(ctx, wfListGradeSections, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfListGradeSectionsRow{}
	for rows.Next() {
		var i WfListGradeSectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IntervalStartTime,
			&i.IntervalEndTime,
			&i.SectionHeadTeacherID,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfListGrades = `-- name: WfListGrades :many
SELECT id, name, sort_order FROM grades ORDER BY sort_order
`

type WfListGradesRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) WfListGrades(ctx context.Context) ([]WfListGradesRow, error) {
	rows, err := q.db.Query(ctx, wfListGrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfListGradesRow{}
	for rows.Next() {
		var i WfListGradesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfListMediums = `-- name: WfListMediums :many

SELECT id, name FROM mediums ORDER BY name
`

type WfListMediumsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// ---- W4 intake ----
func (q *Queries) WfListMediums(ctx context.Context) ([]WfListMediumsRow, error) {
	rows, err := q.db.Query(ctx, wfListMediums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfListMediumsRow{}
	for rows.Next() {
		var i WfListMediumsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfListTerms = `-- name: WfListTerms :many
SELECT id, name, start_date, end_date, sort_order, is_current FROM terms WHERE academic_year_id = $1 ORDER BY sort_order, start_date
`

type WfListTermsRow struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	SortOrder int32       `json:"sort_order"`
	IsCurrent bool        `json:"is_current"`
}

func (q *Queries) WfListTerms(ctx context.Context, academicYearID uuid.UUID) ([]WfListTermsRow, error) {
	rows, err := q.db.Query(ctx, wfListTerms, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfListTermsRow{}
	for rows.Next() {
		var i WfListTermsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.SortOrder,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfListYearClasses = `-- name: WfListYearClasses :many
SELECT
    c.id, c.name, c.grade_id, g.name AS grade_name, g.sort_order AS grade_order,
    c.stream_id, s.name AS stream_name, c.stream_group_id, sg.name AS stream_group_name,
    c.medium_id, m.name AS medium_name, c.home_classroom_id, hc.name AS homeroom_name,
    c.form_teacher_id, c.capacity,
    (SELECT COUNT(*) FROM class_students cs WHERE cs.class_id = c.id)::int AS student_count
FROM classes c
JOIN grades g ON g.id = c.grade_id
LEFT JOIN streams s        ON s.id = c.stream_id
LEFT JOIN stream_groups sg ON sg.id = c.stream_group_id
LEFT JOIN mediums m        ON m.id = c.medium_id
LEFT JOIN classrooms hc    ON hc.id = c.home_classroom_id
WHERE c.academic_year_id = $1
ORDER BY g.sort_order, c.name
`

type WfListYearClassesRow struct {
	ID              uuid.UUID   `json:"id"`
	Name            string      `json:"name"`
	GradeID         uuid.UUID   `json:"grade_id"`
	GradeName       string      `json:"grade_name"`
	GradeOrder      int32       `json:"grade_order"`
	StreamID        pgtype.UUID `json:"stream_id"`
	StreamName      pgtype.Text `json:"stream_name"`
	StreamGroupID   pgtype.UUID `json:"stream_group_id"`
	StreamGroupName pgtype.Text `json:"stream_group_name"`
	MediumID        pgtype.UUID `json:"medium_id"`
	MediumName      pgtype.Text `json:"medium_name"`
	HomeClassroomID pgtype.UUID `json:"home_classroom_id"`
	HomeroomName    pgtype.Text `json:"homeroom_name"`
	FormTeacherID   pgtype.UUID `json:"form_teacher_id"`
	Capacity        int32       `json:"capacity"`
	StudentCount    int32       `json:"student_count"`
}

func (q *Queries) WfListYearClasses(ctx context.Context, academicYearID uuid.UUID) ([]WfListYearClassesRow, error) {
	rows, err := q.db.Query(ctx, wfListYearClasses, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfListYearClassesRow{}
	for rows.Next() {
		var i WfListYearClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GradeID,
			&i.GradeName,
			&i.GradeOrder,
			&i.StreamID,
			&i.StreamName,
			&i.StreamGroupID,
			&i.StreamGroupName,
			&i.MediumID,
			&i.MediumName,
			&i.HomeClassroomID,
			&i.HomeroomName,
			&i.FormTeacherID,
			&i.Capacity,
			&i.StudentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfMarkStudentsLeft = `-- name: WfMarkStudentsLeft :execrows
UPDATE student_profiles SET enrollment_status = 'left', left_at = $1::timestamptz, updated_at = NOW()
WHERE id = ANY($2::uuid[]) AND enrollment_status = 'active'
`

type WfMarkStudentsLeftParams struct {
	LeftAt pgtype.Timestamptz `json:"left_at"`
	Ids    []uuid.UUID        `json:"ids"`
}

func (q *Queries) WfMarkStudentsLeft(ctx context.Context, arg WfMarkStudentsLeftParams) (int64, error) {
	result, err := q.db.Exec(ctx, wfMarkStudentsLeft, arg.LeftAt, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wfPromotionPolicies = `-- name: WfPromotionPolicies :many
SELECT from_grade_id, policy, spread_by_marks FROM promotion_policies
`

type WfPromotionPoliciesRow struct {
	FromGradeID   uuid.UUID `json:"from_grade_id"`
	Policy        string    `json:"policy"`
	SpreadByMarks bool      `json:"spread_by_marks"`
}

func (q *Queries) WfPromotionPolicies(ctx context.Context) ([]WfPromotionPoliciesRow, error) {
	rows, err := q.db.Query(ctx, wfPromotionPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfPromotionPoliciesRow{}
	for rows.Next() {
		var i WfPromotionPoliciesRow
		if err := rows.Scan(&i.FromGradeID, &i.Policy, &i.SpreadByMarks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfPromotionStudents = `-- name: WfPromotionStudents :many

SELECT sp.id, sp.full_name, sp.index_number, COALESCE(sp.gender, '')::text AS gender,
       COALESCE(sp.house_id::text, '')::text AS house_id,
       c.name AS class_name, c.grade_id, COALESCE(c.medium_id::text, '')::text AS medium_id
FROM student_profiles sp
JOIN class_students cs ON cs.student_id = sp.id
JOIN classes c ON c.id = cs.class_id AND c.academic_year_id = $1
WHERE sp.enrollment_status = 'active'
ORDER BY sp.full_name, sp.id
`

type WfPromotionStudentsRow struct {
	ID          uuid.UUID `json:"id"`
	FullName    string    `json:"full_name"`
	IndexNumber string    `json:"index_number"`
	Gender      string    `json:"gender"`
	HouseID     string    `json:"house_id"`
	ClassName   string    `json:"class_name"`
	GradeID     uuid.UUID `json:"grade_id"`
	MediumID    string    `json:"medium_id"`
}

// ---- W5 promotion ----
// Active students in the source year with what placement needs: class, grade, medium, gender, house.
func (q *Queries) WfPromotionStudents(ctx context.Context, academicYearID uuid.UUID) ([]WfPromotionStudentsRow, error) {
	rows, err := q.db.Query(ctx, wfPromotionStudents, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfPromotionStudentsRow{}
	for rows.Next() {
		var i WfPromotionStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.IndexNumber,
			&i.Gender,
			&i.HouseID,
			&i.ClassName,
			&i.GradeID,
			&i.MediumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfRestoreIntake = `-- name: WfRestoreIntake :exec
INSERT INTO student_intakes (student_id, academic_year_id, grade_id, medium_id) VALUES ($1, $2, $3, $4)
ON CONFLICT (student_id) DO NOTHING
`

type WfRestoreIntakeParams struct {
	StudentID      uuid.UUID   `json:"student_id"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	GradeID        uuid.UUID   `json:"grade_id"`
	MediumID       pgtype.UUID `json:"medium_id"`
}

func (q *Queries) WfRestoreIntake(ctx context.Context, arg WfRestoreIntakeParams) error {
	_, err := q.db.Exec(ctx, wfRestoreIntake,
		arg.StudentID,
		arg.AcademicYearID,
		arg.GradeID,
		arg.MediumID,
	)
	return err
}

const wfRestoreStudentsActive = `-- name: WfRestoreStudentsActive :execrows
UPDATE student_profiles SET enrollment_status = 'active', left_at = NULL, updated_at = NOW()
WHERE id = ANY($1::uuid[]) AND enrollment_status = 'left' AND erased_at IS NULL
`

func (q *Queries) WfRestoreStudentsActive(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, wfRestoreStudentsActive, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wfSchoolType = `-- name: WfSchoolType :one
SELECT COALESCE(school_type, '')::text AS school_type FROM school LIMIT 1
`

func (q *Queries) WfSchoolType(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, wfSchoolType)
	var school_type string
	err := row.Scan(&school_type)
	return school_type, err
}

const wfSetCurrentTerm = `-- name: WfSetCurrentTerm :exec
UPDATE terms SET is_current = (id = $1) WHERE id = $1 OR is_current = TRUE
`

func (q *Queries) WfSetCurrentTerm(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, wfSetCurrentTerm, id)
	return err
}

const wfSetCurrentYear = `-- name: WfSetCurrentYear :exec
UPDATE academic_years SET is_current = (id = $1) WHERE id = $1 OR is_current = TRUE
`

func (q *Queries) WfSetCurrentYear(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, wfSetCurrentYear, id)
	return err
}

const wfSetStudentUser = `-- name: WfSetStudentUser :exec
UPDATE student_profiles SET user_id = $2, updated_at = NOW() WHERE id = $1
`

type WfSetStudentUserParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) WfSetStudentUser(ctx context.Context, arg WfSetStudentUserParams) error {
	_, err := q.db.Exec(ctx, wfSetStudentUser, arg.ID, arg.UserID)
	return err
}

const wfStudentChoices = `-- name: WfStudentChoices :many
SELECT e.student_id, s.name AS subject_name, e.subject_id,
       COALESCE(l.stream_id::text, '')::text AS stream_id,
       COALESCE(l.stream_group_id::text, '')::text AS stream_group_id,
       ((SELECT COUNT(*) FROM group_subjects gs WHERE gs.group_id = g.id) > g.max_select)::bool AS is_choice
FROM student_subject_enrollments e
JOIN selection_groups g ON g.id = e.group_id
JOIN levels l ON l.id = g.level_id
JOIN subjects s ON s.id = e.subject_id
WHERE e.academic_year_id = $1::uuid AND e.student_id = ANY($2::uuid[])
ORDER BY e.student_id, s.name
`

type WfStudentChoicesParams struct {
	Year uuid.UUID   `json:"year"`
	Ids  []uuid.UUID `json:"ids"`
}

type WfStudentChoicesRow struct {
	StudentID     uuid.UUID `json:"student_id"`
	SubjectName   string    `json:"subject_name"`
	SubjectID     uuid.UUID `json:"subject_id"`
	StreamID      string    `json:"stream_id"`
	StreamGroupID string    `json:"stream_group_id"`
	IsChoice      bool      `json:"is_choice"`
}

// Each student's optional subjects for the target year, and the stream of the level they are in.
// A group is a real choice when it offers more subjects than a student may take.
func (q *Queries) WfStudentChoices(ctx context.Context, arg WfStudentChoicesParams) ([]WfStudentChoicesRow, error) {
	rows, err := q.db.Query(ctx, wfStudentChoices, arg.Year, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfStudentChoicesRow{}
	for rows.Next() {
		var i WfStudentChoicesRow
		if err := rows.Scan(
			&i.StudentID,
			&i.SubjectName,
			&i.SubjectID,
			&i.StreamID,
			&i.StreamGroupID,
			&i.IsChoice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfStudentsInUse = `-- name: WfStudentsInUse :one
SELECT (EXISTS (SELECT 1 FROM student_profiles WHERE id = ANY($1::uuid[]) AND user_id IS NOT NULL)
     OR EXISTS (SELECT 1 FROM class_students WHERE student_id = ANY($1::uuid[]))
     OR EXISTS (SELECT 1 FROM student_subject_enrollments WHERE student_id = ANY($1::uuid[]))
     OR EXISTS (SELECT 1 FROM attendance_records WHERE student_id = ANY($1::uuid[]))
     OR EXISTS (SELECT 1 FROM term_marks WHERE student_id = ANY($1::uuid[])))::bool AS in_use
`

// An imported student can no longer be removed once they have an account, a class, subjects or records.
func (q *Queries) WfStudentsInUse(ctx context.Context, ids []uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, wfStudentsInUse, ids)
	var in_use bool
	err := row.Scan(&in_use)
	return in_use, err
}

const wfStudentsWithoutAccount = `-- name: WfStudentsWithoutAccount :many
SELECT id, full_name, index_number FROM student_profiles
WHERE index_number = ANY($1::text[]) AND user_id IS NULL
`

type WfStudentsWithoutAccountRow struct {
	ID          uuid.UUID `json:"id"`
	FullName    string    `json:"full_name"`
	IndexNumber string    `json:"index_number"`
}

func (q *Queries) WfStudentsWithoutAccount(ctx context.Context, numbers []string) ([]WfStudentsWithoutAccountRow, error) {
	rows, err := q.db.Query(ctx, wfStudentsWithoutAccount, numbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfStudentsWithoutAccountRow{}
	for rows.Next() {
		var i WfStudentsWithoutAccountRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.IndexNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfTargetOccupancy = `-- name: WfTargetOccupancy :many
SELECT cs.class_id, COUNT(*)::int AS taken
FROM class_students cs
JOIN classes c ON c.id = cs.class_id AND c.academic_year_id = $1::uuid
WHERE NOT (cs.student_id = ANY($2::uuid[]))
GROUP BY cs.class_id
`

type WfTargetOccupancyParams struct {
	Year    uuid.UUID   `json:"year"`
	Exclude []uuid.UUID `json:"exclude"`
}

type WfTargetOccupancyRow struct {
	ClassID uuid.UUID `json:"class_id"`
	Taken   int32     `json:"taken"`
}

// Seats already taken in target classes by students outside this promotion (for example placed by hand).
func (q *Queries) WfTargetOccupancy(ctx context.Context, arg WfTargetOccupancyParams) ([]WfTargetOccupancyRow, error) {
	rows, err := q.db.Query(ctx, wfTargetOccupancy, arg.Year, arg.Exclude)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfTargetOccupancyRow{}
	for rows.Next() {
		var i WfTargetOccupancyRow
		if err := rows.Scan(&i.ClassID, &i.Taken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfUpsertPromotionPolicy = `-- name: WfUpsertPromotionPolicy :exec
INSERT INTO promotion_policies (from_grade_id, policy, spread_by_marks) VALUES ($1, $2, $3)
ON CONFLICT (from_grade_id) DO UPDATE SET policy = EXCLUDED.policy, spread_by_marks = EXCLUDED.spread_by_marks, updated_at = NOW()
`

type WfUpsertPromotionPolicyParams struct {
	FromGradeID   uuid.UUID `json:"from_grade_id"`
	Policy        string    `json:"policy"`
	SpreadByMarks bool      `json:"spread_by_marks"`
}

func (q *Queries) WfUpsertPromotionPolicy(ctx context.Context, arg WfUpsertPromotionPolicyParams) error {
	_, err := q.db.Exec(ctx, wfUpsertPromotionPolicy, arg.FromGradeID, arg.Policy, arg.SpreadByMarks)
	return err
}

const wfYearAssignments = `-- name: WfYearAssignments :many
SELECT cs.student_id, cs.class_id
FROM class_students cs JOIN classes c ON c.id = cs.class_id AND c.academic_year_id = $1::uuid
WHERE cs.student_id = ANY($2::uuid[])
`

type WfYearAssignmentsParams struct {
	Year uuid.UUID   `json:"year"`
	Ids  []uuid.UUID `json:"ids"`
}

type WfYearAssignmentsRow struct {
	StudentID uuid.UUID `json:"student_id"`
	ClassID   uuid.UUID `json:"class_id"`
}

func (q *Queries) WfYearAssignments(ctx context.Context, arg WfYearAssignmentsParams) ([]WfYearAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, wfYearAssignments, arg.Year, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfYearAssignmentsRow{}
	for rows.Next() {
		var i WfYearAssignmentsRow
		if err := rows.Scan(&i.StudentID, &i.ClassID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wfYearHasActivity = `-- name: WfYearHasActivity :one
SELECT (EXISTS (SELECT 1 FROM class_students cs JOIN classes c ON c.id = cs.class_id WHERE c.academic_year_id = $1)
    OR EXISTS (SELECT 1 FROM attendance_sessions a JOIN classes c ON c.id = a.class_id WHERE c.academic_year_id = $1)
    OR EXISTS (SELECT 1 FROM timetables t WHERE t.academic_year_id = $1)
    OR EXISTS (SELECT 1 FROM student_subject_enrollments e WHERE e.academic_year_id = $1))::bool AS has_activity
`

// True once anything real is recorded against the year's classes; a rollover can no longer be reverted.
func (q *Queries) WfYearHasActivity(ctx context.Context, academicYearID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, wfYearHasActivity, academicYearID)
	var has_activity bool
	err := row.Scan(&has_activity)
	return has_activity, err
}

const wfYearReadiness = `-- name: WfYearReadiness :one

SELECT
    (SELECT COUNT(*) FROM classes c WHERE c.academic_year_id = $1)::int AS classes,
    (SELECT COUNT(*) FROM class_students cs JOIN classes c ON c.id = cs.class_id WHERE c.academic_year_id = $1)::int AS students,
    (SELECT COUNT(DISTINCT t.class_id) FROM timetables t WHERE t.academic_year_id = $1 AND t.status = 'published')::int AS published_timetables,
    (SELECT COUNT(*) FROM terms tr WHERE tr.academic_year_id = $1)::int AS terms
`

type WfYearReadinessRow struct {
	Classes             int32 `json:"classes"`
	Students            int32 `json:"students"`
	PublishedTimetables int32 `json:"published_timetables"`
	Terms               int32 `json:"terms"`
}

// ---- W8 go live ----
func (q *Queries) WfYearReadiness(ctx context.Context, academicYearID uuid.UUID) (WfYearReadinessRow, error) {
	row := q.db.QueryRow(ctx, wfYearReadiness, academicYearID)
	var i WfYearReadinessRow
	err := row.Scan(
		&i.Classes,
		&i.Students,
		&i.PublishedTimetables,
		&i.Terms,
	)
	return i, err
}
